-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vgg_accelerator_layer_block_1_16_32_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    s_input_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    s_input_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    s_input_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    s_input_empty_n : IN STD_LOGIC;
    s_input_read : OUT STD_LOGIC;
    s_conv1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    s_conv1_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    s_conv1_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    s_conv1_full_n : IN STD_LOGIC;
    s_conv1_write : OUT STD_LOGIC );
end;


architecture behav of vgg_accelerator_layer_block_1_16_32_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 : STD_LOGIC;
    signal void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 : STD_LOGIC;
    signal void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 : STD_LOGIC;
    signal void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 : STD_LOGIC;
    signal void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_done : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_idle : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_ready : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_idle : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_ready : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_write : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_input_read : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 : STD_LOGIC;
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call8 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vgg_accelerator_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 : OUT STD_LOGIC;
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 : OUT STD_LOGIC;
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 : OUT STD_LOGIC;
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 : OUT STD_LOGIC;
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component vgg_accelerator_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_conv1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        s_conv1_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        s_conv1_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        s_conv1_full_n : IN STD_LOGIC;
        s_conv1_write : OUT STD_LOGIC;
        s_input_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        s_input_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        s_input_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        s_input_empty_n : IN STD_LOGIC;
        s_input_read : OUT STD_LOGIC;
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 : OUT STD_LOGIC;
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 : OUT STD_LOGIC;
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 : OUT STD_LOGIC;
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 : OUT STD_LOGIC;
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component vgg_accelerator_layer_block_1_16_32_s_void_layer_block_stream_stream_signed_char_const_1_3_3_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_U : component vgg_accelerator_layer_block_1_16_32_s_void_layer_block_stream_stream_signed_char_const_1_3_3_bkb
    generic map (
        DataWidth => 8,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0,
        ce0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0,
        we0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0,
        d0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0,
        q0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_q0);

    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_U : component vgg_accelerator_layer_block_1_16_32_s_void_layer_block_stream_stream_signed_char_const_1_3_3_bkb
    generic map (
        DataWidth => 8,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0,
        ce0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0,
        we0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0,
        d0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0,
        q0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_q0);

    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24 : component vgg_accelerator_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start,
        ap_done => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_done,
        ap_idle => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_idle,
        ap_ready => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_ready,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0);

    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32 : component vgg_accelerator_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start,
        ap_done => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done,
        ap_idle => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_idle,
        ap_ready => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_ready,
        s_conv1_din => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_din,
        s_conv1_num_data_valid => ap_const_lv8_0,
        s_conv1_fifo_cap => ap_const_lv8_0,
        s_conv1_full_n => s_conv1_full_n,
        s_conv1_write => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_write,
        s_input_dout => s_input_dout,
        s_input_num_data_valid => ap_const_lv8_0,
        s_input_fifo_cap => ap_const_lv8_0,
        s_input_empty_n => s_input_empty_n,
        s_input_read => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_input_read,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_q0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_q0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 => grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0,
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_q0 => void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_ready = ap_const_logic_1)) then 
                    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_ready = ap_const_logic_1)) then 
                    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_done, grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_done)
    begin
        if ((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done)
    begin
        if ((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call8_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call8 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg;
    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg;

    internal_ap_ready_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    s_conv1_din <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_din;

    s_conv1_write_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            s_conv1_write <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_write;
        else 
            s_conv1_write <= ap_const_logic_0;
        end if; 
    end process;


    s_input_read_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_input_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            s_input_read <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_input_read;
        else 
            s_input_read <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0, grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0;
        else 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 <= "XXXXX";
        end if; 
    end process;


    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0, grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0;
        else 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0, grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0;
        else 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 <= "XXXXXXXX";
        end if; 
    end process;


    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0, grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0;
        else 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0, grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0;
        else 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 <= "XXXXX";
        end if; 
    end process;


    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0, grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0;
        else 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0, grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0;
        else 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 <= "XXXXXXXX";
        end if; 
    end process;


    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0_assign_proc : process(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0, grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 <= grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0;
        else 
            void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
