-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vgg_accelerator_dense_layer is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
    OUTPUT_STREAM_TREADY : IN STD_LOGIC;
    OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_pool3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    s_pool3_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    s_pool3_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    s_pool3_empty_n : IN STD_LOGIC;
    s_pool3_read : OUT STD_LOGIC );
end;


architecture behav of vgg_accelerator_dense_layer is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal dense_bias_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal dense_bias_ce0 : STD_LOGIC;
    signal dense_bias_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal c_1_reg_179 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln140_fu_123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_V_41_fu_145_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal acc_V_41_reg_193 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal shl_ln_fu_157_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_reg_198 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln161_fu_166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln161_reg_203 : STD_LOGIC_VECTOR (0 downto 0);
    signal flat_img_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal flat_img_V_ce0 : STD_LOGIC;
    signal flat_img_V_we0 : STD_LOGIC;
    signal flat_img_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_done : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_idle : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_ready : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_s_pool3_read : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_ce0 : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_we0 : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_done : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_idle : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_ready : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TREADY : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_ce0 : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID : STD_LOGIC;
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call9 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln140_fu_135_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_68 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln140_fu_129_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln152_fu_154_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal OUTPUT_STREAM_TVALID_int_regslice : STD_LOGIC;
    signal OUTPUT_STREAM_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_OUTPUT_STREAM_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_135_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_pool3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        s_pool3_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_pool3_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_pool3_empty_n : IN STD_LOGIC;
        s_pool3_read : OUT STD_LOGIC;
        flat_img_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        flat_img_V_ce0 : OUT STD_LOGIC;
        flat_img_V_we0 : OUT STD_LOGIC;
        flat_img_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_146_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        OUTPUT_STREAM_TREADY : IN STD_LOGIC;
        sext_ln141 : IN STD_LOGIC_VECTOR (13 downto 0);
        shl_ln : IN STD_LOGIC_VECTOR (10 downto 0);
        flat_img_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        flat_img_V_ce0 : OUT STD_LOGIC;
        flat_img_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        output_packet_last_V : IN STD_LOGIC_VECTOR (0 downto 0);
        OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
        OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component vgg_accelerator_dense_layer_dense_bias_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component vgg_accelerator_dense_layer_flat_img_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component vgg_accelerator_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    dense_bias_U : component vgg_accelerator_dense_layer_dense_bias_ROM_AUTO_1R
    generic map (
        DataWidth => 2,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dense_bias_address0,
        ce0 => dense_bias_ce0,
        q0 => dense_bias_q0);

    flat_img_V_U : component vgg_accelerator_dense_layer_flat_img_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => flat_img_V_address0,
        ce0 => flat_img_V_ce0,
        we0 => flat_img_V_we0,
        d0 => grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_d0,
        q0 => flat_img_V_q0);

    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89 : component vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_135_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start,
        ap_done => grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_done,
        ap_idle => grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_idle,
        ap_ready => grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_ready,
        s_pool3_dout => s_pool3_dout,
        s_pool3_num_data_valid => ap_const_lv7_0,
        s_pool3_fifo_cap => ap_const_lv7_0,
        s_pool3_empty_n => s_pool3_empty_n,
        s_pool3_read => grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_s_pool3_read,
        flat_img_V_address0 => grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_address0,
        flat_img_V_ce0 => grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_ce0,
        flat_img_V_we0 => grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_we0,
        flat_img_V_d0 => grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_d0);

    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97 : component vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_146_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start,
        ap_done => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_done,
        ap_idle => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_idle,
        ap_ready => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_ready,
        OUTPUT_STREAM_TREADY => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TREADY,
        sext_ln141 => acc_V_41_reg_193,
        shl_ln => shl_ln_reg_198,
        flat_img_V_address0 => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_address0,
        flat_img_V_ce0 => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_ce0,
        flat_img_V_q0 => flat_img_V_q0,
        output_packet_last_V => icmp_ln161_reg_203,
        OUTPUT_STREAM_TDATA => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TKEEP => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TLAST => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TLAST);

    regslice_both_OUTPUT_STREAM_V_data_V_U : component vgg_accelerator_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TDATA,
        vld_in => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID,
        ack_in => OUTPUT_STREAM_TREADY_int_regslice,
        data_out => OUTPUT_STREAM_TDATA,
        vld_out => regslice_both_OUTPUT_STREAM_V_data_V_U_vld_out,
        ack_out => OUTPUT_STREAM_TREADY,
        apdone_blk => regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk);

    regslice_both_OUTPUT_STREAM_V_keep_V_U : component vgg_accelerator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TKEEP,
        vld_in => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID,
        ack_in => regslice_both_OUTPUT_STREAM_V_keep_V_U_ack_in_dummy,
        data_out => OUTPUT_STREAM_TKEEP,
        vld_out => regslice_both_OUTPUT_STREAM_V_keep_V_U_vld_out,
        ack_out => OUTPUT_STREAM_TREADY,
        apdone_blk => regslice_both_OUTPUT_STREAM_V_keep_V_U_apdone_blk);

    regslice_both_OUTPUT_STREAM_V_strb_V_U : component vgg_accelerator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TSTRB,
        vld_in => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID,
        ack_in => regslice_both_OUTPUT_STREAM_V_strb_V_U_ack_in_dummy,
        data_out => OUTPUT_STREAM_TSTRB,
        vld_out => regslice_both_OUTPUT_STREAM_V_strb_V_U_vld_out,
        ack_out => OUTPUT_STREAM_TREADY,
        apdone_blk => regslice_both_OUTPUT_STREAM_V_strb_V_U_apdone_blk);

    regslice_both_OUTPUT_STREAM_V_last_V_U : component vgg_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TLAST,
        vld_in => grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID,
        ack_in => regslice_both_OUTPUT_STREAM_V_last_V_U_ack_in_dummy,
        data_out => OUTPUT_STREAM_TLAST,
        vld_out => regslice_both_OUTPUT_STREAM_V_last_V_U_vld_out,
        ack_out => OUTPUT_STREAM_TREADY,
        apdone_blk => regslice_both_OUTPUT_STREAM_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_ready = ap_const_logic_1)) then 
                    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_ready = ap_const_logic_1)) then 
                    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                c_fu_68 <= ap_const_lv2_0;
            elsif (((icmp_ln140_fu_123_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                c_fu_68 <= add_ln140_fu_129_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    acc_V_41_reg_193(13 downto 12) <= acc_V_41_fu_145_p3(13 downto 12);
                icmp_ln161_reg_203 <= icmp_ln161_fu_166_p2;
                    shl_ln_reg_198(10) <= shl_ln_fu_157_p3(10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                c_1_reg_179 <= c_fu_68;
            end if;
        end if;
    end process;
    acc_V_41_reg_193(11 downto 0) <= "000000000000";
    shl_ln_reg_198(9 downto 0) <= "0000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, icmp_ln140_fu_123_p2, grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_done, grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state7, regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln140_fu_123_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    OUTPUT_STREAM_TVALID <= regslice_both_OUTPUT_STREAM_V_data_V_U_vld_out;
    OUTPUT_STREAM_TVALID_int_regslice <= grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID;
    acc_V_41_fu_145_p3 <= (dense_bias_q0 & ap_const_lv12_0);
    add_ln140_fu_129_p2 <= std_logic_vector(unsigned(c_fu_68) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_done)
    begin
        if ((grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_done)
    begin
        if ((grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state7_blk_assign_proc : process(regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call9_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call9 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state7, regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7, regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    dense_bias_address0 <= zext_ln140_fu_135_p1(1 - 1 downto 0);

    dense_bias_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dense_bias_ce0 <= ap_const_logic_1;
        else 
            dense_bias_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    flat_img_V_address0_assign_proc : process(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_address0, grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_address0, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            flat_img_V_address0 <= grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            flat_img_V_address0 <= grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_address0;
        else 
            flat_img_V_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    flat_img_V_ce0_assign_proc : process(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_ce0, grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_ce0, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            flat_img_V_ce0 <= grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            flat_img_V_ce0 <= grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_ce0;
        else 
            flat_img_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    flat_img_V_we0_assign_proc : process(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            flat_img_V_we0 <= grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_we0;
        else 
            flat_img_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start <= grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg;
    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TREADY <= (ap_CS_fsm_state6 and OUTPUT_STREAM_TREADY_int_regslice);
    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start <= grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg;
    icmp_ln140_fu_123_p2 <= "1" when (c_fu_68 = ap_const_lv2_2) else "0";
    icmp_ln161_fu_166_p2 <= "1" when (c_1_reg_179 = ap_const_lv2_1) else "0";

    s_pool3_read_assign_proc : process(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_s_pool3_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            s_pool3_read <= grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_s_pool3_read;
        else 
            s_pool3_read <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln_fu_157_p3 <= (trunc_ln152_fu_154_p1 & ap_const_lv10_0);
    trunc_ln152_fu_154_p1 <= c_1_reg_179(1 - 1 downto 0);
    zext_ln140_fu_135_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_68),64));
end behav;
