-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vgg_accelerator_layer_block_16_32_16_Pipeline_VITIS_LOOP_71_8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln66 : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln71_2 : IN STD_LOGIC_VECTOR (8 downto 0);
    zext_ln76 : IN STD_LOGIC_VECTOR (11 downto 0);
    window_V_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_522_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_531_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_540_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_549_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_558_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_567_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_576_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_585_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_594_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_603_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_612_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_621_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_630_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_639_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_648_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_514_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_523_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_532_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_541_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_550_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_559_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_568_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_577_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_586_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_595_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_604_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_613_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_622_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_631_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_640_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_649_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_234_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_241_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_248_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_255_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_262_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_269_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_276_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_283_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_290_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_297_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_304_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_311_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_318_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_325_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_332_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_226_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_516_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_525_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_534_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_543_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_552_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_561_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_570_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_579_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_588_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_597_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_606_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_615_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_624_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_633_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_642_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_651_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_235_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_242_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_249_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_256_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_263_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_270_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_277_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_284_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_291_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_298_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_305_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_312_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_319_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_326_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_333_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_227_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_236_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_243_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_250_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_257_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_264_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_271_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_278_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_285_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_292_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_299_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_306_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_313_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_320_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_327_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_334_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_228_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_519_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_528_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_537_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_546_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_555_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_564_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_573_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_582_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_591_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_600_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_609_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_618_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_627_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_636_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_645_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_654_2_i_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_237_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_244_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_251_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_258_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_265_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_272_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_279_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_286_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_293_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_300_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_307_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_314_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_321_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_328_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_335_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_229_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_238_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_245_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_252_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_259_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_266_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_273_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_280_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_287_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_294_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_301_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_308_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_315_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_322_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_329_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_336_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    window_V_230_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    s_conv2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    s_conv2_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    s_conv2_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    s_conv2_full_n : IN STD_LOGIC;
    s_conv2_write : OUT STD_LOGIC );
end;


architecture behav of vgg_accelerator_layer_block_16_32_16_Pipeline_VITIS_LOOP_71_8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv13_2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_const_lv13_3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000011";
    constant ap_const_lv13_4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_const_lv13_5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000101";
    constant ap_const_lv13_6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000110";
    constant ap_const_lv13_7 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000111";
    constant ap_const_lv13_8 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_7FFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "01111111111111111111111111111111";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln71_reg_2929 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal conv2_weights_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal conv2_weights_ce0 : STD_LOGIC;
    signal conv2_weights_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_weights_address1 : STD_LOGIC_VECTOR (12 downto 0);
    signal conv2_weights_ce1 : STD_LOGIC;
    signal conv2_weights_q1 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_weights_address2 : STD_LOGIC_VECTOR (12 downto 0);
    signal conv2_weights_ce2 : STD_LOGIC;
    signal conv2_weights_q2 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_weights_address3 : STD_LOGIC_VECTOR (12 downto 0);
    signal conv2_weights_ce3 : STD_LOGIC;
    signal conv2_weights_q3 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_weights_address4 : STD_LOGIC_VECTOR (12 downto 0);
    signal conv2_weights_ce4 : STD_LOGIC;
    signal conv2_weights_q4 : STD_LOGIC_VECTOR (4 downto 0);
    signal s_conv2_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln71_2_reg_3011 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln71_2_reg_3011_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln71_fu_1425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln76_12_fu_1477_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln76_12_reg_2933 : STD_LOGIC_VECTOR (12 downto 0);
    signal px_V_fu_1488_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_reg_2946 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_9_fu_1537_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_9_reg_2956 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_10_fu_1586_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_10_reg_2966 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_11_fu_1635_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_11_reg_2976 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_12_fu_1684_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_12_reg_2986 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_13_fu_1722_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_13_reg_2991 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_14_fu_1760_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_14_reg_2996 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_15_fu_1798_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_15_reg_3001 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_16_fu_1836_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal px_V_16_reg_3006 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln71_2_fu_1874_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln1347_fu_1892_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_reg_3015 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal mul_ln1347_9_fu_1905_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_9_reg_3020 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_10_fu_1918_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_10_reg_3025 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_11_fu_1931_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_11_reg_3030 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_12_fu_1944_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_12_reg_3035 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_26_reg_3060 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_V_29_fu_2350_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_29_reg_3066 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_27_reg_3071 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln1347_13_fu_2371_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_13_reg_3077 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_14_fu_2384_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_14_reg_3082 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_15_fu_2397_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_15_reg_3087 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_16_fu_2410_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_16_reg_3092 : STD_LOGIC_VECTOR (11 downto 0);
    signal acc_V_fu_2761_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_reg_3097 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln76_16_fu_1483_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln76_17_fu_1532_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln76_18_fu_1581_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln76_19_fu_1630_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln76_20_fu_1679_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln76_21_fu_1955_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln76_22_fu_1965_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln76_23_fu_1975_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln76_24_fu_1985_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_fu_410 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln66_cast_fu_1408_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ch_2_fu_414 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln71_fu_1431_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_ch : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln76_fu_1441_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln76_4_fu_1445_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln76_13_fu_1453_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln71_fu_1437_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln76_fu_1457_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln71_2_cast_fu_1404_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln76_14_fu_1463_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln76_11_fu_1467_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln76_15_fu_1473_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln76_cast_fu_1400_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln76_13_fu_1526_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln76_14_fu_1575_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln76_15_fu_1624_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln76_16_fu_1673_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln76_17_fu_1950_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln76_18_fu_1960_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln76_19_fu_1970_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln76_20_fu_1980_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln813_fu_1993_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_fu_1997_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln813_fu_1993_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_fu_2004_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_fu_2012_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal acc_V_21_fu_2026_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1347_18_fu_2008_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_21_fu_2026_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_fu_2018_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_19_fu_2032_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_10_fu_2040_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_10_fu_2046_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln302_fu_2052_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_fu_2058_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_22_fu_2066_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_9_fu_2078_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln813_9_fu_2074_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_19_fu_2085_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_9_fu_2093_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_20_fu_2089_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_23_fu_2107_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_20_fu_2099_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_21_fu_2113_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_11_fu_2121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_11_fu_2127_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln302_9_fu_2133_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_9_fu_2139_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_24_fu_2147_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_10_fu_2159_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln813_10_fu_2155_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_21_fu_2166_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_10_fu_2174_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_22_fu_2170_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_25_fu_2188_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_22_fu_2180_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_23_fu_2194_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_12_fu_2202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_12_fu_2208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln302_10_fu_2214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_10_fu_2220_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_26_fu_2228_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_11_fu_2240_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln813_11_fu_2236_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_23_fu_2247_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_11_fu_2255_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_24_fu_2251_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_27_fu_2269_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_24_fu_2261_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_25_fu_2275_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_13_fu_2283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_13_fu_2289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln302_11_fu_2295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_11_fu_2301_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_28_fu_2309_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_12_fu_2321_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln813_12_fu_2317_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_25_fu_2328_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_12_fu_2336_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_26_fu_2332_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln895_14_fu_2416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_14_fu_2421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln302_12_fu_2426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_12_fu_2430_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_30_fu_2438_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_13_fu_2449_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln813_13_fu_2445_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_27_fu_2456_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_13_fu_2464_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_28_fu_2460_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_31_fu_2478_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_28_fu_2470_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_29_fu_2484_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_15_fu_2492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_15_fu_2498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln302_13_fu_2504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_13_fu_2510_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_32_fu_2518_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_14_fu_2530_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln813_14_fu_2526_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_29_fu_2537_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_14_fu_2545_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_30_fu_2541_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_33_fu_2559_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_30_fu_2551_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_fu_2565_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_16_fu_2573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_16_fu_2579_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln302_14_fu_2585_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_14_fu_2591_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_34_fu_2599_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_15_fu_2611_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln813_15_fu_2607_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_31_fu_2618_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_15_fu_2626_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_32_fu_2622_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_35_fu_2640_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_32_fu_2632_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_33_fu_2646_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_17_fu_2654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_17_fu_2660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln302_15_fu_2666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_15_fu_2672_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_36_fu_2680_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_16_fu_2692_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln813_16_fu_2688_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_33_fu_2699_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_16_fu_2707_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_34_fu_2703_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_37_fu_2721_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_34_fu_2713_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_35_fu_2727_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_18_fu_2735_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_18_fu_2741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln302_16_fu_2747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_16_fu_2753_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_2777_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln71_fu_2774_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal acc_V_38_fu_2784_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_5_fu_2802_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_39_fu_2792_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln377_fu_2810_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln377_3_fu_2814_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln377_2_fu_2824_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Val2_40_fu_2828_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_2848_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_fu_2864_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_36_fu_2840_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln888_fu_2872_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_2858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln888_fu_2878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_2884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_fu_2890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_2896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln856_fu_2834_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln302_fu_2902_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vgg_accelerator_mux_164_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        din11 : IN STD_LOGIC_VECTOR (7 downto 0);
        din12 : IN STD_LOGIC_VECTOR (7 downto 0);
        din13 : IN STD_LOGIC_VECTOR (7 downto 0);
        din14 : IN STD_LOGIC_VECTOR (7 downto 0);
        din15 : IN STD_LOGIC_VECTOR (7 downto 0);
        din16 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component vgg_accelerator_mul_8s_5s_12_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component vgg_accelerator_layer_block_16_32_16_Pipeline_VITIS_LOOP_71_8_conv2_weights_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        address1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        address2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (4 downto 0);
        address3 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (4 downto 0);
        address4 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component vgg_accelerator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    conv2_weights_U : component vgg_accelerator_layer_block_16_32_16_Pipeline_VITIS_LOOP_71_8_conv2_weights_ROM_AUTO_1R
    generic map (
        DataWidth => 5,
        AddressRange => 4608,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => conv2_weights_address0,
        ce0 => conv2_weights_ce0,
        q0 => conv2_weights_q0,
        address1 => conv2_weights_address1,
        ce1 => conv2_weights_ce1,
        q1 => conv2_weights_q1,
        address2 => conv2_weights_address2,
        ce2 => conv2_weights_ce2,
        q2 => conv2_weights_q2,
        address3 => conv2_weights_address3,
        ce3 => conv2_weights_ce3,
        q3 => conv2_weights_q3,
        address4 => conv2_weights_address4,
        ce4 => conv2_weights_ce4,
        q4 => conv2_weights_q4);

    mux_164_8_1_1_U318 : component vgg_accelerator_mux_164_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => window_V_2_i_reload,
        din1 => window_V_522_2_i_reload,
        din2 => window_V_531_2_i_reload,
        din3 => window_V_540_2_i_reload,
        din4 => window_V_549_2_i_reload,
        din5 => window_V_558_2_i_reload,
        din6 => window_V_567_2_i_reload,
        din7 => window_V_576_2_i_reload,
        din8 => window_V_585_2_i_reload,
        din9 => window_V_594_2_i_reload,
        din10 => window_V_603_2_i_reload,
        din11 => window_V_612_2_i_reload,
        din12 => window_V_621_2_i_reload,
        din13 => window_V_630_2_i_reload,
        din14 => window_V_639_2_i_reload,
        din15 => window_V_648_2_i_reload,
        din16 => trunc_ln76_fu_1441_p1,
        dout => px_V_fu_1488_p18);

    mux_164_8_1_1_U319 : component vgg_accelerator_mux_164_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => window_V_514_2_i_reload,
        din1 => window_V_523_2_i_reload,
        din2 => window_V_532_2_i_reload,
        din3 => window_V_541_2_i_reload,
        din4 => window_V_550_2_i_reload,
        din5 => window_V_559_2_i_reload,
        din6 => window_V_568_2_i_reload,
        din7 => window_V_577_2_i_reload,
        din8 => window_V_586_2_i_reload,
        din9 => window_V_595_2_i_reload,
        din10 => window_V_604_2_i_reload,
        din11 => window_V_613_2_i_reload,
        din12 => window_V_622_2_i_reload,
        din13 => window_V_631_2_i_reload,
        din14 => window_V_640_2_i_reload,
        din15 => window_V_649_2_i_reload,
        din16 => trunc_ln76_fu_1441_p1,
        dout => px_V_9_fu_1537_p18);

    mux_164_8_1_1_U320 : component vgg_accelerator_mux_164_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => window_V_234_reload,
        din1 => window_V_241_reload,
        din2 => window_V_248_reload,
        din3 => window_V_255_reload,
        din4 => window_V_262_reload,
        din5 => window_V_269_reload,
        din6 => window_V_276_reload,
        din7 => window_V_283_reload,
        din8 => window_V_290_reload,
        din9 => window_V_297_reload,
        din10 => window_V_304_reload,
        din11 => window_V_311_reload,
        din12 => window_V_318_reload,
        din13 => window_V_325_reload,
        din14 => window_V_332_reload,
        din15 => window_V_226_reload,
        din16 => trunc_ln76_fu_1441_p1,
        dout => px_V_10_fu_1586_p18);

    mux_164_8_1_1_U321 : component vgg_accelerator_mux_164_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => window_V_516_2_i_reload,
        din1 => window_V_525_2_i_reload,
        din2 => window_V_534_2_i_reload,
        din3 => window_V_543_2_i_reload,
        din4 => window_V_552_2_i_reload,
        din5 => window_V_561_2_i_reload,
        din6 => window_V_570_2_i_reload,
        din7 => window_V_579_2_i_reload,
        din8 => window_V_588_2_i_reload,
        din9 => window_V_597_2_i_reload,
        din10 => window_V_606_2_i_reload,
        din11 => window_V_615_2_i_reload,
        din12 => window_V_624_2_i_reload,
        din13 => window_V_633_2_i_reload,
        din14 => window_V_642_2_i_reload,
        din15 => window_V_651_2_i_reload,
        din16 => trunc_ln76_fu_1441_p1,
        dout => px_V_11_fu_1635_p18);

    mux_164_8_1_1_U322 : component vgg_accelerator_mux_164_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => window_V_235_reload,
        din1 => window_V_242_reload,
        din2 => window_V_249_reload,
        din3 => window_V_256_reload,
        din4 => window_V_263_reload,
        din5 => window_V_270_reload,
        din6 => window_V_277_reload,
        din7 => window_V_284_reload,
        din8 => window_V_291_reload,
        din9 => window_V_298_reload,
        din10 => window_V_305_reload,
        din11 => window_V_312_reload,
        din12 => window_V_319_reload,
        din13 => window_V_326_reload,
        din14 => window_V_333_reload,
        din15 => window_V_227_reload,
        din16 => trunc_ln76_fu_1441_p1,
        dout => px_V_12_fu_1684_p18);

    mux_164_8_1_1_U323 : component vgg_accelerator_mux_164_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => window_V_236_reload,
        din1 => window_V_243_reload,
        din2 => window_V_250_reload,
        din3 => window_V_257_reload,
        din4 => window_V_264_reload,
        din5 => window_V_271_reload,
        din6 => window_V_278_reload,
        din7 => window_V_285_reload,
        din8 => window_V_292_reload,
        din9 => window_V_299_reload,
        din10 => window_V_306_reload,
        din11 => window_V_313_reload,
        din12 => window_V_320_reload,
        din13 => window_V_327_reload,
        din14 => window_V_334_reload,
        din15 => window_V_228_reload,
        din16 => trunc_ln76_fu_1441_p1,
        dout => px_V_13_fu_1722_p18);

    mux_164_8_1_1_U324 : component vgg_accelerator_mux_164_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => window_V_519_2_i_reload,
        din1 => window_V_528_2_i_reload,
        din2 => window_V_537_2_i_reload,
        din3 => window_V_546_2_i_reload,
        din4 => window_V_555_2_i_reload,
        din5 => window_V_564_2_i_reload,
        din6 => window_V_573_2_i_reload,
        din7 => window_V_582_2_i_reload,
        din8 => window_V_591_2_i_reload,
        din9 => window_V_600_2_i_reload,
        din10 => window_V_609_2_i_reload,
        din11 => window_V_618_2_i_reload,
        din12 => window_V_627_2_i_reload,
        din13 => window_V_636_2_i_reload,
        din14 => window_V_645_2_i_reload,
        din15 => window_V_654_2_i_reload,
        din16 => trunc_ln76_fu_1441_p1,
        dout => px_V_14_fu_1760_p18);

    mux_164_8_1_1_U325 : component vgg_accelerator_mux_164_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => window_V_237_reload,
        din1 => window_V_244_reload,
        din2 => window_V_251_reload,
        din3 => window_V_258_reload,
        din4 => window_V_265_reload,
        din5 => window_V_272_reload,
        din6 => window_V_279_reload,
        din7 => window_V_286_reload,
        din8 => window_V_293_reload,
        din9 => window_V_300_reload,
        din10 => window_V_307_reload,
        din11 => window_V_314_reload,
        din12 => window_V_321_reload,
        din13 => window_V_328_reload,
        din14 => window_V_335_reload,
        din15 => window_V_229_reload,
        din16 => trunc_ln76_fu_1441_p1,
        dout => px_V_15_fu_1798_p18);

    mux_164_8_1_1_U326 : component vgg_accelerator_mux_164_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => window_V_238_reload,
        din1 => window_V_245_reload,
        din2 => window_V_252_reload,
        din3 => window_V_259_reload,
        din4 => window_V_266_reload,
        din5 => window_V_273_reload,
        din6 => window_V_280_reload,
        din7 => window_V_287_reload,
        din8 => window_V_294_reload,
        din9 => window_V_301_reload,
        din10 => window_V_308_reload,
        din11 => window_V_315_reload,
        din12 => window_V_322_reload,
        din13 => window_V_329_reload,
        din14 => window_V_336_reload,
        din15 => window_V_230_reload,
        din16 => trunc_ln76_fu_1441_p1,
        dout => px_V_16_fu_1836_p18);

    mul_8s_5s_12_1_1_U327 : component vgg_accelerator_mul_8s_5s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        din0 => px_V_reg_2946,
        din1 => conv2_weights_q4,
        dout => mul_ln1347_fu_1892_p2);

    mul_8s_5s_12_1_1_U328 : component vgg_accelerator_mul_8s_5s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        din0 => px_V_9_reg_2956,
        din1 => conv2_weights_q3,
        dout => mul_ln1347_9_fu_1905_p2);

    mul_8s_5s_12_1_1_U329 : component vgg_accelerator_mul_8s_5s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        din0 => px_V_10_reg_2966,
        din1 => conv2_weights_q2,
        dout => mul_ln1347_10_fu_1918_p2);

    mul_8s_5s_12_1_1_U330 : component vgg_accelerator_mul_8s_5s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        din0 => px_V_11_reg_2976,
        din1 => conv2_weights_q1,
        dout => mul_ln1347_11_fu_1931_p2);

    mul_8s_5s_12_1_1_U331 : component vgg_accelerator_mul_8s_5s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        din0 => px_V_12_reg_2986,
        din1 => conv2_weights_q0,
        dout => mul_ln1347_12_fu_1944_p2);

    mul_8s_5s_12_1_1_U332 : component vgg_accelerator_mul_8s_5s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        din0 => px_V_13_reg_2991,
        din1 => conv2_weights_q3,
        dout => mul_ln1347_13_fu_2371_p2);

    mul_8s_5s_12_1_1_U333 : component vgg_accelerator_mul_8s_5s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        din0 => px_V_14_reg_2996,
        din1 => conv2_weights_q2,
        dout => mul_ln1347_14_fu_2384_p2);

    mul_8s_5s_12_1_1_U334 : component vgg_accelerator_mul_8s_5s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        din0 => px_V_15_reg_3001,
        din1 => conv2_weights_q1,
        dout => mul_ln1347_15_fu_2397_p2);

    mul_8s_5s_12_1_1_U335 : component vgg_accelerator_mul_8s_5s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        din0 => px_V_16_reg_3006,
        din1 => conv2_weights_q0,
        dout => mul_ln1347_16_fu_2410_p2);

    flow_control_loop_pipe_sequential_init_U : component vgg_accelerator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ch_2_fu_414_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln71_fu_1425_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    ch_2_fu_414 <= add_ln71_fu_1431_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ch_2_fu_414 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_fu_410_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                lhs_fu_410 <= sext_ln66_cast_fu_1408_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                lhs_fu_410 <= acc_V_fu_2761_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                acc_V_29_reg_3066 <= acc_V_29_fu_2350_p2;
                icmp_ln71_2_reg_3011_pp0_iter1_reg <= icmp_ln71_2_reg_3011;
                icmp_ln71_reg_2929 <= icmp_ln71_fu_1425_p2;
                mul_ln1347_13_reg_3077 <= mul_ln1347_13_fu_2371_p2;
                mul_ln1347_14_reg_3082 <= mul_ln1347_14_fu_2384_p2;
                mul_ln1347_15_reg_3087 <= mul_ln1347_15_fu_2397_p2;
                mul_ln1347_16_reg_3092 <= mul_ln1347_16_fu_2410_p2;
                p_Result_26_reg_3060 <= ret_V_12_fu_2336_p2(32 downto 32);
                p_Result_27_reg_3071 <= acc_V_29_fu_2350_p2(31 downto 31);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                acc_V_reg_3097 <= acc_V_fu_2761_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln71_fu_1425_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln76_12_reg_2933 <= add_ln76_12_fu_1477_p2;
                icmp_ln71_2_reg_3011 <= icmp_ln71_2_fu_1874_p2;
                px_V_10_reg_2966 <= px_V_10_fu_1586_p18;
                px_V_11_reg_2976 <= px_V_11_fu_1635_p18;
                px_V_12_reg_2986 <= px_V_12_fu_1684_p18;
                px_V_13_reg_2991 <= px_V_13_fu_1722_p18;
                px_V_14_reg_2996 <= px_V_14_fu_1760_p18;
                px_V_15_reg_3001 <= px_V_15_fu_1798_p18;
                px_V_16_reg_3006 <= px_V_16_fu_1836_p18;
                px_V_9_reg_2956 <= px_V_9_fu_1537_p18;
                px_V_reg_2946 <= px_V_fu_1488_p18;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_reg_2929 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                mul_ln1347_10_reg_3025 <= mul_ln1347_10_fu_1918_p2;
                mul_ln1347_11_reg_3030 <= mul_ln1347_11_fu_1931_p2;
                mul_ln1347_12_reg_3035 <= mul_ln1347_12_fu_1944_p2;
                mul_ln1347_9_reg_3020 <= mul_ln1347_9_fu_1905_p2;
                mul_ln1347_reg_3015 <= mul_ln1347_fu_1892_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter1_stage0, ap_idle_pp0_0to0, ap_idle_pp0_1to2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    Range1_all_zeros_fu_2858_p2 <= "1" when (tmp_2_fu_2848_p4 = ap_const_lv11_0) else "0";
    acc_V_21_fu_2026_p0 <= lhs_fu_410;
    acc_V_21_fu_2026_p2 <= std_logic_vector(signed(acc_V_21_fu_2026_p0) + signed(sext_ln1347_18_fu_2008_p1));
    acc_V_22_fu_2066_p3 <= 
        select_ln346_fu_2058_p3 when (xor_ln302_fu_2052_p2(0) = '1') else 
        acc_V_21_fu_2026_p2;
    acc_V_23_fu_2107_p2 <= std_logic_vector(signed(acc_V_22_fu_2066_p3) + signed(sext_ln1347_20_fu_2089_p1));
    acc_V_24_fu_2147_p3 <= 
        select_ln346_9_fu_2139_p3 when (xor_ln302_9_fu_2133_p2(0) = '1') else 
        acc_V_23_fu_2107_p2;
    acc_V_25_fu_2188_p2 <= std_logic_vector(signed(acc_V_24_fu_2147_p3) + signed(sext_ln1347_22_fu_2170_p1));
    acc_V_26_fu_2228_p3 <= 
        select_ln346_10_fu_2220_p3 when (xor_ln302_10_fu_2214_p2(0) = '1') else 
        acc_V_25_fu_2188_p2;
    acc_V_27_fu_2269_p2 <= std_logic_vector(signed(acc_V_26_fu_2228_p3) + signed(sext_ln1347_24_fu_2251_p1));
    acc_V_28_fu_2309_p3 <= 
        select_ln346_11_fu_2301_p3 when (xor_ln302_11_fu_2295_p2(0) = '1') else 
        acc_V_27_fu_2269_p2;
    acc_V_29_fu_2350_p2 <= std_logic_vector(signed(acc_V_28_fu_2309_p3) + signed(sext_ln1347_26_fu_2332_p1));
    acc_V_30_fu_2438_p3 <= 
        select_ln346_12_fu_2430_p3 when (xor_ln302_12_fu_2426_p2(0) = '1') else 
        acc_V_29_reg_3066;
    acc_V_31_fu_2478_p2 <= std_logic_vector(signed(acc_V_30_fu_2438_p3) + signed(sext_ln1347_28_fu_2460_p1));
    acc_V_32_fu_2518_p3 <= 
        select_ln346_13_fu_2510_p3 when (xor_ln302_13_fu_2504_p2(0) = '1') else 
        acc_V_31_fu_2478_p2;
    acc_V_33_fu_2559_p2 <= std_logic_vector(signed(acc_V_32_fu_2518_p3) + signed(sext_ln1347_30_fu_2541_p1));
    acc_V_34_fu_2599_p3 <= 
        select_ln346_14_fu_2591_p3 when (xor_ln302_14_fu_2585_p2(0) = '1') else 
        acc_V_33_fu_2559_p2;
    acc_V_35_fu_2640_p2 <= std_logic_vector(signed(acc_V_34_fu_2599_p3) + signed(sext_ln1347_32_fu_2622_p1));
    acc_V_36_fu_2680_p3 <= 
        select_ln346_15_fu_2672_p3 when (xor_ln302_15_fu_2666_p2(0) = '1') else 
        acc_V_35_fu_2640_p2;
    acc_V_37_fu_2721_p2 <= std_logic_vector(signed(acc_V_36_fu_2680_p3) + signed(sext_ln1347_34_fu_2703_p1));
    acc_V_38_fu_2784_p3 <= 
        ap_const_lv31_0 when (tmp_fu_2777_p3(0) = '1') else 
        trunc_ln71_fu_2774_p1;
    acc_V_fu_2761_p3 <= 
        select_ln346_16_fu_2753_p3 when (xor_ln302_16_fu_2747_p2(0) = '1') else 
        acc_V_37_fu_2721_p2;
    add_ln71_fu_1431_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ch) + unsigned(ap_const_lv5_1));
    add_ln76_11_fu_1467_p2 <= std_logic_vector(unsigned(zext_ln71_2_cast_fu_1404_p1) + unsigned(zext_ln76_14_fu_1463_p1));
    add_ln76_12_fu_1477_p2 <= std_logic_vector(unsigned(zext_ln76_15_fu_1473_p1) + unsigned(zext_ln76_cast_fu_1400_p1));
    add_ln76_13_fu_1526_p2 <= std_logic_vector(unsigned(add_ln76_12_fu_1477_p2) + unsigned(ap_const_lv13_1));
    add_ln76_14_fu_1575_p2 <= std_logic_vector(unsigned(add_ln76_12_fu_1477_p2) + unsigned(ap_const_lv13_2));
    add_ln76_15_fu_1624_p2 <= std_logic_vector(unsigned(add_ln76_12_fu_1477_p2) + unsigned(ap_const_lv13_3));
    add_ln76_16_fu_1673_p2 <= std_logic_vector(unsigned(add_ln76_12_fu_1477_p2) + unsigned(ap_const_lv13_4));
    add_ln76_17_fu_1950_p2 <= std_logic_vector(unsigned(add_ln76_12_reg_2933) + unsigned(ap_const_lv13_5));
    add_ln76_18_fu_1960_p2 <= std_logic_vector(unsigned(add_ln76_12_reg_2933) + unsigned(ap_const_lv13_6));
    add_ln76_19_fu_1970_p2 <= std_logic_vector(unsigned(add_ln76_12_reg_2933) + unsigned(ap_const_lv13_7));
    add_ln76_20_fu_1980_p2 <= std_logic_vector(unsigned(add_ln76_12_reg_2933) + unsigned(ap_const_lv13_8));
    add_ln76_fu_1457_p2 <= std_logic_vector(unsigned(zext_ln76_13_fu_1453_p1) + unsigned(zext_ln71_fu_1437_p1));
    add_ln856_fu_2834_p2 <= std_logic_vector(unsigned(trunc_ln377_3_fu_2814_p4) + unsigned(zext_ln377_2_fu_2824_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, s_conv2_full_n, icmp_ln71_2_reg_3011_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln71_2_reg_3011_pp0_iter1_reg = ap_const_lv1_1) and (s_conv2_full_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, s_conv2_full_n, icmp_ln71_2_reg_3011_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln71_2_reg_3011_pp0_iter1_reg = ap_const_lv1_1) and (s_conv2_full_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, s_conv2_full_n, icmp_ln71_2_reg_3011_pp0_iter1_reg)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln71_2_reg_3011_pp0_iter1_reg = ap_const_lv1_1) and (s_conv2_full_n = ap_const_logic_0));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter2_assign_proc : process(s_conv2_full_n, icmp_ln71_2_reg_3011_pp0_iter1_reg)
    begin
                ap_block_state5_pp0_stage0_iter2 <= ((icmp_ln71_2_reg_3011_pp0_iter1_reg = ap_const_lv1_1) and (s_conv2_full_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln71_reg_2929)
    begin
        if (((icmp_ln71_reg_2929 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln71_reg_2929, ap_block_pp0_stage0_subdone)
    begin
        if (((icmp_ln71_reg_2929 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ch_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, ch_2_fu_414)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ch <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_ch <= ch_2_fu_414;
        end if; 
    end process;


    conv2_weights_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln76_20_fu_1679_p1, ap_block_pp0_stage1, zext_ln76_24_fu_1985_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                conv2_weights_address0 <= zext_ln76_24_fu_1985_p1(13 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                conv2_weights_address0 <= zext_ln76_20_fu_1679_p1(13 - 1 downto 0);
            else 
                conv2_weights_address0 <= "XXXXXXXXXXXXX";
            end if;
        else 
            conv2_weights_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    conv2_weights_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln76_19_fu_1630_p1, ap_block_pp0_stage1, zext_ln76_23_fu_1975_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                conv2_weights_address1 <= zext_ln76_23_fu_1975_p1(13 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                conv2_weights_address1 <= zext_ln76_19_fu_1630_p1(13 - 1 downto 0);
            else 
                conv2_weights_address1 <= "XXXXXXXXXXXXX";
            end if;
        else 
            conv2_weights_address1 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    conv2_weights_address2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln76_18_fu_1581_p1, ap_block_pp0_stage1, zext_ln76_22_fu_1965_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                conv2_weights_address2 <= zext_ln76_22_fu_1965_p1(13 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                conv2_weights_address2 <= zext_ln76_18_fu_1581_p1(13 - 1 downto 0);
            else 
                conv2_weights_address2 <= "XXXXXXXXXXXXX";
            end if;
        else 
            conv2_weights_address2 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    conv2_weights_address3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln76_17_fu_1532_p1, zext_ln76_21_fu_1955_p1, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                conv2_weights_address3 <= zext_ln76_21_fu_1955_p1(13 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                conv2_weights_address3 <= zext_ln76_17_fu_1532_p1(13 - 1 downto 0);
            else 
                conv2_weights_address3 <= "XXXXXXXXXXXXX";
            end if;
        else 
            conv2_weights_address3 <= "XXXXXXXXXXXXX";
        end if; 
    end process;

    conv2_weights_address4 <= zext_ln76_16_fu_1483_p1(13 - 1 downto 0);

    conv2_weights_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            conv2_weights_ce0 <= ap_const_logic_1;
        else 
            conv2_weights_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    conv2_weights_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            conv2_weights_ce1 <= ap_const_logic_1;
        else 
            conv2_weights_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    conv2_weights_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            conv2_weights_ce2 <= ap_const_logic_1;
        else 
            conv2_weights_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    conv2_weights_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            conv2_weights_ce3 <= ap_const_logic_1;
        else 
            conv2_weights_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    conv2_weights_ce4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_weights_ce4 <= ap_const_logic_1;
        else 
            conv2_weights_ce4 <= ap_const_logic_0;
        end if; 
    end process;

    deleted_zeros_fu_2884_p2 <= (or_ln888_fu_2878_p2 and Range1_all_zeros_fu_2858_p2);
    icmp_ln71_2_fu_1874_p2 <= "1" when (add_ln71_fu_1431_p2 = ap_const_lv5_10) else "0";
    icmp_ln71_fu_1425_p2 <= "1" when (ap_sig_allocacmp_ch = ap_const_lv5_10) else "0";
    or_ln888_fu_2878_p2 <= (xor_ln888_fu_2872_p2 or p_Result_36_fu_2840_p3);
    overflow_10_fu_2046_p2 <= (xor_ln895_10_fu_2040_p2 and p_Result_19_fu_2032_p3);
    overflow_11_fu_2127_p2 <= (xor_ln895_11_fu_2121_p2 and p_Result_21_fu_2113_p3);
    overflow_12_fu_2208_p2 <= (xor_ln895_12_fu_2202_p2 and p_Result_23_fu_2194_p3);
    overflow_13_fu_2289_p2 <= (xor_ln895_13_fu_2283_p2 and p_Result_25_fu_2275_p3);
    overflow_14_fu_2421_p2 <= (xor_ln895_14_fu_2416_p2 and p_Result_27_reg_3071);
    overflow_15_fu_2498_p2 <= (xor_ln895_15_fu_2492_p2 and p_Result_29_fu_2484_p3);
    overflow_16_fu_2579_p2 <= (xor_ln895_16_fu_2573_p2 and p_Result_31_fu_2565_p3);
    overflow_17_fu_2660_p2 <= (xor_ln895_17_fu_2654_p2 and p_Result_33_fu_2646_p3);
    overflow_18_fu_2741_p2 <= (xor_ln895_18_fu_2735_p2 and p_Result_35_fu_2727_p3);
    overflow_fu_2896_p2 <= (xor_ln895_fu_2890_p2 or p_Result_36_fu_2840_p3);
    p_Result_19_fu_2032_p3 <= acc_V_21_fu_2026_p2(31 downto 31);
    p_Result_20_fu_2099_p3 <= ret_V_9_fu_2093_p2(32 downto 32);
    p_Result_21_fu_2113_p3 <= acc_V_23_fu_2107_p2(31 downto 31);
    p_Result_22_fu_2180_p3 <= ret_V_10_fu_2174_p2(32 downto 32);
    p_Result_23_fu_2194_p3 <= acc_V_25_fu_2188_p2(31 downto 31);
    p_Result_24_fu_2261_p3 <= ret_V_11_fu_2255_p2(32 downto 32);
    p_Result_25_fu_2275_p3 <= acc_V_27_fu_2269_p2(31 downto 31);
    p_Result_28_fu_2470_p3 <= ret_V_13_fu_2464_p2(32 downto 32);
    p_Result_29_fu_2484_p3 <= acc_V_31_fu_2478_p2(31 downto 31);
    p_Result_30_fu_2551_p3 <= ret_V_14_fu_2545_p2(32 downto 32);
    p_Result_31_fu_2565_p3 <= acc_V_33_fu_2559_p2(31 downto 31);
    p_Result_32_fu_2632_p3 <= ret_V_15_fu_2626_p2(32 downto 32);
    p_Result_33_fu_2646_p3 <= acc_V_35_fu_2640_p2(31 downto 31);
    p_Result_34_fu_2713_p3 <= ret_V_16_fu_2707_p2(32 downto 32);
    p_Result_35_fu_2727_p3 <= acc_V_37_fu_2721_p2(31 downto 31);
    p_Result_36_fu_2840_p3 <= p_Val2_40_fu_2828_p2(7 downto 7);
    p_Result_s_fu_2018_p3 <= ret_V_fu_2012_p2(32 downto 32);
    p_Val2_39_fu_2792_p4 <= acc_V_38_fu_2784_p3(19 downto 12);
    p_Val2_40_fu_2828_p2 <= std_logic_vector(unsigned(p_Val2_39_fu_2792_p4) + unsigned(zext_ln377_fu_2810_p1));
    ret_V_10_fu_2174_p2 <= std_logic_vector(signed(sext_ln813_10_fu_2155_p1) + signed(sext_ln1347_21_fu_2166_p1));
    ret_V_11_fu_2255_p2 <= std_logic_vector(signed(sext_ln813_11_fu_2236_p1) + signed(sext_ln1347_23_fu_2247_p1));
    ret_V_12_fu_2336_p2 <= std_logic_vector(signed(sext_ln813_12_fu_2317_p1) + signed(sext_ln1347_25_fu_2328_p1));
    ret_V_13_fu_2464_p2 <= std_logic_vector(signed(sext_ln813_13_fu_2445_p1) + signed(sext_ln1347_27_fu_2456_p1));
    ret_V_14_fu_2545_p2 <= std_logic_vector(signed(sext_ln813_14_fu_2526_p1) + signed(sext_ln1347_29_fu_2537_p1));
    ret_V_15_fu_2626_p2 <= std_logic_vector(signed(sext_ln813_15_fu_2607_p1) + signed(sext_ln1347_31_fu_2618_p1));
    ret_V_16_fu_2707_p2 <= std_logic_vector(signed(sext_ln813_16_fu_2688_p1) + signed(sext_ln1347_33_fu_2699_p1));
    ret_V_9_fu_2093_p2 <= std_logic_vector(signed(sext_ln813_9_fu_2074_p1) + signed(sext_ln1347_19_fu_2085_p1));
    ret_V_fu_2012_p2 <= std_logic_vector(signed(sext_ln813_fu_1993_p1) + signed(sext_ln1347_fu_2004_p1));
    rhs_10_fu_2159_p3 <= (mul_ln1347_10_reg_3025 & ap_const_lv8_0);
    rhs_11_fu_2240_p3 <= (mul_ln1347_11_reg_3030 & ap_const_lv8_0);
    rhs_12_fu_2321_p3 <= (mul_ln1347_12_reg_3035 & ap_const_lv8_0);
    rhs_13_fu_2449_p3 <= (mul_ln1347_13_reg_3077 & ap_const_lv8_0);
    rhs_14_fu_2530_p3 <= (mul_ln1347_14_reg_3082 & ap_const_lv8_0);
    rhs_15_fu_2611_p3 <= (mul_ln1347_15_reg_3087 & ap_const_lv8_0);
    rhs_16_fu_2692_p3 <= (mul_ln1347_16_reg_3092 & ap_const_lv8_0);
    rhs_9_fu_2078_p3 <= (mul_ln1347_9_reg_3020 & ap_const_lv8_0);
    rhs_fu_1997_p3 <= (mul_ln1347_reg_3015 & ap_const_lv8_0);

    s_conv2_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, s_conv2_full_n, ap_block_pp0_stage0, icmp_ln71_2_reg_3011_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln71_2_reg_3011_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_conv2_blk_n <= s_conv2_full_n;
        else 
            s_conv2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_conv2_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln302_fu_2902_p3),8));

    s_conv2_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln71_2_reg_3011_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln71_2_reg_3011_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_conv2_write <= ap_const_logic_1;
        else 
            s_conv2_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln302_fu_2902_p3 <= 
        ap_const_lv7_7F when (overflow_fu_2896_p2(0) = '1') else 
        add_ln856_fu_2834_p2;
    select_ln346_10_fu_2220_p3 <= 
        ap_const_lv32_7FFFFFFF when (overflow_12_fu_2208_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln346_11_fu_2301_p3 <= 
        ap_const_lv32_7FFFFFFF when (overflow_13_fu_2289_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln346_12_fu_2430_p3 <= 
        ap_const_lv32_7FFFFFFF when (overflow_14_fu_2421_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln346_13_fu_2510_p3 <= 
        ap_const_lv32_7FFFFFFF when (overflow_15_fu_2498_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln346_14_fu_2591_p3 <= 
        ap_const_lv32_7FFFFFFF when (overflow_16_fu_2579_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln346_15_fu_2672_p3 <= 
        ap_const_lv32_7FFFFFFF when (overflow_17_fu_2660_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln346_16_fu_2753_p3 <= 
        ap_const_lv32_7FFFFFFF when (overflow_18_fu_2741_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln346_9_fu_2139_p3 <= 
        ap_const_lv32_7FFFFFFF when (overflow_11_fu_2127_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln346_fu_2058_p3 <= 
        ap_const_lv32_7FFFFFFF when (overflow_10_fu_2046_p2(0) = '1') else 
        ap_const_lv32_80000000;
        sext_ln1347_18_fu_2008_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_fu_1997_p3),32));

        sext_ln1347_19_fu_2085_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_9_fu_2078_p3),33));

        sext_ln1347_20_fu_2089_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_9_fu_2078_p3),32));

        sext_ln1347_21_fu_2166_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_10_fu_2159_p3),33));

        sext_ln1347_22_fu_2170_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_10_fu_2159_p3),32));

        sext_ln1347_23_fu_2247_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_11_fu_2240_p3),33));

        sext_ln1347_24_fu_2251_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_11_fu_2240_p3),32));

        sext_ln1347_25_fu_2328_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_12_fu_2321_p3),33));

        sext_ln1347_26_fu_2332_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_12_fu_2321_p3),32));

        sext_ln1347_27_fu_2456_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_13_fu_2449_p3),33));

        sext_ln1347_28_fu_2460_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_13_fu_2449_p3),32));

        sext_ln1347_29_fu_2537_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_14_fu_2530_p3),33));

        sext_ln1347_30_fu_2541_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_14_fu_2530_p3),32));

        sext_ln1347_31_fu_2618_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_15_fu_2611_p3),33));

        sext_ln1347_32_fu_2622_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_15_fu_2611_p3),32));

        sext_ln1347_33_fu_2699_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_16_fu_2692_p3),33));

        sext_ln1347_34_fu_2703_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_16_fu_2692_p3),32));

        sext_ln1347_fu_2004_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_fu_1997_p3),33));

        sext_ln66_cast_fu_1408_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln66),32));

        sext_ln813_10_fu_2155_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_V_24_fu_2147_p3),33));

        sext_ln813_11_fu_2236_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_V_26_fu_2228_p3),33));

        sext_ln813_12_fu_2317_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_V_28_fu_2309_p3),33));

        sext_ln813_13_fu_2445_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_V_30_fu_2438_p3),33));

        sext_ln813_14_fu_2526_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_V_32_fu_2518_p3),33));

        sext_ln813_15_fu_2607_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_V_34_fu_2599_p3),33));

        sext_ln813_16_fu_2688_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_V_36_fu_2680_p3),33));

        sext_ln813_9_fu_2074_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_V_22_fu_2066_p3),33));

    sext_ln813_fu_1993_p0 <= lhs_fu_410;
        sext_ln813_fu_1993_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln813_fu_1993_p0),33));

    shl_ln76_4_fu_1445_p3 <= (trunc_ln76_fu_1441_p1 & ap_const_lv3_0);
    tmp_2_fu_2848_p4 <= acc_V_38_fu_2784_p3(30 downto 20);
    tmp_5_fu_2802_p3 <= acc_V_38_fu_2784_p3(11 downto 11);
    tmp_7_fu_2864_p3 <= acc_V_38_fu_2784_p3(19 downto 19);
    tmp_fu_2777_p3 <= acc_V_reg_3097(31 downto 31);
    trunc_ln377_3_fu_2814_p4 <= acc_V_38_fu_2784_p3(18 downto 12);
    trunc_ln71_fu_2774_p1 <= acc_V_reg_3097(31 - 1 downto 0);
    trunc_ln76_fu_1441_p1 <= ap_sig_allocacmp_ch(4 - 1 downto 0);
    xor_ln302_10_fu_2214_p2 <= (p_Result_23_fu_2194_p3 xor p_Result_22_fu_2180_p3);
    xor_ln302_11_fu_2295_p2 <= (p_Result_25_fu_2275_p3 xor p_Result_24_fu_2261_p3);
    xor_ln302_12_fu_2426_p2 <= (p_Result_27_reg_3071 xor p_Result_26_reg_3060);
    xor_ln302_13_fu_2504_p2 <= (p_Result_29_fu_2484_p3 xor p_Result_28_fu_2470_p3);
    xor_ln302_14_fu_2585_p2 <= (p_Result_31_fu_2565_p3 xor p_Result_30_fu_2551_p3);
    xor_ln302_15_fu_2666_p2 <= (p_Result_33_fu_2646_p3 xor p_Result_32_fu_2632_p3);
    xor_ln302_16_fu_2747_p2 <= (p_Result_35_fu_2727_p3 xor p_Result_34_fu_2713_p3);
    xor_ln302_9_fu_2133_p2 <= (p_Result_21_fu_2113_p3 xor p_Result_20_fu_2099_p3);
    xor_ln302_fu_2052_p2 <= (p_Result_s_fu_2018_p3 xor p_Result_19_fu_2032_p3);
    xor_ln888_fu_2872_p2 <= (tmp_7_fu_2864_p3 xor ap_const_lv1_1);
    xor_ln895_10_fu_2040_p2 <= (p_Result_s_fu_2018_p3 xor ap_const_lv1_1);
    xor_ln895_11_fu_2121_p2 <= (p_Result_20_fu_2099_p3 xor ap_const_lv1_1);
    xor_ln895_12_fu_2202_p2 <= (p_Result_22_fu_2180_p3 xor ap_const_lv1_1);
    xor_ln895_13_fu_2283_p2 <= (p_Result_24_fu_2261_p3 xor ap_const_lv1_1);
    xor_ln895_14_fu_2416_p2 <= (p_Result_26_reg_3060 xor ap_const_lv1_1);
    xor_ln895_15_fu_2492_p2 <= (p_Result_28_fu_2470_p3 xor ap_const_lv1_1);
    xor_ln895_16_fu_2573_p2 <= (p_Result_30_fu_2551_p3 xor ap_const_lv1_1);
    xor_ln895_17_fu_2654_p2 <= (p_Result_32_fu_2632_p3 xor ap_const_lv1_1);
    xor_ln895_18_fu_2735_p2 <= (p_Result_34_fu_2713_p3 xor ap_const_lv1_1);
    xor_ln895_fu_2890_p2 <= (deleted_zeros_fu_2884_p2 xor ap_const_lv1_1);
    zext_ln377_2_fu_2824_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_2802_p3),7));
    zext_ln377_fu_2810_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_2802_p3),8));
    zext_ln71_2_cast_fu_1404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln71_2),10));
    zext_ln71_fu_1437_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_ch),8));
    zext_ln76_13_fu_1453_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln76_4_fu_1445_p3),8));
    zext_ln76_14_fu_1463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_fu_1457_p2),10));
    zext_ln76_15_fu_1473_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_11_fu_1467_p2),13));
    zext_ln76_16_fu_1483_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_12_fu_1477_p2),64));
    zext_ln76_17_fu_1532_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_13_fu_1526_p2),64));
    zext_ln76_18_fu_1581_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_14_fu_1575_p2),64));
    zext_ln76_19_fu_1630_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_15_fu_1624_p2),64));
    zext_ln76_20_fu_1679_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_16_fu_1673_p2),64));
    zext_ln76_21_fu_1955_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_17_fu_1950_p2),64));
    zext_ln76_22_fu_1965_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_18_fu_1960_p2),64));
    zext_ln76_23_fu_1975_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_19_fu_1970_p2),64));
    zext_ln76_24_fu_1985_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_20_fu_1980_p2),64));
    zext_ln76_cast_fu_1400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln76),13));
end behav;
