// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module vgg_accelerator_max_val (
        ap_ready,
        a,
        b,
        ap_return
);


output   ap_ready;
input  [7:0] a;
input  [7:0] b;
output  [7:0] ap_return;

wire   [0:0] icmp_ln1649_fu_18_p2;

assign ap_ready = 1'b1;

assign ap_return = ((icmp_ln1649_fu_18_p2[0:0] == 1'b1) ? a : b);

assign icmp_ln1649_fu_18_p2 = (($signed(a) > $signed(b)) ? 1'b1 : 1'b0);

endmodule //vgg_accelerator_max_val
