// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module vgg_accelerator_layer_block_16_32_16_Pipeline_VITIS_LOOP_31_1_VITIS_LOOP_32_2_VITIS_LOOP_33_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_address0,
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_ce0,
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_we0,
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_d0,
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_address0,
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_ce0,
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_we0,
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_address0;
output   void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_ce0;
output   void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_we0;
output  [7:0] void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_d0;
output  [7:0] void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_address0;
output   void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_ce0;
output   void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_we0;
output  [7:0] void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_d0;

reg ap_idle;
reg void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_ce0;
reg void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_we0;
reg void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_ce0;
reg void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln31_fu_137_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln34_2_fu_276_p1;
reg   [4:0] w_fu_58;
wire   [4:0] add_ln33_fu_282_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_w_load;
reg   [1:0] h_fu_62;
wire   [1:0] select_ln32_5_fu_258_p3;
reg   [1:0] ap_sig_allocacmp_h_load;
reg   [6:0] indvar_flatten_fu_66;
wire   [6:0] select_ln32_6_fu_294_p3;
reg   [6:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [4:0] c_fu_70;
wire   [4:0] select_ln31_2_fu_178_p3;
reg   [4:0] ap_sig_allocacmp_c_load;
reg   [9:0] indvar_flatten13_fu_74;
wire   [9:0] add_ln31_2_fu_143_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten13_load;
wire   [0:0] select_ln32_4_fu_250_p3;
wire   [0:0] icmp_ln32_fu_164_p2;
wire   [4:0] add_ln31_fu_158_p2;
wire   [3:0] trunc_ln34_fu_186_p1;
wire   [0:0] empty_45_fu_204_p1;
wire   [0:0] xor_ln31_fu_198_p2;
wire   [0:0] icmp_ln33_fu_214_p2;
wire   [1:0] select_ln31_fu_170_p3;
wire   [0:0] and_ln31_2_fu_220_p2;
wire   [0:0] or_ln32_fu_232_p2;
wire   [1:0] add_ln32_fu_226_p2;
wire   [0:0] empty_46_fu_246_p1;
wire   [0:0] and_ln31_fu_208_p2;
wire   [4:0] select_ln32_fu_238_p3;
wire   [7:0] tmp_fu_190_p3;
wire   [7:0] zext_ln34_fu_266_p1;
wire   [7:0] add_ln34_fu_270_p2;
wire   [6:0] add_ln32_2_fu_288_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

vgg_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln31_fu_137_p2 == 1'd0)) begin
            c_fu_70 <= select_ln31_2_fu_178_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_70 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln31_fu_137_p2 == 1'd0)) begin
            h_fu_62 <= select_ln32_5_fu_258_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            h_fu_62 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln31_fu_137_p2 == 1'd0)) begin
            indvar_flatten13_fu_74 <= add_ln31_2_fu_143_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_74 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln31_fu_137_p2 == 1'd0)) begin
            indvar_flatten_fu_66 <= select_ln32_6_fu_294_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_66 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln31_fu_137_p2 == 1'd0)) begin
            w_fu_58 <= add_ln33_fu_282_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            w_fu_58 <= 5'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_137_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_c_load = 5'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_70;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_h_load = 2'd0;
    end else begin
        ap_sig_allocacmp_h_load = h_fu_62;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_74;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_66;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_w_load = 5'd0;
    end else begin
        ap_sig_allocacmp_w_load = w_fu_58;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_ce0 = 1'b1;
    end else begin
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln32_4_fu_250_p3 == 1'd0) & (icmp_ln31_fu_137_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_we0 = 1'b1;
    end else begin
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_ce0 = 1'b1;
    end else begin
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln32_4_fu_250_p3 == 1'd1) & (icmp_ln31_fu_137_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_we0 = 1'b1;
    end else begin
        void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln31_2_fu_143_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 10'd1);

assign add_ln31_fu_158_p2 = (ap_sig_allocacmp_c_load + 5'd1);

assign add_ln32_2_fu_288_p2 = (ap_sig_allocacmp_indvar_flatten_load + 7'd1);

assign add_ln32_fu_226_p2 = (select_ln31_fu_170_p3 + 2'd1);

assign add_ln33_fu_282_p2 = (select_ln32_fu_238_p3 + 5'd1);

assign add_ln34_fu_270_p2 = (tmp_fu_190_p3 + zext_ln34_fu_266_p1);

assign and_ln31_2_fu_220_p2 = (xor_ln31_fu_198_p2 & icmp_ln33_fu_214_p2);

assign and_ln31_fu_208_p2 = (xor_ln31_fu_198_p2 & empty_45_fu_204_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_45_fu_204_p1 = ap_sig_allocacmp_h_load[0:0];

assign empty_46_fu_246_p1 = add_ln32_fu_226_p2[0:0];

assign icmp_ln31_fu_137_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_164_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 7'd32) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_214_p2 = ((ap_sig_allocacmp_w_load == 5'd16) ? 1'b1 : 1'b0);

assign or_ln32_fu_232_p2 = (icmp_ln32_fu_164_p2 | and_ln31_2_fu_220_p2);

assign select_ln31_2_fu_178_p3 = ((icmp_ln32_fu_164_p2[0:0] == 1'b1) ? add_ln31_fu_158_p2 : ap_sig_allocacmp_c_load);

assign select_ln31_fu_170_p3 = ((icmp_ln32_fu_164_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_h_load);

assign select_ln32_4_fu_250_p3 = ((and_ln31_2_fu_220_p2[0:0] == 1'b1) ? empty_46_fu_246_p1 : and_ln31_fu_208_p2);

assign select_ln32_5_fu_258_p3 = ((and_ln31_2_fu_220_p2[0:0] == 1'b1) ? add_ln32_fu_226_p2 : select_ln31_fu_170_p3);

assign select_ln32_6_fu_294_p3 = ((icmp_ln32_fu_164_p2[0:0] == 1'b1) ? 7'd1 : add_ln32_2_fu_288_p2);

assign select_ln32_fu_238_p3 = ((or_ln32_fu_232_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_w_load);

assign tmp_fu_190_p3 = {{trunc_ln34_fu_186_p1}, {4'd0}};

assign trunc_ln34_fu_186_p1 = select_ln31_2_fu_178_p3[3:0];

assign void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_address0 = zext_ln34_2_fu_276_p1;

assign void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_1_d0 = 8'd0;

assign void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_address0 = zext_ln34_2_fu_276_p1;

assign void_layer_block_stream_stream_signed_char_const_16_3_3_signed_char_con_d0 = 8'd0;

assign xor_ln31_fu_198_p2 = (icmp_ln32_fu_164_p2 ^ 1'd1);

assign zext_ln34_2_fu_276_p1 = add_ln34_fu_270_p2;

assign zext_ln34_fu_266_p1 = select_ln32_fu_238_p3;

endmodule //vgg_accelerator_layer_block_16_32_16_Pipeline_VITIS_LOOP_31_1_VITIS_LOOP_32_2_VITIS_LOOP_33_3
