// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_146_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        OUTPUT_STREAM_TREADY,
        sext_ln141,
        shl_ln,
        flat_img_V_address0,
        flat_img_V_ce0,
        flat_img_V_q0,
        output_packet_last_V,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   OUTPUT_STREAM_TREADY;
input  [13:0] sext_ln141;
input  [10:0] shl_ln;
output  [9:0] flat_img_V_address0;
output   flat_img_V_ce0;
input  [7:0] flat_img_V_q0;
input  [0:0] output_packet_last_V;
output  [31:0] OUTPUT_STREAM_TDATA;
output   OUTPUT_STREAM_TVALID;
output  [3:0] OUTPUT_STREAM_TKEEP;
output  [3:0] OUTPUT_STREAM_TSTRB;
output  [0:0] OUTPUT_STREAM_TLAST;

reg ap_idle;
reg flat_img_V_ce0;
reg OUTPUT_STREAM_TVALID;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln146_1_reg_627;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln146_fu_211_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_subdone;
wire   [10:0] dense_weights_address0;
reg    dense_weights_ce0;
wire  signed [4:0] dense_weights_q0;
reg    OUTPUT_STREAM_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln146_reg_613;
wire   [0:0] icmp_ln146_1_fu_261_p2;
wire   [11:0] mul_ln1347_fu_280_p2;
reg   [11:0] mul_ln1347_reg_631;
wire    ap_block_pp0_stage1_11001;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln152_fu_251_p1;
wire   [63:0] zext_ln153_fu_256_p1;
reg   [31:0] lhs_fu_124;
wire   [31:0] acc_V_fu_362_p3;
wire  signed [31:0] sext_ln141_cast_fu_194_p1;
wire    ap_loop_init;
reg   [10:0] i_2_fu_128;
wire   [10:0] add_ln146_fu_217_p2;
reg   [10:0] ap_sig_allocacmp_i;
reg    ap_block_pp0_stage0_01001;
wire   [3:0] trunc_ln150_fu_233_p1;
wire   [5:0] channel_bits_fu_223_p4;
wire   [10:0] add_ln152_fu_245_p2;
wire   [9:0] k_fu_237_p3;
wire    ap_block_pp0_stage1;
wire  signed [31:0] sext_ln813_fu_289_p0;
wire  signed [19:0] rhs_fu_293_p3;
wire  signed [32:0] sext_ln813_fu_289_p1;
wire  signed [32:0] sext_ln1347_fu_300_p1;
wire   [32:0] ret_V_fu_308_p2;
wire  signed [31:0] acc_V_40_fu_322_p0;
wire  signed [31:0] sext_ln1347_185_fu_304_p1;
wire   [31:0] acc_V_40_fu_322_p2;
wire   [0:0] p_Result_s_fu_314_p3;
wire   [0:0] p_Result_37_fu_328_p3;
wire   [0:0] xor_ln895_fu_336_p2;
wire   [0:0] overflow_fu_342_p2;
wire   [0:0] xor_ln302_fu_348_p2;
wire   [31:0] select_ln346_fu_354_p3;
wire   [0:0] tmp_fu_396_p3;
wire   [7:0] final_res_V_fu_378_p4;
wire   [7:0] zext_ln377_fu_404_p1;
wire   [7:0] final_res_V_1_fu_408_p2;
wire   [0:0] p_Result_40_fu_414_p3;
wire   [0:0] p_Result_39_fu_388_p3;
wire   [0:0] xor_ln896_fu_422_p2;
wire   [10:0] tmp_i_fu_434_p4;
wire   [11:0] tmp_i_52_fu_450_p4;
wire   [0:0] carry_1_fu_428_p2;
wire   [0:0] Range1_all_ones_fu_460_p2;
wire   [0:0] Range1_all_zeros_fu_466_p2;
wire   [0:0] tmp_258_fu_480_p3;
wire   [0:0] Range2_all_ones_fu_444_p2;
wire   [0:0] xor_ln890_fu_488_p2;
wire   [0:0] and_ln890_fu_494_p2;
wire   [0:0] deleted_zeros_fu_472_p3;
wire   [0:0] xor_ln895_123_fu_514_p2;
wire   [0:0] p_Result_38_fu_370_p3;
wire   [0:0] or_ln895_fu_520_p2;
wire   [0:0] xor_ln895_124_fu_526_p2;
wire   [0:0] deleted_ones_fu_500_p3;
wire   [0:0] xor_ln896_1_fu_538_p2;
wire   [0:0] and_ln891_fu_508_p2;
wire   [0:0] or_ln896_fu_544_p2;
wire   [0:0] xor_ln896_2_fu_550_p2;
wire   [0:0] overflow_19_fu_532_p2;
wire   [0:0] underflow_fu_556_p2;
wire   [0:0] or_ln346_fu_570_p2;
wire   [7:0] select_ln346_105_fu_562_p3;
wire   [7:0] final_res_V_2_fu_576_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_146_3_dense_weights_ROM_AUTO_1R #(
    .DataWidth( 5 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
dense_weights_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_weights_address0),
    .ce0(dense_weights_ce0),
    .q0(dense_weights_q0)
);

vgg_accelerator_mul_8s_5s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8s_5s_12_1_1_U1401(
    .din0(flat_img_V_q0),
    .din1(dense_weights_q0),
    .dout(mul_ln1347_fu_280_p2)
);

vgg_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln146_fu_211_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_2_fu_128 <= add_ln146_fu_217_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_2_fu_128 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            lhs_fu_124 <= sext_ln141_cast_fu_194_p1;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            lhs_fu_124 <= acc_V_fu_362_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln146_fu_211_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln146_1_reg_627 <= icmp_ln146_1_fu_261_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln146_reg_613 <= icmp_ln146_fu_211_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln146_reg_613 == 1'd0))) begin
        mul_ln1347_reg_631 <= mul_ln1347_fu_280_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln146_1_reg_627 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OUTPUT_STREAM_TDATA_blk_n = OUTPUT_STREAM_TREADY;
    end else begin
        OUTPUT_STREAM_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln146_1_reg_627 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OUTPUT_STREAM_TVALID = 1'b1;
    end else begin
        OUTPUT_STREAM_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln146_fu_211_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 11'd0;
    end else begin
        ap_sig_allocacmp_i = i_2_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dense_weights_ce0 = 1'b1;
    end else begin
        dense_weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        flat_img_V_ce0 = 1'b1;
    end else begin
        flat_img_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OUTPUT_STREAM_TDATA = final_res_V_2_fu_576_p3;

assign OUTPUT_STREAM_TKEEP = 4'd15;

assign OUTPUT_STREAM_TLAST = output_packet_last_V;

assign OUTPUT_STREAM_TSTRB = 4'd15;

assign Range1_all_ones_fu_460_p2 = ((tmp_i_52_fu_450_p4 == 12'd4095) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_466_p2 = ((tmp_i_52_fu_450_p4 == 12'd0) ? 1'b1 : 1'b0);

assign Range2_all_ones_fu_444_p2 = ((tmp_i_fu_434_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign acc_V_40_fu_322_p0 = lhs_fu_124;

assign acc_V_40_fu_322_p2 = ($signed(acc_V_40_fu_322_p0) + $signed(sext_ln1347_185_fu_304_p1));

assign acc_V_fu_362_p3 = ((xor_ln302_fu_348_p2[0:0] == 1'b1) ? select_ln346_fu_354_p3 : acc_V_40_fu_322_p2);

assign add_ln146_fu_217_p2 = (ap_sig_allocacmp_i + 11'd1);

assign add_ln152_fu_245_p2 = (ap_sig_allocacmp_i + shl_ln);

assign and_ln890_fu_494_p2 = (xor_ln890_fu_488_p2 & Range2_all_ones_fu_444_p2);

assign and_ln891_fu_508_p2 = (carry_1_fu_428_p2 & Range1_all_ones_fu_460_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((icmp_ln146_1_reg_627 == 1'd1) & (1'b0 == OUTPUT_STREAM_TREADY) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((icmp_ln146_1_reg_627 == 1'd1) & (1'b0 == OUTPUT_STREAM_TREADY))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((icmp_ln146_1_reg_627 == 1'd1) & (1'b0 == OUTPUT_STREAM_TREADY))));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((icmp_ln146_1_reg_627 == 1'd1) & (1'b0 == OUTPUT_STREAM_TREADY));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((icmp_ln146_1_reg_627 == 1'd1) & (1'b0 == OUTPUT_STREAM_TREADY));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign carry_1_fu_428_p2 = (xor_ln896_fu_422_p2 & p_Result_39_fu_388_p3);

assign channel_bits_fu_223_p4 = {{ap_sig_allocacmp_i[9:4]}};

assign deleted_ones_fu_500_p3 = ((carry_1_fu_428_p2[0:0] == 1'b1) ? and_ln890_fu_494_p2 : Range1_all_ones_fu_460_p2);

assign deleted_zeros_fu_472_p3 = ((carry_1_fu_428_p2[0:0] == 1'b1) ? Range1_all_ones_fu_460_p2 : Range1_all_zeros_fu_466_p2);

assign dense_weights_address0 = zext_ln152_fu_251_p1;

assign final_res_V_1_fu_408_p2 = (final_res_V_fu_378_p4 + zext_ln377_fu_404_p1);

assign final_res_V_2_fu_576_p3 = ((or_ln346_fu_570_p2[0:0] == 1'b1) ? select_ln346_105_fu_562_p3 : final_res_V_1_fu_408_p2);

assign final_res_V_fu_378_p4 = {{acc_V_fu_362_p3[19:12]}};

assign flat_img_V_address0 = zext_ln153_fu_256_p1;

assign icmp_ln146_1_fu_261_p2 = ((add_ln146_fu_217_p2 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln146_fu_211_p2 = ((ap_sig_allocacmp_i == 11'd1024) ? 1'b1 : 1'b0);

assign k_fu_237_p3 = {{trunc_ln150_fu_233_p1}, {channel_bits_fu_223_p4}};

assign or_ln346_fu_570_p2 = (underflow_fu_556_p2 | overflow_19_fu_532_p2);

assign or_ln895_fu_520_p2 = (xor_ln895_123_fu_514_p2 | p_Result_40_fu_414_p3);

assign or_ln896_fu_544_p2 = (xor_ln896_fu_422_p2 | xor_ln896_1_fu_538_p2);

assign overflow_19_fu_532_p2 = (xor_ln895_124_fu_526_p2 & or_ln895_fu_520_p2);

assign overflow_fu_342_p2 = (xor_ln895_fu_336_p2 & p_Result_37_fu_328_p3);

assign p_Result_37_fu_328_p3 = acc_V_40_fu_322_p2[32'd31];

assign p_Result_38_fu_370_p3 = acc_V_fu_362_p3[32'd31];

assign p_Result_39_fu_388_p3 = acc_V_fu_362_p3[32'd19];

assign p_Result_40_fu_414_p3 = final_res_V_1_fu_408_p2[32'd7];

assign p_Result_s_fu_314_p3 = ret_V_fu_308_p2[32'd32];

assign ret_V_fu_308_p2 = ($signed(sext_ln813_fu_289_p1) + $signed(sext_ln1347_fu_300_p1));

assign rhs_fu_293_p3 = {{mul_ln1347_reg_631}, {8'd0}};

assign select_ln346_105_fu_562_p3 = ((overflow_19_fu_532_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln346_fu_354_p3 = ((overflow_fu_342_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign sext_ln1347_185_fu_304_p1 = rhs_fu_293_p3;

assign sext_ln1347_fu_300_p1 = rhs_fu_293_p3;

assign sext_ln141_cast_fu_194_p1 = $signed(sext_ln141);

assign sext_ln813_fu_289_p0 = lhs_fu_124;

assign sext_ln813_fu_289_p1 = sext_ln813_fu_289_p0;

assign tmp_258_fu_480_p3 = acc_V_fu_362_p3[32'd20];

assign tmp_fu_396_p3 = acc_V_fu_362_p3[32'd11];

assign tmp_i_52_fu_450_p4 = {{acc_V_fu_362_p3[31:20]}};

assign tmp_i_fu_434_p4 = {{acc_V_fu_362_p3[31:21]}};

assign trunc_ln150_fu_233_p1 = ap_sig_allocacmp_i[3:0];

assign underflow_fu_556_p2 = (xor_ln896_2_fu_550_p2 & p_Result_38_fu_370_p3);

assign xor_ln302_fu_348_p2 = (p_Result_s_fu_314_p3 ^ p_Result_37_fu_328_p3);

assign xor_ln890_fu_488_p2 = (tmp_258_fu_480_p3 ^ 1'd1);

assign xor_ln895_123_fu_514_p2 = (deleted_zeros_fu_472_p3 ^ 1'd1);

assign xor_ln895_124_fu_526_p2 = (p_Result_38_fu_370_p3 ^ 1'd1);

assign xor_ln895_fu_336_p2 = (p_Result_s_fu_314_p3 ^ 1'd1);

assign xor_ln896_1_fu_538_p2 = (deleted_ones_fu_500_p3 ^ 1'd1);

assign xor_ln896_2_fu_550_p2 = (or_ln896_fu_544_p2 ^ and_ln891_fu_508_p2);

assign xor_ln896_fu_422_p2 = (p_Result_40_fu_414_p3 ^ 1'd1);

assign zext_ln152_fu_251_p1 = add_ln152_fu_245_p2;

assign zext_ln153_fu_256_p1 = k_fu_237_p3;

assign zext_ln377_fu_404_p1 = tmp_fu_396_p3;

endmodule //vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_146_3
