-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_146_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    OUTPUT_STREAM_TREADY : IN STD_LOGIC;
    sext_ln141 : IN STD_LOGIC_VECTOR (13 downto 0);
    shl_ln : IN STD_LOGIC_VECTOR (10 downto 0);
    flat_img_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    flat_img_V_ce0 : OUT STD_LOGIC;
    flat_img_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    output_packet_last_V : IN STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
    OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_146_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_7FFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "01111111111111111111111111111111";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln146_1_reg_627 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln146_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal dense_weights_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal dense_weights_ce0 : STD_LOGIC;
    signal dense_weights_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal OUTPUT_STREAM_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln146_reg_613 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln146_1_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln1347_fu_280_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1347_reg_631 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln152_fu_251_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln153_fu_256_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_fu_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_fu_362_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln141_cast_fu_194_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_2_fu_128 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln146_fu_217_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln150_fu_233_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal channel_bits_fu_223_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln152_fu_245_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_fu_237_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal sext_ln813_fu_289_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_fu_293_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln813_fu_289_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln1347_fu_300_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_fu_308_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal acc_V_40_fu_322_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1347_185_fu_304_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_40_fu_322_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_fu_314_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_37_fu_328_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln302_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_fu_354_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_396_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal final_res_V_fu_378_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln377_fu_404_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal final_res_V_1_fu_408_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_40_fu_414_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_39_fu_388_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln896_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_fu_434_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_i_52_fu_450_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal carry_1_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_258_fu_480_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln890_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln890_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_472_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_123_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_38_fu_370_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln895_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_124_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_500_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln896_1_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln891_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln896_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln896_2_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_19_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln346_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_105_fu_562_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal final_res_V_2_fu_576_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component vgg_accelerator_mul_8s_5s_12_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_146_3_dense_weights_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component vgg_accelerator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    dense_weights_U : component vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_146_3_dense_weights_ROM_AUTO_1R
    generic map (
        DataWidth => 5,
        AddressRange => 2048,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dense_weights_address0,
        ce0 => dense_weights_ce0,
        q0 => dense_weights_q0);

    mul_8s_5s_12_1_1_U1401 : component vgg_accelerator_mul_8s_5s_12_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        din0 => flat_img_V_q0,
        din1 => dense_weights_q0,
        dout => mul_ln1347_fu_280_p2);

    flow_control_loop_pipe_sequential_init_U : component vgg_accelerator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    i_2_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln146_fu_211_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_2_fu_128 <= add_ln146_fu_217_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_2_fu_128 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    lhs_fu_124 <= sext_ln141_cast_fu_194_p1;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    lhs_fu_124 <= acc_V_fu_362_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln146_fu_211_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln146_1_reg_627 <= icmp_ln146_1_fu_261_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln146_reg_613 <= icmp_ln146_fu_211_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln146_reg_613 = ap_const_lv1_0))) then
                mul_ln1347_reg_631 <= mul_ln1347_fu_280_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage1_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    OUTPUT_STREAM_TDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(final_res_V_2_fu_576_p3),32));

    OUTPUT_STREAM_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, OUTPUT_STREAM_TREADY, icmp_ln146_1_reg_627, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln146_1_reg_627 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            OUTPUT_STREAM_TDATA_blk_n <= OUTPUT_STREAM_TREADY;
        else 
            OUTPUT_STREAM_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    OUTPUT_STREAM_TKEEP <= ap_const_lv4_F;
    OUTPUT_STREAM_TLAST <= output_packet_last_V;
    OUTPUT_STREAM_TSTRB <= ap_const_lv4_F;

    OUTPUT_STREAM_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln146_1_reg_627, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln146_1_reg_627 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            OUTPUT_STREAM_TVALID <= ap_const_logic_1;
        else 
            OUTPUT_STREAM_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    Range1_all_ones_fu_460_p2 <= "1" when (tmp_i_52_fu_450_p4 = ap_const_lv12_FFF) else "0";
    Range1_all_zeros_fu_466_p2 <= "1" when (tmp_i_52_fu_450_p4 = ap_const_lv12_0) else "0";
    Range2_all_ones_fu_444_p2 <= "1" when (tmp_i_fu_434_p4 = ap_const_lv11_7FF) else "0";
    acc_V_40_fu_322_p0 <= lhs_fu_124;
    acc_V_40_fu_322_p2 <= std_logic_vector(signed(acc_V_40_fu_322_p0) + signed(sext_ln1347_185_fu_304_p1));
    acc_V_fu_362_p3 <= 
        select_ln346_fu_354_p3 when (xor_ln302_fu_348_p2(0) = '1') else 
        acc_V_40_fu_322_p2;
    add_ln146_fu_217_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv11_1));
    add_ln152_fu_245_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(shl_ln));
    and_ln890_fu_494_p2 <= (xor_ln890_fu_488_p2 and Range2_all_ones_fu_444_p2);
    and_ln891_fu_508_p2 <= (carry_1_fu_428_p2 and Range1_all_ones_fu_460_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, OUTPUT_STREAM_TREADY, icmp_ln146_1_reg_627)
    begin
                ap_block_pp0_stage0_01001 <= ((icmp_ln146_1_reg_627 = ap_const_lv1_1) and (ap_const_logic_0 = OUTPUT_STREAM_TREADY) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, OUTPUT_STREAM_TREADY, icmp_ln146_1_reg_627, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln146_1_reg_627 = ap_const_lv1_1) and (ap_const_logic_0 = OUTPUT_STREAM_TREADY))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, OUTPUT_STREAM_TREADY, icmp_ln146_1_reg_627, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln146_1_reg_627 = ap_const_lv1_1) and (ap_const_logic_0 = OUTPUT_STREAM_TREADY))));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(OUTPUT_STREAM_TREADY, icmp_ln146_1_reg_627)
    begin
                ap_block_state3_io <= ((icmp_ln146_1_reg_627 = ap_const_lv1_1) and (ap_const_logic_0 = OUTPUT_STREAM_TREADY));
    end process;


    ap_block_state3_pp0_stage0_iter1_assign_proc : process(OUTPUT_STREAM_TREADY, icmp_ln146_1_reg_627)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((icmp_ln146_1_reg_627 = ap_const_lv1_1) and (ap_const_logic_0 = OUTPUT_STREAM_TREADY));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln146_fu_211_p2)
    begin
        if (((icmp_ln146_fu_211_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_2_fu_128)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_i <= i_2_fu_128;
        end if; 
    end process;

    carry_1_fu_428_p2 <= (xor_ln896_fu_422_p2 and p_Result_39_fu_388_p3);
    channel_bits_fu_223_p4 <= ap_sig_allocacmp_i(9 downto 4);
    deleted_ones_fu_500_p3 <= 
        and_ln890_fu_494_p2 when (carry_1_fu_428_p2(0) = '1') else 
        Range1_all_ones_fu_460_p2;
    deleted_zeros_fu_472_p3 <= 
        Range1_all_ones_fu_460_p2 when (carry_1_fu_428_p2(0) = '1') else 
        Range1_all_zeros_fu_466_p2;
    dense_weights_address0 <= zext_ln152_fu_251_p1(11 - 1 downto 0);

    dense_weights_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dense_weights_ce0 <= ap_const_logic_1;
        else 
            dense_weights_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    final_res_V_1_fu_408_p2 <= std_logic_vector(unsigned(final_res_V_fu_378_p4) + unsigned(zext_ln377_fu_404_p1));
    final_res_V_2_fu_576_p3 <= 
        select_ln346_105_fu_562_p3 when (or_ln346_fu_570_p2(0) = '1') else 
        final_res_V_1_fu_408_p2;
    final_res_V_fu_378_p4 <= acc_V_fu_362_p3(19 downto 12);
    flat_img_V_address0 <= zext_ln153_fu_256_p1(10 - 1 downto 0);

    flat_img_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            flat_img_V_ce0 <= ap_const_logic_1;
        else 
            flat_img_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln146_1_fu_261_p2 <= "1" when (add_ln146_fu_217_p2 = ap_const_lv11_400) else "0";
    icmp_ln146_fu_211_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv11_400) else "0";
    k_fu_237_p3 <= (trunc_ln150_fu_233_p1 & channel_bits_fu_223_p4);
    or_ln346_fu_570_p2 <= (underflow_fu_556_p2 or overflow_19_fu_532_p2);
    or_ln895_fu_520_p2 <= (xor_ln895_123_fu_514_p2 or p_Result_40_fu_414_p3);
    or_ln896_fu_544_p2 <= (xor_ln896_fu_422_p2 or xor_ln896_1_fu_538_p2);
    overflow_19_fu_532_p2 <= (xor_ln895_124_fu_526_p2 and or_ln895_fu_520_p2);
    overflow_fu_342_p2 <= (xor_ln895_fu_336_p2 and p_Result_37_fu_328_p3);
    p_Result_37_fu_328_p3 <= acc_V_40_fu_322_p2(31 downto 31);
    p_Result_38_fu_370_p3 <= acc_V_fu_362_p3(31 downto 31);
    p_Result_39_fu_388_p3 <= acc_V_fu_362_p3(19 downto 19);
    p_Result_40_fu_414_p3 <= final_res_V_1_fu_408_p2(7 downto 7);
    p_Result_s_fu_314_p3 <= ret_V_fu_308_p2(32 downto 32);
    ret_V_fu_308_p2 <= std_logic_vector(signed(sext_ln813_fu_289_p1) + signed(sext_ln1347_fu_300_p1));
    rhs_fu_293_p3 <= (mul_ln1347_reg_631 & ap_const_lv8_0);
    select_ln346_105_fu_562_p3 <= 
        ap_const_lv8_7F when (overflow_19_fu_532_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln346_fu_354_p3 <= 
        ap_const_lv32_7FFFFFFF when (overflow_fu_342_p2(0) = '1') else 
        ap_const_lv32_80000000;
        sext_ln1347_185_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_fu_293_p3),32));

        sext_ln1347_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_fu_293_p3),33));

        sext_ln141_cast_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln141),32));

    sext_ln813_fu_289_p0 <= lhs_fu_124;
        sext_ln813_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln813_fu_289_p0),33));

    tmp_258_fu_480_p3 <= acc_V_fu_362_p3(20 downto 20);
    tmp_fu_396_p3 <= acc_V_fu_362_p3(11 downto 11);
    tmp_i_52_fu_450_p4 <= acc_V_fu_362_p3(31 downto 20);
    tmp_i_fu_434_p4 <= acc_V_fu_362_p3(31 downto 21);
    trunc_ln150_fu_233_p1 <= ap_sig_allocacmp_i(4 - 1 downto 0);
    underflow_fu_556_p2 <= (xor_ln896_2_fu_550_p2 and p_Result_38_fu_370_p3);
    xor_ln302_fu_348_p2 <= (p_Result_s_fu_314_p3 xor p_Result_37_fu_328_p3);
    xor_ln890_fu_488_p2 <= (tmp_258_fu_480_p3 xor ap_const_lv1_1);
    xor_ln895_123_fu_514_p2 <= (deleted_zeros_fu_472_p3 xor ap_const_lv1_1);
    xor_ln895_124_fu_526_p2 <= (p_Result_38_fu_370_p3 xor ap_const_lv1_1);
    xor_ln895_fu_336_p2 <= (p_Result_s_fu_314_p3 xor ap_const_lv1_1);
    xor_ln896_1_fu_538_p2 <= (deleted_ones_fu_500_p3 xor ap_const_lv1_1);
    xor_ln896_2_fu_550_p2 <= (or_ln896_fu_544_p2 xor and_ln891_fu_508_p2);
    xor_ln896_fu_422_p2 <= (p_Result_40_fu_414_p3 xor ap_const_lv1_1);
    zext_ln152_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln152_fu_245_p2),64));
    zext_ln153_fu_256_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_fu_237_p3),64));
    zext_ln377_fu_404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_396_p3),8));
end behav;
