-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vgg_accelerator is
generic (
    C_S_AXI_CTRL_BUS_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CTRL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_CTRL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    INPUT_STREAM_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    INPUT_STREAM_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TVALID : IN STD_LOGIC;
    INPUT_STREAM_TREADY : OUT STD_LOGIC;
    OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
    OUTPUT_STREAM_TREADY : IN STD_LOGIC );
end;


architecture behav of vgg_accelerator is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "vgg_accelerator_vgg_accelerator,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu5eg-sfvc784-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.115000,HLS_SYN_LAT=329008,HLS_SYN_TPT=325637,HLS_SYN_MEM=39,HLS_SYN_DSP=0,HLS_SYN_FF=15135,HLS_SYN_LUT=40994,HLS_VERSION=2022_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal input_adapter_U0_ap_start : STD_LOGIC;
    signal input_adapter_U0_ap_done : STD_LOGIC;
    signal input_adapter_U0_ap_continue : STD_LOGIC;
    signal input_adapter_U0_ap_idle : STD_LOGIC;
    signal input_adapter_U0_ap_ready : STD_LOGIC;
    signal input_adapter_U0_s_input_din : STD_LOGIC_VECTOR (7 downto 0);
    signal input_adapter_U0_s_input_write : STD_LOGIC;
    signal input_adapter_U0_start_out : STD_LOGIC;
    signal input_adapter_U0_start_write : STD_LOGIC;
    signal input_adapter_U0_INPUT_STREAM_TREADY : STD_LOGIC;
    signal layer_block_1_16_32_U0_ap_start : STD_LOGIC;
    signal layer_block_1_16_32_U0_ap_done : STD_LOGIC;
    signal layer_block_1_16_32_U0_ap_continue : STD_LOGIC;
    signal layer_block_1_16_32_U0_ap_idle : STD_LOGIC;
    signal layer_block_1_16_32_U0_ap_ready : STD_LOGIC;
    signal layer_block_1_16_32_U0_start_out : STD_LOGIC;
    signal layer_block_1_16_32_U0_start_write : STD_LOGIC;
    signal layer_block_1_16_32_U0_s_input_read : STD_LOGIC;
    signal layer_block_1_16_32_U0_s_conv1_din : STD_LOGIC_VECTOR (7 downto 0);
    signal layer_block_1_16_32_U0_s_conv1_write : STD_LOGIC;
    signal max_pool_16_32_U0_ap_start : STD_LOGIC;
    signal max_pool_16_32_U0_ap_done : STD_LOGIC;
    signal max_pool_16_32_U0_ap_continue : STD_LOGIC;
    signal max_pool_16_32_U0_ap_idle : STD_LOGIC;
    signal max_pool_16_32_U0_ap_ready : STD_LOGIC;
    signal max_pool_16_32_U0_s_conv1_read : STD_LOGIC;
    signal max_pool_16_32_U0_s_pool1_din : STD_LOGIC_VECTOR (7 downto 0);
    signal max_pool_16_32_U0_s_pool1_write : STD_LOGIC;
    signal max_pool_16_32_U0_start_out : STD_LOGIC;
    signal max_pool_16_32_U0_start_write : STD_LOGIC;
    signal layer_block_16_32_16_U0_ap_start : STD_LOGIC;
    signal layer_block_16_32_16_U0_ap_done : STD_LOGIC;
    signal layer_block_16_32_16_U0_ap_continue : STD_LOGIC;
    signal layer_block_16_32_16_U0_ap_idle : STD_LOGIC;
    signal layer_block_16_32_16_U0_ap_ready : STD_LOGIC;
    signal layer_block_16_32_16_U0_start_out : STD_LOGIC;
    signal layer_block_16_32_16_U0_start_write : STD_LOGIC;
    signal layer_block_16_32_16_U0_s_conv2_din : STD_LOGIC_VECTOR (7 downto 0);
    signal layer_block_16_32_16_U0_s_conv2_write : STD_LOGIC;
    signal layer_block_16_32_16_U0_s_pool1_read : STD_LOGIC;
    signal max_pool_32_16_U0_ap_start : STD_LOGIC;
    signal max_pool_32_16_U0_ap_done : STD_LOGIC;
    signal max_pool_32_16_U0_ap_continue : STD_LOGIC;
    signal max_pool_32_16_U0_ap_idle : STD_LOGIC;
    signal max_pool_32_16_U0_ap_ready : STD_LOGIC;
    signal max_pool_32_16_U0_s_conv2_read : STD_LOGIC;
    signal max_pool_32_16_U0_s_pool2_din : STD_LOGIC_VECTOR (7 downto 0);
    signal max_pool_32_16_U0_s_pool2_write : STD_LOGIC;
    signal max_pool_32_16_U0_start_out : STD_LOGIC;
    signal max_pool_32_16_U0_start_write : STD_LOGIC;
    signal layer_block_32_64_8_U0_ap_start : STD_LOGIC;
    signal layer_block_32_64_8_U0_ap_done : STD_LOGIC;
    signal layer_block_32_64_8_U0_ap_continue : STD_LOGIC;
    signal layer_block_32_64_8_U0_ap_idle : STD_LOGIC;
    signal layer_block_32_64_8_U0_ap_ready : STD_LOGIC;
    signal layer_block_32_64_8_U0_start_out : STD_LOGIC;
    signal layer_block_32_64_8_U0_start_write : STD_LOGIC;
    signal layer_block_32_64_8_U0_s_conv3_din : STD_LOGIC_VECTOR (7 downto 0);
    signal layer_block_32_64_8_U0_s_conv3_write : STD_LOGIC;
    signal layer_block_32_64_8_U0_s_pool2_read : STD_LOGIC;
    signal max_pool_64_8_U0_ap_start : STD_LOGIC;
    signal max_pool_64_8_U0_ap_done : STD_LOGIC;
    signal max_pool_64_8_U0_ap_continue : STD_LOGIC;
    signal max_pool_64_8_U0_ap_idle : STD_LOGIC;
    signal max_pool_64_8_U0_ap_ready : STD_LOGIC;
    signal max_pool_64_8_U0_s_conv3_read : STD_LOGIC;
    signal max_pool_64_8_U0_s_pool3_din : STD_LOGIC_VECTOR (7 downto 0);
    signal max_pool_64_8_U0_s_pool3_write : STD_LOGIC;
    signal max_pool_64_8_U0_start_out : STD_LOGIC;
    signal max_pool_64_8_U0_start_write : STD_LOGIC;
    signal dense_layer_U0_ap_start : STD_LOGIC;
    signal dense_layer_U0_ap_done : STD_LOGIC;
    signal dense_layer_U0_ap_continue : STD_LOGIC;
    signal dense_layer_U0_ap_idle : STD_LOGIC;
    signal dense_layer_U0_ap_ready : STD_LOGIC;
    signal dense_layer_U0_OUTPUT_STREAM_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_layer_U0_OUTPUT_STREAM_TVALID : STD_LOGIC;
    signal dense_layer_U0_OUTPUT_STREAM_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal dense_layer_U0_OUTPUT_STREAM_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal dense_layer_U0_OUTPUT_STREAM_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal dense_layer_U0_s_pool3_read : STD_LOGIC;
    signal s_input_full_n : STD_LOGIC;
    signal s_input_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal s_input_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal s_input_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal s_input_empty_n : STD_LOGIC;
    signal s_conv1_full_n : STD_LOGIC;
    signal s_conv1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal s_conv1_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal s_conv1_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal s_conv1_empty_n : STD_LOGIC;
    signal s_pool1_full_n : STD_LOGIC;
    signal s_pool1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal s_pool1_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal s_pool1_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal s_pool1_empty_n : STD_LOGIC;
    signal s_conv2_full_n : STD_LOGIC;
    signal s_conv2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal s_conv2_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal s_conv2_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal s_conv2_empty_n : STD_LOGIC;
    signal s_pool2_full_n : STD_LOGIC;
    signal s_pool2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal s_pool2_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal s_pool2_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal s_pool2_empty_n : STD_LOGIC;
    signal s_conv3_full_n : STD_LOGIC;
    signal s_conv3_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal s_conv3_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal s_conv3_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal s_conv3_empty_n : STD_LOGIC;
    signal s_pool3_full_n : STD_LOGIC;
    signal s_pool3_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal s_pool3_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal s_pool3_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal s_pool3_empty_n : STD_LOGIC;
    signal start_for_layer_block_1_16_32_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_layer_block_1_16_32_U0_full_n : STD_LOGIC;
    signal start_for_layer_block_1_16_32_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_layer_block_1_16_32_U0_empty_n : STD_LOGIC;
    signal start_for_max_pool_16_32_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_max_pool_16_32_U0_full_n : STD_LOGIC;
    signal start_for_max_pool_16_32_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_max_pool_16_32_U0_empty_n : STD_LOGIC;
    signal start_for_layer_block_16_32_16_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_layer_block_16_32_16_U0_full_n : STD_LOGIC;
    signal start_for_layer_block_16_32_16_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_layer_block_16_32_16_U0_empty_n : STD_LOGIC;
    signal start_for_max_pool_32_16_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_max_pool_32_16_U0_full_n : STD_LOGIC;
    signal start_for_max_pool_32_16_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_max_pool_32_16_U0_empty_n : STD_LOGIC;
    signal start_for_layer_block_32_64_8_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_layer_block_32_64_8_U0_full_n : STD_LOGIC;
    signal start_for_layer_block_32_64_8_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_layer_block_32_64_8_U0_empty_n : STD_LOGIC;
    signal start_for_max_pool_64_8_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_max_pool_64_8_U0_full_n : STD_LOGIC;
    signal start_for_max_pool_64_8_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_max_pool_64_8_U0_empty_n : STD_LOGIC;
    signal start_for_dense_layer_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_layer_U0_full_n : STD_LOGIC;
    signal start_for_dense_layer_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_layer_U0_empty_n : STD_LOGIC;

    component vgg_accelerator_input_adapter IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        INPUT_STREAM_TVALID : IN STD_LOGIC;
        s_input_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        s_input_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        s_input_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        s_input_full_n : IN STD_LOGIC;
        s_input_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        INPUT_STREAM_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        INPUT_STREAM_TREADY : OUT STD_LOGIC;
        INPUT_STREAM_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        INPUT_STREAM_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        INPUT_STREAM_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component vgg_accelerator_layer_block_1_16_32_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        s_input_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        s_input_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        s_input_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        s_input_empty_n : IN STD_LOGIC;
        s_input_read : OUT STD_LOGIC;
        s_conv1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        s_conv1_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        s_conv1_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        s_conv1_full_n : IN STD_LOGIC;
        s_conv1_write : OUT STD_LOGIC );
    end component;


    component vgg_accelerator_max_pool_16_32_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_conv1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        s_conv1_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        s_conv1_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        s_conv1_empty_n : IN STD_LOGIC;
        s_conv1_read : OUT STD_LOGIC;
        s_pool1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        s_pool1_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        s_pool1_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        s_pool1_full_n : IN STD_LOGIC;
        s_pool1_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component vgg_accelerator_layer_block_16_32_16_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        s_conv2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        s_conv2_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_conv2_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_conv2_full_n : IN STD_LOGIC;
        s_conv2_write : OUT STD_LOGIC;
        s_pool1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        s_pool1_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        s_pool1_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        s_pool1_empty_n : IN STD_LOGIC;
        s_pool1_read : OUT STD_LOGIC );
    end component;


    component vgg_accelerator_max_pool_32_16_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_conv2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        s_conv2_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_conv2_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_conv2_empty_n : IN STD_LOGIC;
        s_conv2_read : OUT STD_LOGIC;
        s_pool2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        s_pool2_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_pool2_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_pool2_full_n : IN STD_LOGIC;
        s_pool2_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component vgg_accelerator_layer_block_32_64_8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        s_conv3_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        s_conv3_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_conv3_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_conv3_full_n : IN STD_LOGIC;
        s_conv3_write : OUT STD_LOGIC;
        s_pool2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        s_pool2_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_pool2_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_pool2_empty_n : IN STD_LOGIC;
        s_pool2_read : OUT STD_LOGIC );
    end component;


    component vgg_accelerator_max_pool_64_8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_conv3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        s_conv3_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_conv3_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_conv3_empty_n : IN STD_LOGIC;
        s_conv3_read : OUT STD_LOGIC;
        s_pool3_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        s_pool3_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_pool3_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_pool3_full_n : IN STD_LOGIC;
        s_pool3_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component vgg_accelerator_dense_layer IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
        OUTPUT_STREAM_TREADY : IN STD_LOGIC;
        OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        s_pool3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        s_pool3_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        s_pool3_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        s_pool3_empty_n : IN STD_LOGIC;
        s_pool3_read : OUT STD_LOGIC );
    end component;


    component vgg_accelerator_fifo_w8_d128_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component vgg_accelerator_fifo_w8_d64_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component vgg_accelerator_start_for_layer_block_1_16_32_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component vgg_accelerator_start_for_max_pool_16_32_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component vgg_accelerator_start_for_layer_block_16_32_16_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component vgg_accelerator_start_for_max_pool_32_16_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component vgg_accelerator_start_for_layer_block_32_64_8_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component vgg_accelerator_start_for_max_pool_64_8_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component vgg_accelerator_start_for_dense_layer_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component vgg_accelerator_CTRL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    CTRL_BUS_s_axi_U : component vgg_accelerator_CTRL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_BUS_AWVALID,
        AWREADY => s_axi_CTRL_BUS_AWREADY,
        AWADDR => s_axi_CTRL_BUS_AWADDR,
        WVALID => s_axi_CTRL_BUS_WVALID,
        WREADY => s_axi_CTRL_BUS_WREADY,
        WDATA => s_axi_CTRL_BUS_WDATA,
        WSTRB => s_axi_CTRL_BUS_WSTRB,
        ARVALID => s_axi_CTRL_BUS_ARVALID,
        ARREADY => s_axi_CTRL_BUS_ARREADY,
        ARADDR => s_axi_CTRL_BUS_ARADDR,
        RVALID => s_axi_CTRL_BUS_RVALID,
        RREADY => s_axi_CTRL_BUS_RREADY,
        RDATA => s_axi_CTRL_BUS_RDATA,
        RRESP => s_axi_CTRL_BUS_RRESP,
        BVALID => s_axi_CTRL_BUS_BVALID,
        BREADY => s_axi_CTRL_BUS_BREADY,
        BRESP => s_axi_CTRL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    input_adapter_U0 : component vgg_accelerator_input_adapter
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => input_adapter_U0_ap_start,
        start_full_n => start_for_layer_block_1_16_32_U0_full_n,
        ap_done => input_adapter_U0_ap_done,
        ap_continue => input_adapter_U0_ap_continue,
        ap_idle => input_adapter_U0_ap_idle,
        ap_ready => input_adapter_U0_ap_ready,
        INPUT_STREAM_TVALID => INPUT_STREAM_TVALID,
        s_input_din => input_adapter_U0_s_input_din,
        s_input_num_data_valid => s_input_num_data_valid,
        s_input_fifo_cap => s_input_fifo_cap,
        s_input_full_n => s_input_full_n,
        s_input_write => input_adapter_U0_s_input_write,
        start_out => input_adapter_U0_start_out,
        start_write => input_adapter_U0_start_write,
        INPUT_STREAM_TDATA => INPUT_STREAM_TDATA,
        INPUT_STREAM_TREADY => input_adapter_U0_INPUT_STREAM_TREADY,
        INPUT_STREAM_TKEEP => INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB => INPUT_STREAM_TSTRB,
        INPUT_STREAM_TLAST => INPUT_STREAM_TLAST);

    layer_block_1_16_32_U0 : component vgg_accelerator_layer_block_1_16_32_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => layer_block_1_16_32_U0_ap_start,
        start_full_n => start_for_max_pool_16_32_U0_full_n,
        ap_done => layer_block_1_16_32_U0_ap_done,
        ap_continue => layer_block_1_16_32_U0_ap_continue,
        ap_idle => layer_block_1_16_32_U0_ap_idle,
        ap_ready => layer_block_1_16_32_U0_ap_ready,
        start_out => layer_block_1_16_32_U0_start_out,
        start_write => layer_block_1_16_32_U0_start_write,
        s_input_dout => s_input_dout,
        s_input_num_data_valid => s_input_num_data_valid,
        s_input_fifo_cap => s_input_fifo_cap,
        s_input_empty_n => s_input_empty_n,
        s_input_read => layer_block_1_16_32_U0_s_input_read,
        s_conv1_din => layer_block_1_16_32_U0_s_conv1_din,
        s_conv1_num_data_valid => s_conv1_num_data_valid,
        s_conv1_fifo_cap => s_conv1_fifo_cap,
        s_conv1_full_n => s_conv1_full_n,
        s_conv1_write => layer_block_1_16_32_U0_s_conv1_write);

    max_pool_16_32_U0 : component vgg_accelerator_max_pool_16_32_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => max_pool_16_32_U0_ap_start,
        start_full_n => start_for_layer_block_16_32_16_U0_full_n,
        ap_done => max_pool_16_32_U0_ap_done,
        ap_continue => max_pool_16_32_U0_ap_continue,
        ap_idle => max_pool_16_32_U0_ap_idle,
        ap_ready => max_pool_16_32_U0_ap_ready,
        s_conv1_dout => s_conv1_dout,
        s_conv1_num_data_valid => s_conv1_num_data_valid,
        s_conv1_fifo_cap => s_conv1_fifo_cap,
        s_conv1_empty_n => s_conv1_empty_n,
        s_conv1_read => max_pool_16_32_U0_s_conv1_read,
        s_pool1_din => max_pool_16_32_U0_s_pool1_din,
        s_pool1_num_data_valid => s_pool1_num_data_valid,
        s_pool1_fifo_cap => s_pool1_fifo_cap,
        s_pool1_full_n => s_pool1_full_n,
        s_pool1_write => max_pool_16_32_U0_s_pool1_write,
        start_out => max_pool_16_32_U0_start_out,
        start_write => max_pool_16_32_U0_start_write);

    layer_block_16_32_16_U0 : component vgg_accelerator_layer_block_16_32_16_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => layer_block_16_32_16_U0_ap_start,
        start_full_n => start_for_max_pool_32_16_U0_full_n,
        ap_done => layer_block_16_32_16_U0_ap_done,
        ap_continue => layer_block_16_32_16_U0_ap_continue,
        ap_idle => layer_block_16_32_16_U0_ap_idle,
        ap_ready => layer_block_16_32_16_U0_ap_ready,
        start_out => layer_block_16_32_16_U0_start_out,
        start_write => layer_block_16_32_16_U0_start_write,
        s_conv2_din => layer_block_16_32_16_U0_s_conv2_din,
        s_conv2_num_data_valid => s_conv2_num_data_valid,
        s_conv2_fifo_cap => s_conv2_fifo_cap,
        s_conv2_full_n => s_conv2_full_n,
        s_conv2_write => layer_block_16_32_16_U0_s_conv2_write,
        s_pool1_dout => s_pool1_dout,
        s_pool1_num_data_valid => s_pool1_num_data_valid,
        s_pool1_fifo_cap => s_pool1_fifo_cap,
        s_pool1_empty_n => s_pool1_empty_n,
        s_pool1_read => layer_block_16_32_16_U0_s_pool1_read);

    max_pool_32_16_U0 : component vgg_accelerator_max_pool_32_16_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => max_pool_32_16_U0_ap_start,
        start_full_n => start_for_layer_block_32_64_8_U0_full_n,
        ap_done => max_pool_32_16_U0_ap_done,
        ap_continue => max_pool_32_16_U0_ap_continue,
        ap_idle => max_pool_32_16_U0_ap_idle,
        ap_ready => max_pool_32_16_U0_ap_ready,
        s_conv2_dout => s_conv2_dout,
        s_conv2_num_data_valid => s_conv2_num_data_valid,
        s_conv2_fifo_cap => s_conv2_fifo_cap,
        s_conv2_empty_n => s_conv2_empty_n,
        s_conv2_read => max_pool_32_16_U0_s_conv2_read,
        s_pool2_din => max_pool_32_16_U0_s_pool2_din,
        s_pool2_num_data_valid => s_pool2_num_data_valid,
        s_pool2_fifo_cap => s_pool2_fifo_cap,
        s_pool2_full_n => s_pool2_full_n,
        s_pool2_write => max_pool_32_16_U0_s_pool2_write,
        start_out => max_pool_32_16_U0_start_out,
        start_write => max_pool_32_16_U0_start_write);

    layer_block_32_64_8_U0 : component vgg_accelerator_layer_block_32_64_8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => layer_block_32_64_8_U0_ap_start,
        start_full_n => start_for_max_pool_64_8_U0_full_n,
        ap_done => layer_block_32_64_8_U0_ap_done,
        ap_continue => layer_block_32_64_8_U0_ap_continue,
        ap_idle => layer_block_32_64_8_U0_ap_idle,
        ap_ready => layer_block_32_64_8_U0_ap_ready,
        start_out => layer_block_32_64_8_U0_start_out,
        start_write => layer_block_32_64_8_U0_start_write,
        s_conv3_din => layer_block_32_64_8_U0_s_conv3_din,
        s_conv3_num_data_valid => s_conv3_num_data_valid,
        s_conv3_fifo_cap => s_conv3_fifo_cap,
        s_conv3_full_n => s_conv3_full_n,
        s_conv3_write => layer_block_32_64_8_U0_s_conv3_write,
        s_pool2_dout => s_pool2_dout,
        s_pool2_num_data_valid => s_pool2_num_data_valid,
        s_pool2_fifo_cap => s_pool2_fifo_cap,
        s_pool2_empty_n => s_pool2_empty_n,
        s_pool2_read => layer_block_32_64_8_U0_s_pool2_read);

    max_pool_64_8_U0 : component vgg_accelerator_max_pool_64_8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => max_pool_64_8_U0_ap_start,
        start_full_n => start_for_dense_layer_U0_full_n,
        ap_done => max_pool_64_8_U0_ap_done,
        ap_continue => max_pool_64_8_U0_ap_continue,
        ap_idle => max_pool_64_8_U0_ap_idle,
        ap_ready => max_pool_64_8_U0_ap_ready,
        s_conv3_dout => s_conv3_dout,
        s_conv3_num_data_valid => s_conv3_num_data_valid,
        s_conv3_fifo_cap => s_conv3_fifo_cap,
        s_conv3_empty_n => s_conv3_empty_n,
        s_conv3_read => max_pool_64_8_U0_s_conv3_read,
        s_pool3_din => max_pool_64_8_U0_s_pool3_din,
        s_pool3_num_data_valid => s_pool3_num_data_valid,
        s_pool3_fifo_cap => s_pool3_fifo_cap,
        s_pool3_full_n => s_pool3_full_n,
        s_pool3_write => max_pool_64_8_U0_s_pool3_write,
        start_out => max_pool_64_8_U0_start_out,
        start_write => max_pool_64_8_U0_start_write);

    dense_layer_U0 : component vgg_accelerator_dense_layer
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dense_layer_U0_ap_start,
        ap_done => dense_layer_U0_ap_done,
        ap_continue => dense_layer_U0_ap_continue,
        ap_idle => dense_layer_U0_ap_idle,
        ap_ready => dense_layer_U0_ap_ready,
        OUTPUT_STREAM_TDATA => dense_layer_U0_OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID => dense_layer_U0_OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY => OUTPUT_STREAM_TREADY,
        OUTPUT_STREAM_TKEEP => dense_layer_U0_OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB => dense_layer_U0_OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TLAST => dense_layer_U0_OUTPUT_STREAM_TLAST,
        s_pool3_dout => s_pool3_dout,
        s_pool3_num_data_valid => s_pool3_num_data_valid,
        s_pool3_fifo_cap => s_pool3_fifo_cap,
        s_pool3_empty_n => s_pool3_empty_n,
        s_pool3_read => dense_layer_U0_s_pool3_read);

    s_input_U : component vgg_accelerator_fifo_w8_d128_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => input_adapter_U0_s_input_din,
        if_full_n => s_input_full_n,
        if_write => input_adapter_U0_s_input_write,
        if_dout => s_input_dout,
        if_num_data_valid => s_input_num_data_valid,
        if_fifo_cap => s_input_fifo_cap,
        if_empty_n => s_input_empty_n,
        if_read => layer_block_1_16_32_U0_s_input_read);

    s_conv1_U : component vgg_accelerator_fifo_w8_d128_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => layer_block_1_16_32_U0_s_conv1_din,
        if_full_n => s_conv1_full_n,
        if_write => layer_block_1_16_32_U0_s_conv1_write,
        if_dout => s_conv1_dout,
        if_num_data_valid => s_conv1_num_data_valid,
        if_fifo_cap => s_conv1_fifo_cap,
        if_empty_n => s_conv1_empty_n,
        if_read => max_pool_16_32_U0_s_conv1_read);

    s_pool1_U : component vgg_accelerator_fifo_w8_d128_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => max_pool_16_32_U0_s_pool1_din,
        if_full_n => s_pool1_full_n,
        if_write => max_pool_16_32_U0_s_pool1_write,
        if_dout => s_pool1_dout,
        if_num_data_valid => s_pool1_num_data_valid,
        if_fifo_cap => s_pool1_fifo_cap,
        if_empty_n => s_pool1_empty_n,
        if_read => layer_block_16_32_16_U0_s_pool1_read);

    s_conv2_U : component vgg_accelerator_fifo_w8_d64_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => layer_block_16_32_16_U0_s_conv2_din,
        if_full_n => s_conv2_full_n,
        if_write => layer_block_16_32_16_U0_s_conv2_write,
        if_dout => s_conv2_dout,
        if_num_data_valid => s_conv2_num_data_valid,
        if_fifo_cap => s_conv2_fifo_cap,
        if_empty_n => s_conv2_empty_n,
        if_read => max_pool_32_16_U0_s_conv2_read);

    s_pool2_U : component vgg_accelerator_fifo_w8_d64_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => max_pool_32_16_U0_s_pool2_din,
        if_full_n => s_pool2_full_n,
        if_write => max_pool_32_16_U0_s_pool2_write,
        if_dout => s_pool2_dout,
        if_num_data_valid => s_pool2_num_data_valid,
        if_fifo_cap => s_pool2_fifo_cap,
        if_empty_n => s_pool2_empty_n,
        if_read => layer_block_32_64_8_U0_s_pool2_read);

    s_conv3_U : component vgg_accelerator_fifo_w8_d64_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => layer_block_32_64_8_U0_s_conv3_din,
        if_full_n => s_conv3_full_n,
        if_write => layer_block_32_64_8_U0_s_conv3_write,
        if_dout => s_conv3_dout,
        if_num_data_valid => s_conv3_num_data_valid,
        if_fifo_cap => s_conv3_fifo_cap,
        if_empty_n => s_conv3_empty_n,
        if_read => max_pool_64_8_U0_s_conv3_read);

    s_pool3_U : component vgg_accelerator_fifo_w8_d64_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => max_pool_64_8_U0_s_pool3_din,
        if_full_n => s_pool3_full_n,
        if_write => max_pool_64_8_U0_s_pool3_write,
        if_dout => s_pool3_dout,
        if_num_data_valid => s_pool3_num_data_valid,
        if_fifo_cap => s_pool3_fifo_cap,
        if_empty_n => s_pool3_empty_n,
        if_read => dense_layer_U0_s_pool3_read);

    start_for_layer_block_1_16_32_U0_U : component vgg_accelerator_start_for_layer_block_1_16_32_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_layer_block_1_16_32_U0_din,
        if_full_n => start_for_layer_block_1_16_32_U0_full_n,
        if_write => input_adapter_U0_start_write,
        if_dout => start_for_layer_block_1_16_32_U0_dout,
        if_empty_n => start_for_layer_block_1_16_32_U0_empty_n,
        if_read => layer_block_1_16_32_U0_ap_ready);

    start_for_max_pool_16_32_U0_U : component vgg_accelerator_start_for_max_pool_16_32_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_max_pool_16_32_U0_din,
        if_full_n => start_for_max_pool_16_32_U0_full_n,
        if_write => layer_block_1_16_32_U0_start_write,
        if_dout => start_for_max_pool_16_32_U0_dout,
        if_empty_n => start_for_max_pool_16_32_U0_empty_n,
        if_read => max_pool_16_32_U0_ap_ready);

    start_for_layer_block_16_32_16_U0_U : component vgg_accelerator_start_for_layer_block_16_32_16_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_layer_block_16_32_16_U0_din,
        if_full_n => start_for_layer_block_16_32_16_U0_full_n,
        if_write => max_pool_16_32_U0_start_write,
        if_dout => start_for_layer_block_16_32_16_U0_dout,
        if_empty_n => start_for_layer_block_16_32_16_U0_empty_n,
        if_read => layer_block_16_32_16_U0_ap_ready);

    start_for_max_pool_32_16_U0_U : component vgg_accelerator_start_for_max_pool_32_16_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_max_pool_32_16_U0_din,
        if_full_n => start_for_max_pool_32_16_U0_full_n,
        if_write => layer_block_16_32_16_U0_start_write,
        if_dout => start_for_max_pool_32_16_U0_dout,
        if_empty_n => start_for_max_pool_32_16_U0_empty_n,
        if_read => max_pool_32_16_U0_ap_ready);

    start_for_layer_block_32_64_8_U0_U : component vgg_accelerator_start_for_layer_block_32_64_8_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_layer_block_32_64_8_U0_din,
        if_full_n => start_for_layer_block_32_64_8_U0_full_n,
        if_write => max_pool_32_16_U0_start_write,
        if_dout => start_for_layer_block_32_64_8_U0_dout,
        if_empty_n => start_for_layer_block_32_64_8_U0_empty_n,
        if_read => layer_block_32_64_8_U0_ap_ready);

    start_for_max_pool_64_8_U0_U : component vgg_accelerator_start_for_max_pool_64_8_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_max_pool_64_8_U0_din,
        if_full_n => start_for_max_pool_64_8_U0_full_n,
        if_write => layer_block_32_64_8_U0_start_write,
        if_dout => start_for_max_pool_64_8_U0_dout,
        if_empty_n => start_for_max_pool_64_8_U0_empty_n,
        if_read => max_pool_64_8_U0_ap_ready);

    start_for_dense_layer_U0_U : component vgg_accelerator_start_for_dense_layer_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dense_layer_U0_din,
        if_full_n => start_for_dense_layer_U0_full_n,
        if_write => max_pool_64_8_U0_start_write,
        if_dout => start_for_dense_layer_U0_dout,
        if_empty_n => start_for_dense_layer_U0_empty_n,
        if_read => dense_layer_U0_ap_ready);




    INPUT_STREAM_TREADY <= input_adapter_U0_INPUT_STREAM_TREADY;
    OUTPUT_STREAM_TDATA <= dense_layer_U0_OUTPUT_STREAM_TDATA;
    OUTPUT_STREAM_TKEEP <= dense_layer_U0_OUTPUT_STREAM_TKEEP;
    OUTPUT_STREAM_TLAST <= dense_layer_U0_OUTPUT_STREAM_TLAST;
    OUTPUT_STREAM_TSTRB <= dense_layer_U0_OUTPUT_STREAM_TSTRB;
    OUTPUT_STREAM_TVALID <= dense_layer_U0_OUTPUT_STREAM_TVALID;
    ap_done <= dense_layer_U0_ap_done;
    ap_idle <= (max_pool_64_8_U0_ap_idle and max_pool_32_16_U0_ap_idle and max_pool_16_32_U0_ap_idle and layer_block_32_64_8_U0_ap_idle and layer_block_1_16_32_U0_ap_idle and layer_block_16_32_16_U0_ap_idle and input_adapter_U0_ap_idle and dense_layer_U0_ap_idle);
    ap_ready <= input_adapter_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    dense_layer_U0_ap_continue <= ap_const_logic_1;
    dense_layer_U0_ap_start <= start_for_dense_layer_U0_empty_n;
    input_adapter_U0_ap_continue <= ap_const_logic_1;
    input_adapter_U0_ap_start <= ap_start;
    layer_block_16_32_16_U0_ap_continue <= ap_const_logic_1;
    layer_block_16_32_16_U0_ap_start <= start_for_layer_block_16_32_16_U0_empty_n;
    layer_block_1_16_32_U0_ap_continue <= ap_const_logic_1;
    layer_block_1_16_32_U0_ap_start <= start_for_layer_block_1_16_32_U0_empty_n;
    layer_block_32_64_8_U0_ap_continue <= ap_const_logic_1;
    layer_block_32_64_8_U0_ap_start <= start_for_layer_block_32_64_8_U0_empty_n;
    max_pool_16_32_U0_ap_continue <= ap_const_logic_1;
    max_pool_16_32_U0_ap_start <= start_for_max_pool_16_32_U0_empty_n;
    max_pool_32_16_U0_ap_continue <= ap_const_logic_1;
    max_pool_32_16_U0_ap_start <= start_for_max_pool_32_16_U0_empty_n;
    max_pool_64_8_U0_ap_continue <= ap_const_logic_1;
    max_pool_64_8_U0_ap_start <= start_for_max_pool_64_8_U0_empty_n;
    start_for_dense_layer_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_layer_block_16_32_16_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_layer_block_1_16_32_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_layer_block_32_64_8_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_max_pool_16_32_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_max_pool_32_16_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_max_pool_64_8_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
