// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module vgg_accelerator_layer_block_1_16_32_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_input_dout,
        s_input_num_data_valid,
        s_input_fifo_cap,
        s_input_empty_n,
        s_input_read,
        s_conv1_din,
        s_conv1_num_data_valid,
        s_conv1_fifo_cap,
        s_conv1_full_n,
        s_conv1_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] s_input_dout;
input  [7:0] s_input_num_data_valid;
input  [7:0] s_input_fifo_cap;
input   s_input_empty_n;
output   s_input_read;
output  [7:0] s_conv1_din;
input  [7:0] s_conv1_num_data_valid;
input  [7:0] s_conv1_fifo_cap;
input   s_conv1_full_n;
output   s_conv1_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg s_input_read;
reg s_conv1_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [4:0] void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0;
reg    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0;
reg    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0;
reg   [7:0] void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0;
wire   [7:0] void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_q0;
reg   [4:0] void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0;
reg    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0;
reg    void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0;
reg   [7:0] void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0;
wire   [7:0] void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_q0;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_done;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_idle;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_ready;
wire   [4:0] grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0;
wire   [7:0] grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0;
wire   [4:0] grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0;
wire   [7:0] grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_idle;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_ready;
wire   [7:0] grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_din;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_write;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_input_read;
wire   [4:0] grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0;
wire   [7:0] grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0;
wire   [4:0] grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0;
wire    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0;
wire   [7:0] grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0;
reg    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg;
reg    ap_block_state1_ignore_call8;
wire    ap_CS_fsm_state2;
reg    grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg = 1'b0;
#0 grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg = 1'b0;
end

vgg_accelerator_layer_block_1_16_32_s_void_layer_block_stream_stream_signed_char_const_1_3_3_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0),
    .ce0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0),
    .we0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0),
    .d0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0),
    .q0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_q0)
);

vgg_accelerator_layer_block_1_16_32_s_void_layer_block_stream_stream_signed_char_const_1_3_3_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0),
    .ce0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0),
    .we0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0),
    .d0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0),
    .q0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_q0)
);

vgg_accelerator_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3 grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start),
    .ap_done(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_done),
    .ap_idle(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_idle),
    .ap_ready(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_ready),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0)
);

vgg_accelerator_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5 grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start),
    .ap_done(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done),
    .ap_idle(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_idle),
    .ap_ready(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_ready),
    .s_conv1_din(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_din),
    .s_conv1_num_data_valid(8'd0),
    .s_conv1_fifo_cap(8'd0),
    .s_conv1_full_n(s_conv1_full_n),
    .s_conv1_write(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_write),
    .s_input_dout(s_input_dout),
    .s_input_num_data_valid(8'd0),
    .s_input_fifo_cap(8'd0),
    .s_input_empty_n(s_input_empty_n),
    .s_input_read(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_input_read),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_q0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_q0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0(grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0),
    .void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_q0(void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg <= 1'b1;
        end else if ((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_ready == 1'b1)) begin
            grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_ready == 1'b1)) begin
            grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_conv1_write = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_write;
    end else begin
        s_conv1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_input_read = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_input_read;
    end else begin
        s_input_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0;
    end else begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0;
    end else begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0;
    end else begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0;
    end else begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0;
    end else begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0;
    end else begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0;
    end else begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0;
    end else begin
        void_layer_block_stream_stream_signed_char_const_1_3_3_signed_char_cons_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call8 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_32_2_VITIS_LOOP_33_3_fu_24_ap_start_reg;

assign grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_ap_start_reg;

assign s_conv1_din = grp_layer_block_1_16_32_Pipeline_VITIS_LOOP_36_4_VITIS_LOOP_37_5_fu_32_s_conv1_din;

assign start_out = real_start;

endmodule //vgg_accelerator_layer_block_1_16_32_s
