// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="vgg_accelerator_vgg_accelerator,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu5eg-sfvc784-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.115000,HLS_SYN_LAT=329008,HLS_SYN_TPT=325637,HLS_SYN_MEM=39,HLS_SYN_DSP=0,HLS_SYN_FF=15135,HLS_SYN_LUT=40994,HLS_VERSION=2022_2}" *)

module vgg_accelerator (
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TLAST,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TLAST,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY
);

parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [31:0] INPUT_STREAM_TDATA;
input  [3:0] INPUT_STREAM_TKEEP;
input  [3:0] INPUT_STREAM_TSTRB;
input  [0:0] INPUT_STREAM_TLAST;
output  [31:0] OUTPUT_STREAM_TDATA;
output  [3:0] OUTPUT_STREAM_TKEEP;
output  [3:0] OUTPUT_STREAM_TSTRB;
output  [0:0] OUTPUT_STREAM_TLAST;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;
output   OUTPUT_STREAM_TVALID;
input   OUTPUT_STREAM_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    input_adapter_U0_ap_start;
wire    input_adapter_U0_ap_done;
wire    input_adapter_U0_ap_continue;
wire    input_adapter_U0_ap_idle;
wire    input_adapter_U0_ap_ready;
wire   [7:0] input_adapter_U0_s_input_din;
wire    input_adapter_U0_s_input_write;
wire    input_adapter_U0_start_out;
wire    input_adapter_U0_start_write;
wire    input_adapter_U0_INPUT_STREAM_TREADY;
wire    layer_block_1_16_32_U0_ap_start;
wire    layer_block_1_16_32_U0_ap_done;
wire    layer_block_1_16_32_U0_ap_continue;
wire    layer_block_1_16_32_U0_ap_idle;
wire    layer_block_1_16_32_U0_ap_ready;
wire    layer_block_1_16_32_U0_start_out;
wire    layer_block_1_16_32_U0_start_write;
wire    layer_block_1_16_32_U0_s_input_read;
wire   [7:0] layer_block_1_16_32_U0_s_conv1_din;
wire    layer_block_1_16_32_U0_s_conv1_write;
wire    max_pool_16_32_U0_ap_start;
wire    max_pool_16_32_U0_ap_done;
wire    max_pool_16_32_U0_ap_continue;
wire    max_pool_16_32_U0_ap_idle;
wire    max_pool_16_32_U0_ap_ready;
wire    max_pool_16_32_U0_s_conv1_read;
wire   [7:0] max_pool_16_32_U0_s_pool1_din;
wire    max_pool_16_32_U0_s_pool1_write;
wire    max_pool_16_32_U0_start_out;
wire    max_pool_16_32_U0_start_write;
wire    layer_block_16_32_16_U0_ap_start;
wire    layer_block_16_32_16_U0_ap_done;
wire    layer_block_16_32_16_U0_ap_continue;
wire    layer_block_16_32_16_U0_ap_idle;
wire    layer_block_16_32_16_U0_ap_ready;
wire    layer_block_16_32_16_U0_start_out;
wire    layer_block_16_32_16_U0_start_write;
wire   [7:0] layer_block_16_32_16_U0_s_conv2_din;
wire    layer_block_16_32_16_U0_s_conv2_write;
wire    layer_block_16_32_16_U0_s_pool1_read;
wire    max_pool_32_16_U0_ap_start;
wire    max_pool_32_16_U0_ap_done;
wire    max_pool_32_16_U0_ap_continue;
wire    max_pool_32_16_U0_ap_idle;
wire    max_pool_32_16_U0_ap_ready;
wire    max_pool_32_16_U0_s_conv2_read;
wire   [7:0] max_pool_32_16_U0_s_pool2_din;
wire    max_pool_32_16_U0_s_pool2_write;
wire    max_pool_32_16_U0_start_out;
wire    max_pool_32_16_U0_start_write;
wire    layer_block_32_64_8_U0_ap_start;
wire    layer_block_32_64_8_U0_ap_done;
wire    layer_block_32_64_8_U0_ap_continue;
wire    layer_block_32_64_8_U0_ap_idle;
wire    layer_block_32_64_8_U0_ap_ready;
wire    layer_block_32_64_8_U0_start_out;
wire    layer_block_32_64_8_U0_start_write;
wire   [7:0] layer_block_32_64_8_U0_s_conv3_din;
wire    layer_block_32_64_8_U0_s_conv3_write;
wire    layer_block_32_64_8_U0_s_pool2_read;
wire    max_pool_64_8_U0_ap_start;
wire    max_pool_64_8_U0_ap_done;
wire    max_pool_64_8_U0_ap_continue;
wire    max_pool_64_8_U0_ap_idle;
wire    max_pool_64_8_U0_ap_ready;
wire    max_pool_64_8_U0_s_conv3_read;
wire   [7:0] max_pool_64_8_U0_s_pool3_din;
wire    max_pool_64_8_U0_s_pool3_write;
wire    max_pool_64_8_U0_start_out;
wire    max_pool_64_8_U0_start_write;
wire    dense_layer_U0_ap_start;
wire    dense_layer_U0_ap_done;
wire    dense_layer_U0_ap_continue;
wire    dense_layer_U0_ap_idle;
wire    dense_layer_U0_ap_ready;
wire   [31:0] dense_layer_U0_OUTPUT_STREAM_TDATA;
wire    dense_layer_U0_OUTPUT_STREAM_TVALID;
wire   [3:0] dense_layer_U0_OUTPUT_STREAM_TKEEP;
wire   [3:0] dense_layer_U0_OUTPUT_STREAM_TSTRB;
wire   [0:0] dense_layer_U0_OUTPUT_STREAM_TLAST;
wire    dense_layer_U0_s_pool3_read;
wire    s_input_full_n;
wire   [7:0] s_input_dout;
wire   [7:0] s_input_num_data_valid;
wire   [7:0] s_input_fifo_cap;
wire    s_input_empty_n;
wire    s_conv1_full_n;
wire   [7:0] s_conv1_dout;
wire   [7:0] s_conv1_num_data_valid;
wire   [7:0] s_conv1_fifo_cap;
wire    s_conv1_empty_n;
wire    s_pool1_full_n;
wire   [7:0] s_pool1_dout;
wire   [7:0] s_pool1_num_data_valid;
wire   [7:0] s_pool1_fifo_cap;
wire    s_pool1_empty_n;
wire    s_conv2_full_n;
wire   [7:0] s_conv2_dout;
wire   [6:0] s_conv2_num_data_valid;
wire   [6:0] s_conv2_fifo_cap;
wire    s_conv2_empty_n;
wire    s_pool2_full_n;
wire   [7:0] s_pool2_dout;
wire   [6:0] s_pool2_num_data_valid;
wire   [6:0] s_pool2_fifo_cap;
wire    s_pool2_empty_n;
wire    s_conv3_full_n;
wire   [7:0] s_conv3_dout;
wire   [6:0] s_conv3_num_data_valid;
wire   [6:0] s_conv3_fifo_cap;
wire    s_conv3_empty_n;
wire    s_pool3_full_n;
wire   [7:0] s_pool3_dout;
wire   [6:0] s_pool3_num_data_valid;
wire   [6:0] s_pool3_fifo_cap;
wire    s_pool3_empty_n;
wire   [0:0] start_for_layer_block_1_16_32_U0_din;
wire    start_for_layer_block_1_16_32_U0_full_n;
wire   [0:0] start_for_layer_block_1_16_32_U0_dout;
wire    start_for_layer_block_1_16_32_U0_empty_n;
wire   [0:0] start_for_max_pool_16_32_U0_din;
wire    start_for_max_pool_16_32_U0_full_n;
wire   [0:0] start_for_max_pool_16_32_U0_dout;
wire    start_for_max_pool_16_32_U0_empty_n;
wire   [0:0] start_for_layer_block_16_32_16_U0_din;
wire    start_for_layer_block_16_32_16_U0_full_n;
wire   [0:0] start_for_layer_block_16_32_16_U0_dout;
wire    start_for_layer_block_16_32_16_U0_empty_n;
wire   [0:0] start_for_max_pool_32_16_U0_din;
wire    start_for_max_pool_32_16_U0_full_n;
wire   [0:0] start_for_max_pool_32_16_U0_dout;
wire    start_for_max_pool_32_16_U0_empty_n;
wire   [0:0] start_for_layer_block_32_64_8_U0_din;
wire    start_for_layer_block_32_64_8_U0_full_n;
wire   [0:0] start_for_layer_block_32_64_8_U0_dout;
wire    start_for_layer_block_32_64_8_U0_empty_n;
wire   [0:0] start_for_max_pool_64_8_U0_din;
wire    start_for_max_pool_64_8_U0_full_n;
wire   [0:0] start_for_max_pool_64_8_U0_dout;
wire    start_for_max_pool_64_8_U0_empty_n;
wire   [0:0] start_for_dense_layer_U0_din;
wire    start_for_dense_layer_U0_full_n;
wire   [0:0] start_for_dense_layer_U0_dout;
wire    start_for_dense_layer_U0_empty_n;

vgg_accelerator_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

vgg_accelerator_input_adapter input_adapter_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(input_adapter_U0_ap_start),
    .start_full_n(start_for_layer_block_1_16_32_U0_full_n),
    .ap_done(input_adapter_U0_ap_done),
    .ap_continue(input_adapter_U0_ap_continue),
    .ap_idle(input_adapter_U0_ap_idle),
    .ap_ready(input_adapter_U0_ap_ready),
    .INPUT_STREAM_TVALID(INPUT_STREAM_TVALID),
    .s_input_din(input_adapter_U0_s_input_din),
    .s_input_num_data_valid(s_input_num_data_valid),
    .s_input_fifo_cap(s_input_fifo_cap),
    .s_input_full_n(s_input_full_n),
    .s_input_write(input_adapter_U0_s_input_write),
    .start_out(input_adapter_U0_start_out),
    .start_write(input_adapter_U0_start_write),
    .INPUT_STREAM_TDATA(INPUT_STREAM_TDATA),
    .INPUT_STREAM_TREADY(input_adapter_U0_INPUT_STREAM_TREADY),
    .INPUT_STREAM_TKEEP(INPUT_STREAM_TKEEP),
    .INPUT_STREAM_TSTRB(INPUT_STREAM_TSTRB),
    .INPUT_STREAM_TLAST(INPUT_STREAM_TLAST)
);

vgg_accelerator_layer_block_1_16_32_s layer_block_1_16_32_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(layer_block_1_16_32_U0_ap_start),
    .start_full_n(start_for_max_pool_16_32_U0_full_n),
    .ap_done(layer_block_1_16_32_U0_ap_done),
    .ap_continue(layer_block_1_16_32_U0_ap_continue),
    .ap_idle(layer_block_1_16_32_U0_ap_idle),
    .ap_ready(layer_block_1_16_32_U0_ap_ready),
    .start_out(layer_block_1_16_32_U0_start_out),
    .start_write(layer_block_1_16_32_U0_start_write),
    .s_input_dout(s_input_dout),
    .s_input_num_data_valid(s_input_num_data_valid),
    .s_input_fifo_cap(s_input_fifo_cap),
    .s_input_empty_n(s_input_empty_n),
    .s_input_read(layer_block_1_16_32_U0_s_input_read),
    .s_conv1_din(layer_block_1_16_32_U0_s_conv1_din),
    .s_conv1_num_data_valid(s_conv1_num_data_valid),
    .s_conv1_fifo_cap(s_conv1_fifo_cap),
    .s_conv1_full_n(s_conv1_full_n),
    .s_conv1_write(layer_block_1_16_32_U0_s_conv1_write)
);

vgg_accelerator_max_pool_16_32_s max_pool_16_32_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(max_pool_16_32_U0_ap_start),
    .start_full_n(start_for_layer_block_16_32_16_U0_full_n),
    .ap_done(max_pool_16_32_U0_ap_done),
    .ap_continue(max_pool_16_32_U0_ap_continue),
    .ap_idle(max_pool_16_32_U0_ap_idle),
    .ap_ready(max_pool_16_32_U0_ap_ready),
    .s_conv1_dout(s_conv1_dout),
    .s_conv1_num_data_valid(s_conv1_num_data_valid),
    .s_conv1_fifo_cap(s_conv1_fifo_cap),
    .s_conv1_empty_n(s_conv1_empty_n),
    .s_conv1_read(max_pool_16_32_U0_s_conv1_read),
    .s_pool1_din(max_pool_16_32_U0_s_pool1_din),
    .s_pool1_num_data_valid(s_pool1_num_data_valid),
    .s_pool1_fifo_cap(s_pool1_fifo_cap),
    .s_pool1_full_n(s_pool1_full_n),
    .s_pool1_write(max_pool_16_32_U0_s_pool1_write),
    .start_out(max_pool_16_32_U0_start_out),
    .start_write(max_pool_16_32_U0_start_write)
);

vgg_accelerator_layer_block_16_32_16_s layer_block_16_32_16_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(layer_block_16_32_16_U0_ap_start),
    .start_full_n(start_for_max_pool_32_16_U0_full_n),
    .ap_done(layer_block_16_32_16_U0_ap_done),
    .ap_continue(layer_block_16_32_16_U0_ap_continue),
    .ap_idle(layer_block_16_32_16_U0_ap_idle),
    .ap_ready(layer_block_16_32_16_U0_ap_ready),
    .start_out(layer_block_16_32_16_U0_start_out),
    .start_write(layer_block_16_32_16_U0_start_write),
    .s_conv2_din(layer_block_16_32_16_U0_s_conv2_din),
    .s_conv2_num_data_valid(s_conv2_num_data_valid),
    .s_conv2_fifo_cap(s_conv2_fifo_cap),
    .s_conv2_full_n(s_conv2_full_n),
    .s_conv2_write(layer_block_16_32_16_U0_s_conv2_write),
    .s_pool1_dout(s_pool1_dout),
    .s_pool1_num_data_valid(s_pool1_num_data_valid),
    .s_pool1_fifo_cap(s_pool1_fifo_cap),
    .s_pool1_empty_n(s_pool1_empty_n),
    .s_pool1_read(layer_block_16_32_16_U0_s_pool1_read)
);

vgg_accelerator_max_pool_32_16_s max_pool_32_16_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(max_pool_32_16_U0_ap_start),
    .start_full_n(start_for_layer_block_32_64_8_U0_full_n),
    .ap_done(max_pool_32_16_U0_ap_done),
    .ap_continue(max_pool_32_16_U0_ap_continue),
    .ap_idle(max_pool_32_16_U0_ap_idle),
    .ap_ready(max_pool_32_16_U0_ap_ready),
    .s_conv2_dout(s_conv2_dout),
    .s_conv2_num_data_valid(s_conv2_num_data_valid),
    .s_conv2_fifo_cap(s_conv2_fifo_cap),
    .s_conv2_empty_n(s_conv2_empty_n),
    .s_conv2_read(max_pool_32_16_U0_s_conv2_read),
    .s_pool2_din(max_pool_32_16_U0_s_pool2_din),
    .s_pool2_num_data_valid(s_pool2_num_data_valid),
    .s_pool2_fifo_cap(s_pool2_fifo_cap),
    .s_pool2_full_n(s_pool2_full_n),
    .s_pool2_write(max_pool_32_16_U0_s_pool2_write),
    .start_out(max_pool_32_16_U0_start_out),
    .start_write(max_pool_32_16_U0_start_write)
);

vgg_accelerator_layer_block_32_64_8_s layer_block_32_64_8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(layer_block_32_64_8_U0_ap_start),
    .start_full_n(start_for_max_pool_64_8_U0_full_n),
    .ap_done(layer_block_32_64_8_U0_ap_done),
    .ap_continue(layer_block_32_64_8_U0_ap_continue),
    .ap_idle(layer_block_32_64_8_U0_ap_idle),
    .ap_ready(layer_block_32_64_8_U0_ap_ready),
    .start_out(layer_block_32_64_8_U0_start_out),
    .start_write(layer_block_32_64_8_U0_start_write),
    .s_conv3_din(layer_block_32_64_8_U0_s_conv3_din),
    .s_conv3_num_data_valid(s_conv3_num_data_valid),
    .s_conv3_fifo_cap(s_conv3_fifo_cap),
    .s_conv3_full_n(s_conv3_full_n),
    .s_conv3_write(layer_block_32_64_8_U0_s_conv3_write),
    .s_pool2_dout(s_pool2_dout),
    .s_pool2_num_data_valid(s_pool2_num_data_valid),
    .s_pool2_fifo_cap(s_pool2_fifo_cap),
    .s_pool2_empty_n(s_pool2_empty_n),
    .s_pool2_read(layer_block_32_64_8_U0_s_pool2_read)
);

vgg_accelerator_max_pool_64_8_s max_pool_64_8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(max_pool_64_8_U0_ap_start),
    .start_full_n(start_for_dense_layer_U0_full_n),
    .ap_done(max_pool_64_8_U0_ap_done),
    .ap_continue(max_pool_64_8_U0_ap_continue),
    .ap_idle(max_pool_64_8_U0_ap_idle),
    .ap_ready(max_pool_64_8_U0_ap_ready),
    .s_conv3_dout(s_conv3_dout),
    .s_conv3_num_data_valid(s_conv3_num_data_valid),
    .s_conv3_fifo_cap(s_conv3_fifo_cap),
    .s_conv3_empty_n(s_conv3_empty_n),
    .s_conv3_read(max_pool_64_8_U0_s_conv3_read),
    .s_pool3_din(max_pool_64_8_U0_s_pool3_din),
    .s_pool3_num_data_valid(s_pool3_num_data_valid),
    .s_pool3_fifo_cap(s_pool3_fifo_cap),
    .s_pool3_full_n(s_pool3_full_n),
    .s_pool3_write(max_pool_64_8_U0_s_pool3_write),
    .start_out(max_pool_64_8_U0_start_out),
    .start_write(max_pool_64_8_U0_start_write)
);

vgg_accelerator_dense_layer dense_layer_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_layer_U0_ap_start),
    .ap_done(dense_layer_U0_ap_done),
    .ap_continue(dense_layer_U0_ap_continue),
    .ap_idle(dense_layer_U0_ap_idle),
    .ap_ready(dense_layer_U0_ap_ready),
    .OUTPUT_STREAM_TDATA(dense_layer_U0_OUTPUT_STREAM_TDATA),
    .OUTPUT_STREAM_TVALID(dense_layer_U0_OUTPUT_STREAM_TVALID),
    .OUTPUT_STREAM_TREADY(OUTPUT_STREAM_TREADY),
    .OUTPUT_STREAM_TKEEP(dense_layer_U0_OUTPUT_STREAM_TKEEP),
    .OUTPUT_STREAM_TSTRB(dense_layer_U0_OUTPUT_STREAM_TSTRB),
    .OUTPUT_STREAM_TLAST(dense_layer_U0_OUTPUT_STREAM_TLAST),
    .s_pool3_dout(s_pool3_dout),
    .s_pool3_num_data_valid(s_pool3_num_data_valid),
    .s_pool3_fifo_cap(s_pool3_fifo_cap),
    .s_pool3_empty_n(s_pool3_empty_n),
    .s_pool3_read(dense_layer_U0_s_pool3_read)
);

vgg_accelerator_fifo_w8_d128_S s_input_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(input_adapter_U0_s_input_din),
    .if_full_n(s_input_full_n),
    .if_write(input_adapter_U0_s_input_write),
    .if_dout(s_input_dout),
    .if_num_data_valid(s_input_num_data_valid),
    .if_fifo_cap(s_input_fifo_cap),
    .if_empty_n(s_input_empty_n),
    .if_read(layer_block_1_16_32_U0_s_input_read)
);

vgg_accelerator_fifo_w8_d128_S s_conv1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(layer_block_1_16_32_U0_s_conv1_din),
    .if_full_n(s_conv1_full_n),
    .if_write(layer_block_1_16_32_U0_s_conv1_write),
    .if_dout(s_conv1_dout),
    .if_num_data_valid(s_conv1_num_data_valid),
    .if_fifo_cap(s_conv1_fifo_cap),
    .if_empty_n(s_conv1_empty_n),
    .if_read(max_pool_16_32_U0_s_conv1_read)
);

vgg_accelerator_fifo_w8_d128_S s_pool1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(max_pool_16_32_U0_s_pool1_din),
    .if_full_n(s_pool1_full_n),
    .if_write(max_pool_16_32_U0_s_pool1_write),
    .if_dout(s_pool1_dout),
    .if_num_data_valid(s_pool1_num_data_valid),
    .if_fifo_cap(s_pool1_fifo_cap),
    .if_empty_n(s_pool1_empty_n),
    .if_read(layer_block_16_32_16_U0_s_pool1_read)
);

vgg_accelerator_fifo_w8_d64_S s_conv2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(layer_block_16_32_16_U0_s_conv2_din),
    .if_full_n(s_conv2_full_n),
    .if_write(layer_block_16_32_16_U0_s_conv2_write),
    .if_dout(s_conv2_dout),
    .if_num_data_valid(s_conv2_num_data_valid),
    .if_fifo_cap(s_conv2_fifo_cap),
    .if_empty_n(s_conv2_empty_n),
    .if_read(max_pool_32_16_U0_s_conv2_read)
);

vgg_accelerator_fifo_w8_d64_S s_pool2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(max_pool_32_16_U0_s_pool2_din),
    .if_full_n(s_pool2_full_n),
    .if_write(max_pool_32_16_U0_s_pool2_write),
    .if_dout(s_pool2_dout),
    .if_num_data_valid(s_pool2_num_data_valid),
    .if_fifo_cap(s_pool2_fifo_cap),
    .if_empty_n(s_pool2_empty_n),
    .if_read(layer_block_32_64_8_U0_s_pool2_read)
);

vgg_accelerator_fifo_w8_d64_S s_conv3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(layer_block_32_64_8_U0_s_conv3_din),
    .if_full_n(s_conv3_full_n),
    .if_write(layer_block_32_64_8_U0_s_conv3_write),
    .if_dout(s_conv3_dout),
    .if_num_data_valid(s_conv3_num_data_valid),
    .if_fifo_cap(s_conv3_fifo_cap),
    .if_empty_n(s_conv3_empty_n),
    .if_read(max_pool_64_8_U0_s_conv3_read)
);

vgg_accelerator_fifo_w8_d64_S s_pool3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(max_pool_64_8_U0_s_pool3_din),
    .if_full_n(s_pool3_full_n),
    .if_write(max_pool_64_8_U0_s_pool3_write),
    .if_dout(s_pool3_dout),
    .if_num_data_valid(s_pool3_num_data_valid),
    .if_fifo_cap(s_pool3_fifo_cap),
    .if_empty_n(s_pool3_empty_n),
    .if_read(dense_layer_U0_s_pool3_read)
);

vgg_accelerator_start_for_layer_block_1_16_32_U0 start_for_layer_block_1_16_32_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_layer_block_1_16_32_U0_din),
    .if_full_n(start_for_layer_block_1_16_32_U0_full_n),
    .if_write(input_adapter_U0_start_write),
    .if_dout(start_for_layer_block_1_16_32_U0_dout),
    .if_empty_n(start_for_layer_block_1_16_32_U0_empty_n),
    .if_read(layer_block_1_16_32_U0_ap_ready)
);

vgg_accelerator_start_for_max_pool_16_32_U0 start_for_max_pool_16_32_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_max_pool_16_32_U0_din),
    .if_full_n(start_for_max_pool_16_32_U0_full_n),
    .if_write(layer_block_1_16_32_U0_start_write),
    .if_dout(start_for_max_pool_16_32_U0_dout),
    .if_empty_n(start_for_max_pool_16_32_U0_empty_n),
    .if_read(max_pool_16_32_U0_ap_ready)
);

vgg_accelerator_start_for_layer_block_16_32_16_U0 start_for_layer_block_16_32_16_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_layer_block_16_32_16_U0_din),
    .if_full_n(start_for_layer_block_16_32_16_U0_full_n),
    .if_write(max_pool_16_32_U0_start_write),
    .if_dout(start_for_layer_block_16_32_16_U0_dout),
    .if_empty_n(start_for_layer_block_16_32_16_U0_empty_n),
    .if_read(layer_block_16_32_16_U0_ap_ready)
);

vgg_accelerator_start_for_max_pool_32_16_U0 start_for_max_pool_32_16_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_max_pool_32_16_U0_din),
    .if_full_n(start_for_max_pool_32_16_U0_full_n),
    .if_write(layer_block_16_32_16_U0_start_write),
    .if_dout(start_for_max_pool_32_16_U0_dout),
    .if_empty_n(start_for_max_pool_32_16_U0_empty_n),
    .if_read(max_pool_32_16_U0_ap_ready)
);

vgg_accelerator_start_for_layer_block_32_64_8_U0 start_for_layer_block_32_64_8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_layer_block_32_64_8_U0_din),
    .if_full_n(start_for_layer_block_32_64_8_U0_full_n),
    .if_write(max_pool_32_16_U0_start_write),
    .if_dout(start_for_layer_block_32_64_8_U0_dout),
    .if_empty_n(start_for_layer_block_32_64_8_U0_empty_n),
    .if_read(layer_block_32_64_8_U0_ap_ready)
);

vgg_accelerator_start_for_max_pool_64_8_U0 start_for_max_pool_64_8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_max_pool_64_8_U0_din),
    .if_full_n(start_for_max_pool_64_8_U0_full_n),
    .if_write(layer_block_32_64_8_U0_start_write),
    .if_dout(start_for_max_pool_64_8_U0_dout),
    .if_empty_n(start_for_max_pool_64_8_U0_empty_n),
    .if_read(max_pool_64_8_U0_ap_ready)
);

vgg_accelerator_start_for_dense_layer_U0 start_for_dense_layer_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_layer_U0_din),
    .if_full_n(start_for_dense_layer_U0_full_n),
    .if_write(max_pool_64_8_U0_start_write),
    .if_dout(start_for_dense_layer_U0_dout),
    .if_empty_n(start_for_dense_layer_U0_empty_n),
    .if_read(dense_layer_U0_ap_ready)
);

assign INPUT_STREAM_TREADY = input_adapter_U0_INPUT_STREAM_TREADY;

assign OUTPUT_STREAM_TDATA = dense_layer_U0_OUTPUT_STREAM_TDATA;

assign OUTPUT_STREAM_TKEEP = dense_layer_U0_OUTPUT_STREAM_TKEEP;

assign OUTPUT_STREAM_TLAST = dense_layer_U0_OUTPUT_STREAM_TLAST;

assign OUTPUT_STREAM_TSTRB = dense_layer_U0_OUTPUT_STREAM_TSTRB;

assign OUTPUT_STREAM_TVALID = dense_layer_U0_OUTPUT_STREAM_TVALID;

assign ap_done = dense_layer_U0_ap_done;

assign ap_idle = (max_pool_64_8_U0_ap_idle & max_pool_32_16_U0_ap_idle & max_pool_16_32_U0_ap_idle & layer_block_32_64_8_U0_ap_idle & layer_block_1_16_32_U0_ap_idle & layer_block_16_32_16_U0_ap_idle & input_adapter_U0_ap_idle & dense_layer_U0_ap_idle);

assign ap_ready = input_adapter_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign dense_layer_U0_ap_continue = 1'b1;

assign dense_layer_U0_ap_start = start_for_dense_layer_U0_empty_n;

assign input_adapter_U0_ap_continue = 1'b1;

assign input_adapter_U0_ap_start = ap_start;

assign layer_block_16_32_16_U0_ap_continue = 1'b1;

assign layer_block_16_32_16_U0_ap_start = start_for_layer_block_16_32_16_U0_empty_n;

assign layer_block_1_16_32_U0_ap_continue = 1'b1;

assign layer_block_1_16_32_U0_ap_start = start_for_layer_block_1_16_32_U0_empty_n;

assign layer_block_32_64_8_U0_ap_continue = 1'b1;

assign layer_block_32_64_8_U0_ap_start = start_for_layer_block_32_64_8_U0_empty_n;

assign max_pool_16_32_U0_ap_continue = 1'b1;

assign max_pool_16_32_U0_ap_start = start_for_max_pool_16_32_U0_empty_n;

assign max_pool_32_16_U0_ap_continue = 1'b1;

assign max_pool_32_16_U0_ap_start = start_for_max_pool_32_16_U0_empty_n;

assign max_pool_64_8_U0_ap_continue = 1'b1;

assign max_pool_64_8_U0_ap_start = start_for_max_pool_64_8_U0_empty_n;

assign start_for_dense_layer_U0_din = 1'b1;

assign start_for_layer_block_16_32_16_U0_din = 1'b1;

assign start_for_layer_block_1_16_32_U0_din = 1'b1;

assign start_for_layer_block_32_64_8_U0_din = 1'b1;

assign start_for_max_pool_16_32_U0_din = 1'b1;

assign start_for_max_pool_32_16_U0_din = 1'b1;

assign start_for_max_pool_64_8_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "vgg_accelerator_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "vgg_accelerator_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //vgg_accelerator

