// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module vgg_accelerator_layer_block_32_64_8_Pipeline_VITIS_LOOP_71_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln66,
        zext_ln71_1,
        zext_ln76,
        window_V_2101_i_reload,
        window_V_9_2_i_reload,
        window_V_18_2_i_reload,
        window_V_27_2_i_reload,
        window_V_36_2_i_reload,
        window_V_45_2_i_reload,
        window_V_54_2_i_reload,
        window_V_63_2_i_reload,
        window_V_72_2_i_reload,
        window_V_81_2_i_reload,
        window_V_90_2_i_reload,
        window_V_99_2_i_reload,
        window_V_108_2_i_reload,
        window_V_117_2_i_reload,
        window_V_126_2_i_reload,
        window_V_135_2_i_reload,
        window_V_144_2_i_reload,
        window_V_153_2_i_reload,
        window_V_162_2_i_reload,
        window_V_171_2_i_reload,
        window_V_180_2_i_reload,
        window_V_189_2_i_reload,
        window_V_198_2_i_reload,
        window_V_207_2_i_reload,
        window_V_216_2_i_reload,
        window_V_225_2_i_reload,
        window_V_234_2_i_reload,
        window_V_243_2_i_reload,
        window_V_252_2_i_reload,
        window_V_261_2_i_reload,
        window_V_270_2_i_reload,
        window_V_279_2_i_reload,
        window_V_1_2_i_reload,
        window_V_10_2_i_reload,
        window_V_19_2_i_reload,
        window_V_28_2_i_reload,
        window_V_37_2_i_reload,
        window_V_46_2_i_reload,
        window_V_55_2_i_reload,
        window_V_64_2_i_reload,
        window_V_73_2_i_reload,
        window_V_82_2_i_reload,
        window_V_91_2_i_reload,
        window_V_100_2_i_reload,
        window_V_109_2_i_reload,
        window_V_118_2_i_reload,
        window_V_127_2_i_reload,
        window_V_136_2_i_reload,
        window_V_145_2_i_reload,
        window_V_154_2_i_reload,
        window_V_163_2_i_reload,
        window_V_172_2_i_reload,
        window_V_181_2_i_reload,
        window_V_190_2_i_reload,
        window_V_199_2_i_reload,
        window_V_208_2_i_reload,
        window_V_217_2_i_reload,
        window_V_226_2_i_reload,
        window_V_235_2_i_reload,
        window_V_244_2_i_reload,
        window_V_253_2_i_reload,
        window_V_262_2_i_reload,
        window_V_271_2_i_reload,
        window_V_280_2_i_reload,
        window_V_9_reload,
        window_V_16_reload,
        window_V_23_reload,
        window_V_30_reload,
        window_V_37_reload,
        window_V_44_reload,
        window_V_51_reload,
        window_V_58_reload,
        window_V_65_reload,
        window_V_72_reload,
        window_V_79_reload,
        window_V_86_reload,
        window_V_93_reload,
        window_V_100_reload,
        window_V_107_reload,
        window_V_114_reload,
        window_V_121_reload,
        window_V_128_reload,
        window_V_135_reload,
        window_V_142_reload,
        window_V_149_reload,
        window_V_156_reload,
        window_V_163_reload,
        window_V_170_reload,
        window_V_177_reload,
        window_V_184_reload,
        window_V_191_reload,
        window_V_198_reload,
        window_V_205_reload,
        window_V_212_reload,
        window_V_219_reload,
        window_V_1_reload,
        window_V_3_2_i_reload,
        window_V_12_2_i_reload,
        window_V_21_2_i_reload,
        window_V_30_2_i_reload,
        window_V_39_2_i_reload,
        window_V_48_2_i_reload,
        window_V_57_2_i_reload,
        window_V_66_2_i_reload,
        window_V_75_2_i_reload,
        window_V_84_2_i_reload,
        window_V_93_2_i_reload,
        window_V_102_2_i_reload,
        window_V_111_2_i_reload,
        window_V_120_2_i_reload,
        window_V_129_2_i_reload,
        window_V_138_2_i_reload,
        window_V_147_2_i_reload,
        window_V_156_2_i_reload,
        window_V_165_2_i_reload,
        window_V_174_2_i_reload,
        window_V_183_2_i_reload,
        window_V_192_2_i_reload,
        window_V_201_2_i_reload,
        window_V_210_2_i_reload,
        window_V_219_2_i_reload,
        window_V_228_2_i_reload,
        window_V_237_2_i_reload,
        window_V_246_2_i_reload,
        window_V_255_2_i_reload,
        window_V_264_2_i_reload,
        window_V_273_2_i_reload,
        window_V_282_2_i_reload,
        window_V_10_reload,
        window_V_17_reload,
        window_V_24_reload,
        window_V_31_reload,
        window_V_38_reload,
        window_V_45_reload,
        window_V_52_reload,
        window_V_59_reload,
        window_V_66_reload,
        window_V_73_reload,
        window_V_80_reload,
        window_V_87_reload,
        window_V_94_reload,
        window_V_101_reload,
        window_V_108_reload,
        window_V_115_reload,
        window_V_122_reload,
        window_V_129_reload,
        window_V_136_reload,
        window_V_143_reload,
        window_V_150_reload,
        window_V_157_reload,
        window_V_164_reload,
        window_V_171_reload,
        window_V_178_reload,
        window_V_185_reload,
        window_V_192_reload,
        window_V_199_reload,
        window_V_206_reload,
        window_V_213_reload,
        window_V_220_reload,
        window_V_2_reload,
        window_V_11_reload,
        window_V_18_reload,
        window_V_25_reload,
        window_V_32_reload,
        window_V_39_reload,
        window_V_46_reload,
        window_V_53_reload,
        window_V_60_reload,
        window_V_67_reload,
        window_V_74_reload,
        window_V_81_reload,
        window_V_88_reload,
        window_V_95_reload,
        window_V_102_reload,
        window_V_109_reload,
        window_V_116_reload,
        window_V_123_reload,
        window_V_130_reload,
        window_V_137_reload,
        window_V_144_reload,
        window_V_151_reload,
        window_V_158_reload,
        window_V_165_reload,
        window_V_172_reload,
        window_V_179_reload,
        window_V_186_reload,
        window_V_193_reload,
        window_V_200_reload,
        window_V_207_reload,
        window_V_214_reload,
        window_V_221_reload,
        window_V_3_reload,
        window_V_6_2_i_reload,
        window_V_15_2_i_reload,
        window_V_24_2_i_reload,
        window_V_33_2_i_reload,
        window_V_42_2_i_reload,
        window_V_51_2_i_reload,
        window_V_60_2_i_reload,
        window_V_69_2_i_reload,
        window_V_78_2_i_reload,
        window_V_87_2_i_reload,
        window_V_96_2_i_reload,
        window_V_105_2_i_reload,
        window_V_114_2_i_reload,
        window_V_123_2_i_reload,
        window_V_132_2_i_reload,
        window_V_141_2_i_reload,
        window_V_150_2_i_reload,
        window_V_159_2_i_reload,
        window_V_168_2_i_reload,
        window_V_177_2_i_reload,
        window_V_186_2_i_reload,
        window_V_195_2_i_reload,
        window_V_204_2_i_reload,
        window_V_213_2_i_reload,
        window_V_222_2_i_reload,
        window_V_231_2_i_reload,
        window_V_240_2_i_reload,
        window_V_249_2_i_reload,
        window_V_258_2_i_reload,
        window_V_267_2_i_reload,
        window_V_276_2_i_reload,
        window_V_285_2_i_reload,
        window_V_12_reload,
        window_V_19_reload,
        window_V_26_reload,
        window_V_33_reload,
        window_V_40_reload,
        window_V_47_reload,
        window_V_54_reload,
        window_V_61_reload,
        window_V_68_reload,
        window_V_75_reload,
        window_V_82_reload,
        window_V_89_reload,
        window_V_96_reload,
        window_V_103_reload,
        window_V_110_reload,
        window_V_117_reload,
        window_V_124_reload,
        window_V_131_reload,
        window_V_138_reload,
        window_V_145_reload,
        window_V_152_reload,
        window_V_159_reload,
        window_V_166_reload,
        window_V_173_reload,
        window_V_180_reload,
        window_V_187_reload,
        window_V_194_reload,
        window_V_201_reload,
        window_V_208_reload,
        window_V_215_reload,
        window_V_222_reload,
        window_V_4_reload,
        window_V_13_reload,
        window_V_20_reload,
        window_V_27_reload,
        window_V_34_reload,
        window_V_41_reload,
        window_V_48_reload,
        window_V_55_reload,
        window_V_62_reload,
        window_V_69_reload,
        window_V_76_reload,
        window_V_83_reload,
        window_V_90_reload,
        window_V_97_reload,
        window_V_104_reload,
        window_V_111_reload,
        window_V_118_reload,
        window_V_125_reload,
        window_V_132_reload,
        window_V_139_reload,
        window_V_146_reload,
        window_V_153_reload,
        window_V_160_reload,
        window_V_167_reload,
        window_V_174_reload,
        window_V_181_reload,
        window_V_188_reload,
        window_V_195_reload,
        window_V_202_reload,
        window_V_209_reload,
        window_V_216_reload,
        window_V_223_reload,
        window_V_5_reload,
        s_conv3_din,
        s_conv3_num_data_valid,
        s_conv3_fifo_cap,
        s_conv3_full_n,
        s_conv3_write
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [14:0] sext_ln66;
input  [10:0] zext_ln71_1;
input  [13:0] zext_ln76;
input  [7:0] window_V_2101_i_reload;
input  [7:0] window_V_9_2_i_reload;
input  [7:0] window_V_18_2_i_reload;
input  [7:0] window_V_27_2_i_reload;
input  [7:0] window_V_36_2_i_reload;
input  [7:0] window_V_45_2_i_reload;
input  [7:0] window_V_54_2_i_reload;
input  [7:0] window_V_63_2_i_reload;
input  [7:0] window_V_72_2_i_reload;
input  [7:0] window_V_81_2_i_reload;
input  [7:0] window_V_90_2_i_reload;
input  [7:0] window_V_99_2_i_reload;
input  [7:0] window_V_108_2_i_reload;
input  [7:0] window_V_117_2_i_reload;
input  [7:0] window_V_126_2_i_reload;
input  [7:0] window_V_135_2_i_reload;
input  [7:0] window_V_144_2_i_reload;
input  [7:0] window_V_153_2_i_reload;
input  [7:0] window_V_162_2_i_reload;
input  [7:0] window_V_171_2_i_reload;
input  [7:0] window_V_180_2_i_reload;
input  [7:0] window_V_189_2_i_reload;
input  [7:0] window_V_198_2_i_reload;
input  [7:0] window_V_207_2_i_reload;
input  [7:0] window_V_216_2_i_reload;
input  [7:0] window_V_225_2_i_reload;
input  [7:0] window_V_234_2_i_reload;
input  [7:0] window_V_243_2_i_reload;
input  [7:0] window_V_252_2_i_reload;
input  [7:0] window_V_261_2_i_reload;
input  [7:0] window_V_270_2_i_reload;
input  [7:0] window_V_279_2_i_reload;
input  [7:0] window_V_1_2_i_reload;
input  [7:0] window_V_10_2_i_reload;
input  [7:0] window_V_19_2_i_reload;
input  [7:0] window_V_28_2_i_reload;
input  [7:0] window_V_37_2_i_reload;
input  [7:0] window_V_46_2_i_reload;
input  [7:0] window_V_55_2_i_reload;
input  [7:0] window_V_64_2_i_reload;
input  [7:0] window_V_73_2_i_reload;
input  [7:0] window_V_82_2_i_reload;
input  [7:0] window_V_91_2_i_reload;
input  [7:0] window_V_100_2_i_reload;
input  [7:0] window_V_109_2_i_reload;
input  [7:0] window_V_118_2_i_reload;
input  [7:0] window_V_127_2_i_reload;
input  [7:0] window_V_136_2_i_reload;
input  [7:0] window_V_145_2_i_reload;
input  [7:0] window_V_154_2_i_reload;
input  [7:0] window_V_163_2_i_reload;
input  [7:0] window_V_172_2_i_reload;
input  [7:0] window_V_181_2_i_reload;
input  [7:0] window_V_190_2_i_reload;
input  [7:0] window_V_199_2_i_reload;
input  [7:0] window_V_208_2_i_reload;
input  [7:0] window_V_217_2_i_reload;
input  [7:0] window_V_226_2_i_reload;
input  [7:0] window_V_235_2_i_reload;
input  [7:0] window_V_244_2_i_reload;
input  [7:0] window_V_253_2_i_reload;
input  [7:0] window_V_262_2_i_reload;
input  [7:0] window_V_271_2_i_reload;
input  [7:0] window_V_280_2_i_reload;
input  [7:0] window_V_9_reload;
input  [7:0] window_V_16_reload;
input  [7:0] window_V_23_reload;
input  [7:0] window_V_30_reload;
input  [7:0] window_V_37_reload;
input  [7:0] window_V_44_reload;
input  [7:0] window_V_51_reload;
input  [7:0] window_V_58_reload;
input  [7:0] window_V_65_reload;
input  [7:0] window_V_72_reload;
input  [7:0] window_V_79_reload;
input  [7:0] window_V_86_reload;
input  [7:0] window_V_93_reload;
input  [7:0] window_V_100_reload;
input  [7:0] window_V_107_reload;
input  [7:0] window_V_114_reload;
input  [7:0] window_V_121_reload;
input  [7:0] window_V_128_reload;
input  [7:0] window_V_135_reload;
input  [7:0] window_V_142_reload;
input  [7:0] window_V_149_reload;
input  [7:0] window_V_156_reload;
input  [7:0] window_V_163_reload;
input  [7:0] window_V_170_reload;
input  [7:0] window_V_177_reload;
input  [7:0] window_V_184_reload;
input  [7:0] window_V_191_reload;
input  [7:0] window_V_198_reload;
input  [7:0] window_V_205_reload;
input  [7:0] window_V_212_reload;
input  [7:0] window_V_219_reload;
input  [7:0] window_V_1_reload;
input  [7:0] window_V_3_2_i_reload;
input  [7:0] window_V_12_2_i_reload;
input  [7:0] window_V_21_2_i_reload;
input  [7:0] window_V_30_2_i_reload;
input  [7:0] window_V_39_2_i_reload;
input  [7:0] window_V_48_2_i_reload;
input  [7:0] window_V_57_2_i_reload;
input  [7:0] window_V_66_2_i_reload;
input  [7:0] window_V_75_2_i_reload;
input  [7:0] window_V_84_2_i_reload;
input  [7:0] window_V_93_2_i_reload;
input  [7:0] window_V_102_2_i_reload;
input  [7:0] window_V_111_2_i_reload;
input  [7:0] window_V_120_2_i_reload;
input  [7:0] window_V_129_2_i_reload;
input  [7:0] window_V_138_2_i_reload;
input  [7:0] window_V_147_2_i_reload;
input  [7:0] window_V_156_2_i_reload;
input  [7:0] window_V_165_2_i_reload;
input  [7:0] window_V_174_2_i_reload;
input  [7:0] window_V_183_2_i_reload;
input  [7:0] window_V_192_2_i_reload;
input  [7:0] window_V_201_2_i_reload;
input  [7:0] window_V_210_2_i_reload;
input  [7:0] window_V_219_2_i_reload;
input  [7:0] window_V_228_2_i_reload;
input  [7:0] window_V_237_2_i_reload;
input  [7:0] window_V_246_2_i_reload;
input  [7:0] window_V_255_2_i_reload;
input  [7:0] window_V_264_2_i_reload;
input  [7:0] window_V_273_2_i_reload;
input  [7:0] window_V_282_2_i_reload;
input  [7:0] window_V_10_reload;
input  [7:0] window_V_17_reload;
input  [7:0] window_V_24_reload;
input  [7:0] window_V_31_reload;
input  [7:0] window_V_38_reload;
input  [7:0] window_V_45_reload;
input  [7:0] window_V_52_reload;
input  [7:0] window_V_59_reload;
input  [7:0] window_V_66_reload;
input  [7:0] window_V_73_reload;
input  [7:0] window_V_80_reload;
input  [7:0] window_V_87_reload;
input  [7:0] window_V_94_reload;
input  [7:0] window_V_101_reload;
input  [7:0] window_V_108_reload;
input  [7:0] window_V_115_reload;
input  [7:0] window_V_122_reload;
input  [7:0] window_V_129_reload;
input  [7:0] window_V_136_reload;
input  [7:0] window_V_143_reload;
input  [7:0] window_V_150_reload;
input  [7:0] window_V_157_reload;
input  [7:0] window_V_164_reload;
input  [7:0] window_V_171_reload;
input  [7:0] window_V_178_reload;
input  [7:0] window_V_185_reload;
input  [7:0] window_V_192_reload;
input  [7:0] window_V_199_reload;
input  [7:0] window_V_206_reload;
input  [7:0] window_V_213_reload;
input  [7:0] window_V_220_reload;
input  [7:0] window_V_2_reload;
input  [7:0] window_V_11_reload;
input  [7:0] window_V_18_reload;
input  [7:0] window_V_25_reload;
input  [7:0] window_V_32_reload;
input  [7:0] window_V_39_reload;
input  [7:0] window_V_46_reload;
input  [7:0] window_V_53_reload;
input  [7:0] window_V_60_reload;
input  [7:0] window_V_67_reload;
input  [7:0] window_V_74_reload;
input  [7:0] window_V_81_reload;
input  [7:0] window_V_88_reload;
input  [7:0] window_V_95_reload;
input  [7:0] window_V_102_reload;
input  [7:0] window_V_109_reload;
input  [7:0] window_V_116_reload;
input  [7:0] window_V_123_reload;
input  [7:0] window_V_130_reload;
input  [7:0] window_V_137_reload;
input  [7:0] window_V_144_reload;
input  [7:0] window_V_151_reload;
input  [7:0] window_V_158_reload;
input  [7:0] window_V_165_reload;
input  [7:0] window_V_172_reload;
input  [7:0] window_V_179_reload;
input  [7:0] window_V_186_reload;
input  [7:0] window_V_193_reload;
input  [7:0] window_V_200_reload;
input  [7:0] window_V_207_reload;
input  [7:0] window_V_214_reload;
input  [7:0] window_V_221_reload;
input  [7:0] window_V_3_reload;
input  [7:0] window_V_6_2_i_reload;
input  [7:0] window_V_15_2_i_reload;
input  [7:0] window_V_24_2_i_reload;
input  [7:0] window_V_33_2_i_reload;
input  [7:0] window_V_42_2_i_reload;
input  [7:0] window_V_51_2_i_reload;
input  [7:0] window_V_60_2_i_reload;
input  [7:0] window_V_69_2_i_reload;
input  [7:0] window_V_78_2_i_reload;
input  [7:0] window_V_87_2_i_reload;
input  [7:0] window_V_96_2_i_reload;
input  [7:0] window_V_105_2_i_reload;
input  [7:0] window_V_114_2_i_reload;
input  [7:0] window_V_123_2_i_reload;
input  [7:0] window_V_132_2_i_reload;
input  [7:0] window_V_141_2_i_reload;
input  [7:0] window_V_150_2_i_reload;
input  [7:0] window_V_159_2_i_reload;
input  [7:0] window_V_168_2_i_reload;
input  [7:0] window_V_177_2_i_reload;
input  [7:0] window_V_186_2_i_reload;
input  [7:0] window_V_195_2_i_reload;
input  [7:0] window_V_204_2_i_reload;
input  [7:0] window_V_213_2_i_reload;
input  [7:0] window_V_222_2_i_reload;
input  [7:0] window_V_231_2_i_reload;
input  [7:0] window_V_240_2_i_reload;
input  [7:0] window_V_249_2_i_reload;
input  [7:0] window_V_258_2_i_reload;
input  [7:0] window_V_267_2_i_reload;
input  [7:0] window_V_276_2_i_reload;
input  [7:0] window_V_285_2_i_reload;
input  [7:0] window_V_12_reload;
input  [7:0] window_V_19_reload;
input  [7:0] window_V_26_reload;
input  [7:0] window_V_33_reload;
input  [7:0] window_V_40_reload;
input  [7:0] window_V_47_reload;
input  [7:0] window_V_54_reload;
input  [7:0] window_V_61_reload;
input  [7:0] window_V_68_reload;
input  [7:0] window_V_75_reload;
input  [7:0] window_V_82_reload;
input  [7:0] window_V_89_reload;
input  [7:0] window_V_96_reload;
input  [7:0] window_V_103_reload;
input  [7:0] window_V_110_reload;
input  [7:0] window_V_117_reload;
input  [7:0] window_V_124_reload;
input  [7:0] window_V_131_reload;
input  [7:0] window_V_138_reload;
input  [7:0] window_V_145_reload;
input  [7:0] window_V_152_reload;
input  [7:0] window_V_159_reload;
input  [7:0] window_V_166_reload;
input  [7:0] window_V_173_reload;
input  [7:0] window_V_180_reload;
input  [7:0] window_V_187_reload;
input  [7:0] window_V_194_reload;
input  [7:0] window_V_201_reload;
input  [7:0] window_V_208_reload;
input  [7:0] window_V_215_reload;
input  [7:0] window_V_222_reload;
input  [7:0] window_V_4_reload;
input  [7:0] window_V_13_reload;
input  [7:0] window_V_20_reload;
input  [7:0] window_V_27_reload;
input  [7:0] window_V_34_reload;
input  [7:0] window_V_41_reload;
input  [7:0] window_V_48_reload;
input  [7:0] window_V_55_reload;
input  [7:0] window_V_62_reload;
input  [7:0] window_V_69_reload;
input  [7:0] window_V_76_reload;
input  [7:0] window_V_83_reload;
input  [7:0] window_V_90_reload;
input  [7:0] window_V_97_reload;
input  [7:0] window_V_104_reload;
input  [7:0] window_V_111_reload;
input  [7:0] window_V_118_reload;
input  [7:0] window_V_125_reload;
input  [7:0] window_V_132_reload;
input  [7:0] window_V_139_reload;
input  [7:0] window_V_146_reload;
input  [7:0] window_V_153_reload;
input  [7:0] window_V_160_reload;
input  [7:0] window_V_167_reload;
input  [7:0] window_V_174_reload;
input  [7:0] window_V_181_reload;
input  [7:0] window_V_188_reload;
input  [7:0] window_V_195_reload;
input  [7:0] window_V_202_reload;
input  [7:0] window_V_209_reload;
input  [7:0] window_V_216_reload;
input  [7:0] window_V_223_reload;
input  [7:0] window_V_5_reload;
output  [7:0] s_conv3_din;
input  [6:0] s_conv3_num_data_valid;
input  [6:0] s_conv3_fifo_cap;
input   s_conv3_full_n;
output   s_conv3_write;

reg ap_idle;
reg s_conv3_write;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln71_reg_4369;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [14:0] conv3_weights_address0;
reg    conv3_weights_ce0;
wire  signed [4:0] conv3_weights_q0;
reg   [14:0] conv3_weights_address1;
reg    conv3_weights_ce1;
wire  signed [4:0] conv3_weights_q1;
reg   [14:0] conv3_weights_address2;
reg    conv3_weights_ce2;
wire  signed [4:0] conv3_weights_q2;
reg   [14:0] conv3_weights_address3;
reg    conv3_weights_ce3;
wire  signed [4:0] conv3_weights_q3;
wire   [14:0] conv3_weights_address4;
reg    conv3_weights_ce4;
wire  signed [4:0] conv3_weights_q4;
reg    s_conv3_blk_n;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln71_1_reg_4451;
reg   [0:0] icmp_ln71_1_reg_4451_pp0_iter1_reg;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state5_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln71_fu_2577_p2;
wire   [14:0] add_ln76_2_fu_2629_p2;
reg   [14:0] add_ln76_2_reg_4373;
wire   [7:0] px_V_fu_2640_p34;
reg  signed [7:0] px_V_reg_4386;
wire   [7:0] px_V_1_fu_2721_p34;
reg  signed [7:0] px_V_1_reg_4396;
wire   [7:0] px_V_2_fu_2802_p34;
reg  signed [7:0] px_V_2_reg_4406;
wire   [7:0] px_V_3_fu_2883_p34;
reg  signed [7:0] px_V_3_reg_4416;
wire   [7:0] px_V_4_fu_2964_p34;
reg  signed [7:0] px_V_4_reg_4426;
wire   [7:0] px_V_5_fu_3034_p34;
reg  signed [7:0] px_V_5_reg_4431;
wire   [7:0] px_V_6_fu_3104_p34;
reg  signed [7:0] px_V_6_reg_4436;
wire   [7:0] px_V_7_fu_3174_p34;
reg  signed [7:0] px_V_7_reg_4441;
wire   [7:0] px_V_8_fu_3244_p34;
reg  signed [7:0] px_V_8_reg_4446;
wire   [0:0] icmp_ln71_1_fu_3314_p2;
wire   [11:0] mul_ln1347_fu_3332_p2;
reg   [11:0] mul_ln1347_reg_4455;
wire    ap_block_pp0_stage1_11001;
wire   [11:0] mul_ln1347_1_fu_3345_p2;
reg   [11:0] mul_ln1347_1_reg_4460;
wire   [11:0] mul_ln1347_2_fu_3358_p2;
reg   [11:0] mul_ln1347_2_reg_4465;
wire   [11:0] mul_ln1347_3_fu_3371_p2;
reg   [11:0] mul_ln1347_3_reg_4470;
wire   [11:0] mul_ln1347_4_fu_3384_p2;
reg   [11:0] mul_ln1347_4_reg_4475;
reg   [0:0] p_Result_8_reg_4500;
wire   [31:0] acc_V_10_fu_3790_p2;
reg   [31:0] acc_V_10_reg_4506;
reg   [0:0] p_Result_9_reg_4511;
wire   [11:0] mul_ln1347_5_fu_3811_p2;
reg   [11:0] mul_ln1347_5_reg_4517;
wire   [11:0] mul_ln1347_6_fu_3824_p2;
reg   [11:0] mul_ln1347_6_reg_4522;
wire   [11:0] mul_ln1347_7_fu_3837_p2;
reg   [11:0] mul_ln1347_7_reg_4527;
wire   [11:0] mul_ln1347_8_fu_3850_p2;
reg   [11:0] mul_ln1347_8_reg_4532;
wire   [31:0] acc_V_fu_4201_p3;
reg   [31:0] acc_V_reg_4537;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln76_4_fu_2635_p1;
wire   [63:0] zext_ln76_5_fu_2716_p1;
wire   [63:0] zext_ln76_6_fu_2797_p1;
wire   [63:0] zext_ln76_7_fu_2878_p1;
wire   [63:0] zext_ln76_8_fu_2959_p1;
wire   [63:0] zext_ln76_9_fu_3395_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln76_10_fu_3405_p1;
wire   [63:0] zext_ln76_11_fu_3415_p1;
wire   [63:0] zext_ln76_12_fu_3425_p1;
reg   [31:0] lhs_fu_698;
wire  signed [31:0] sext_ln66_cast_fu_2560_p1;
wire    ap_loop_init;
reg   [5:0] ch_fu_702;
wire   [5:0] add_ln71_fu_2583_p2;
reg   [5:0] ap_sig_allocacmp_ch_1;
reg    ap_block_pp0_stage0_01001;
wire   [4:0] trunc_ln76_fu_2593_p1;
wire   [7:0] shl_ln76_2_fu_2597_p3;
wire   [8:0] zext_ln76_1_fu_2605_p1;
wire   [8:0] zext_ln71_fu_2589_p1;
wire   [8:0] add_ln76_fu_2609_p2;
wire   [11:0] zext_ln71_1_cast_fu_2556_p1;
wire   [11:0] zext_ln76_2_fu_2615_p1;
wire   [11:0] add_ln76_1_fu_2619_p2;
wire   [14:0] zext_ln76_3_fu_2625_p1;
wire   [14:0] zext_ln76_cast_fu_2552_p1;
wire   [14:0] add_ln76_3_fu_2710_p2;
wire   [14:0] add_ln76_4_fu_2791_p2;
wire   [14:0] add_ln76_5_fu_2872_p2;
wire   [14:0] add_ln76_6_fu_2953_p2;
wire   [14:0] add_ln76_7_fu_3390_p2;
wire   [14:0] add_ln76_8_fu_3400_p2;
wire   [14:0] add_ln76_9_fu_3410_p2;
wire   [14:0] add_ln76_10_fu_3420_p2;
wire  signed [31:0] sext_ln813_fu_3433_p0;
wire  signed [19:0] rhs_fu_3437_p3;
wire  signed [32:0] sext_ln813_fu_3433_p1;
wire  signed [32:0] sext_ln1347_fu_3444_p1;
wire   [32:0] ret_V_fu_3452_p2;
wire  signed [31:0] acc_V_2_fu_3466_p0;
wire  signed [31:0] sext_ln1347_1_fu_3448_p1;
wire   [31:0] acc_V_2_fu_3466_p2;
wire   [0:0] p_Result_s_fu_3458_p3;
wire   [0:0] p_Result_1_fu_3472_p3;
wire   [0:0] xor_ln895_1_fu_3480_p2;
wire   [0:0] overflow_1_fu_3486_p2;
wire   [0:0] xor_ln302_fu_3492_p2;
wire   [31:0] select_ln346_fu_3498_p3;
wire  signed [31:0] acc_V_3_fu_3506_p3;
wire  signed [19:0] rhs_1_fu_3518_p3;
wire  signed [32:0] sext_ln813_1_fu_3514_p1;
wire  signed [32:0] sext_ln1347_2_fu_3525_p1;
wire   [32:0] ret_V_1_fu_3533_p2;
wire  signed [31:0] sext_ln1347_3_fu_3529_p1;
wire   [31:0] acc_V_4_fu_3547_p2;
wire   [0:0] p_Result_2_fu_3539_p3;
wire   [0:0] p_Result_3_fu_3553_p3;
wire   [0:0] xor_ln895_2_fu_3561_p2;
wire   [0:0] overflow_2_fu_3567_p2;
wire   [0:0] xor_ln302_1_fu_3573_p2;
wire   [31:0] select_ln346_1_fu_3579_p3;
wire  signed [31:0] acc_V_5_fu_3587_p3;
wire  signed [19:0] rhs_2_fu_3599_p3;
wire  signed [32:0] sext_ln813_2_fu_3595_p1;
wire  signed [32:0] sext_ln1347_4_fu_3606_p1;
wire   [32:0] ret_V_2_fu_3614_p2;
wire  signed [31:0] sext_ln1347_5_fu_3610_p1;
wire   [31:0] acc_V_6_fu_3628_p2;
wire   [0:0] p_Result_4_fu_3620_p3;
wire   [0:0] p_Result_5_fu_3634_p3;
wire   [0:0] xor_ln895_3_fu_3642_p2;
wire   [0:0] overflow_3_fu_3648_p2;
wire   [0:0] xor_ln302_2_fu_3654_p2;
wire   [31:0] select_ln346_2_fu_3660_p3;
wire  signed [31:0] acc_V_7_fu_3668_p3;
wire  signed [19:0] rhs_3_fu_3680_p3;
wire  signed [32:0] sext_ln813_3_fu_3676_p1;
wire  signed [32:0] sext_ln1347_6_fu_3687_p1;
wire   [32:0] ret_V_3_fu_3695_p2;
wire  signed [31:0] sext_ln1347_7_fu_3691_p1;
wire   [31:0] acc_V_8_fu_3709_p2;
wire   [0:0] p_Result_6_fu_3701_p3;
wire   [0:0] p_Result_7_fu_3715_p3;
wire   [0:0] xor_ln895_4_fu_3723_p2;
wire   [0:0] overflow_4_fu_3729_p2;
wire   [0:0] xor_ln302_3_fu_3735_p2;
wire   [31:0] select_ln346_3_fu_3741_p3;
wire  signed [31:0] acc_V_9_fu_3749_p3;
wire  signed [19:0] rhs_4_fu_3761_p3;
wire  signed [32:0] sext_ln813_4_fu_3757_p1;
wire  signed [32:0] sext_ln1347_8_fu_3768_p1;
wire   [32:0] ret_V_4_fu_3776_p2;
wire  signed [31:0] sext_ln1347_9_fu_3772_p1;
wire   [0:0] xor_ln895_5_fu_3856_p2;
wire   [0:0] overflow_5_fu_3861_p2;
wire   [0:0] xor_ln302_4_fu_3866_p2;
wire   [31:0] select_ln346_4_fu_3870_p3;
wire  signed [31:0] acc_V_11_fu_3878_p3;
wire  signed [19:0] rhs_5_fu_3889_p3;
wire  signed [32:0] sext_ln813_5_fu_3885_p1;
wire  signed [32:0] sext_ln1347_10_fu_3896_p1;
wire   [32:0] ret_V_5_fu_3904_p2;
wire  signed [31:0] sext_ln1347_11_fu_3900_p1;
wire   [31:0] acc_V_12_fu_3918_p2;
wire   [0:0] p_Result_10_fu_3910_p3;
wire   [0:0] p_Result_11_fu_3924_p3;
wire   [0:0] xor_ln895_6_fu_3932_p2;
wire   [0:0] overflow_6_fu_3938_p2;
wire   [0:0] xor_ln302_5_fu_3944_p2;
wire   [31:0] select_ln346_5_fu_3950_p3;
wire  signed [31:0] acc_V_13_fu_3958_p3;
wire  signed [19:0] rhs_6_fu_3970_p3;
wire  signed [32:0] sext_ln813_6_fu_3966_p1;
wire  signed [32:0] sext_ln1347_12_fu_3977_p1;
wire   [32:0] ret_V_6_fu_3985_p2;
wire  signed [31:0] sext_ln1347_13_fu_3981_p1;
wire   [31:0] acc_V_14_fu_3999_p2;
wire   [0:0] p_Result_12_fu_3991_p3;
wire   [0:0] p_Result_13_fu_4005_p3;
wire   [0:0] xor_ln895_7_fu_4013_p2;
wire   [0:0] overflow_7_fu_4019_p2;
wire   [0:0] xor_ln302_6_fu_4025_p2;
wire   [31:0] select_ln346_6_fu_4031_p3;
wire  signed [31:0] acc_V_15_fu_4039_p3;
wire  signed [19:0] rhs_7_fu_4051_p3;
wire  signed [32:0] sext_ln813_7_fu_4047_p1;
wire  signed [32:0] sext_ln1347_14_fu_4058_p1;
wire   [32:0] ret_V_7_fu_4066_p2;
wire  signed [31:0] sext_ln1347_15_fu_4062_p1;
wire   [31:0] acc_V_16_fu_4080_p2;
wire   [0:0] p_Result_14_fu_4072_p3;
wire   [0:0] p_Result_15_fu_4086_p3;
wire   [0:0] xor_ln895_8_fu_4094_p2;
wire   [0:0] overflow_8_fu_4100_p2;
wire   [0:0] xor_ln302_7_fu_4106_p2;
wire   [31:0] select_ln346_7_fu_4112_p3;
wire  signed [31:0] acc_V_17_fu_4120_p3;
wire  signed [19:0] rhs_8_fu_4132_p3;
wire  signed [32:0] sext_ln813_8_fu_4128_p1;
wire  signed [32:0] sext_ln1347_16_fu_4139_p1;
wire   [32:0] ret_V_8_fu_4147_p2;
wire  signed [31:0] sext_ln1347_17_fu_4143_p1;
wire   [31:0] acc_V_18_fu_4161_p2;
wire   [0:0] p_Result_16_fu_4153_p3;
wire   [0:0] p_Result_17_fu_4167_p3;
wire   [0:0] xor_ln895_9_fu_4175_p2;
wire   [0:0] overflow_9_fu_4181_p2;
wire   [0:0] xor_ln302_8_fu_4187_p2;
wire   [31:0] select_ln346_8_fu_4193_p3;
wire   [0:0] tmp_fu_4217_p3;
wire   [30:0] trunc_ln71_fu_4214_p1;
wire   [30:0] acc_V_19_fu_4224_p3;
wire   [0:0] tmp_2_fu_4242_p3;
wire   [7:0] p_Val2_1_fu_4232_p4;
wire   [7:0] zext_ln377_fu_4250_p1;
wire   [6:0] trunc_ln377_1_fu_4254_p4;
wire   [6:0] zext_ln377_1_fu_4264_p1;
wire   [7:0] p_Val2_20_fu_4268_p2;
wire   [10:0] tmp_1_fu_4288_p4;
wire   [0:0] tmp_4_fu_4304_p3;
wire   [0:0] p_Result_18_fu_4280_p3;
wire   [0:0] xor_ln888_fu_4312_p2;
wire   [0:0] Range1_all_zeros_fu_4298_p2;
wire   [0:0] or_ln888_fu_4318_p2;
wire   [0:0] deleted_zeros_fu_4324_p2;
wire   [0:0] xor_ln895_fu_4330_p2;
wire   [0:0] overflow_fu_4336_p2;
wire   [6:0] add_ln856_fu_4274_p2;
wire   [6:0] select_ln302_fu_4342_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

vgg_accelerator_layer_block_32_64_8_Pipeline_VITIS_LOOP_71_8_conv3_weights_ROM_AUTO_1R #(
    .DataWidth( 5 ),
    .AddressRange( 18432 ),
    .AddressWidth( 15 ))
conv3_weights_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv3_weights_address0),
    .ce0(conv3_weights_ce0),
    .q0(conv3_weights_q0),
    .address1(conv3_weights_address1),
    .ce1(conv3_weights_ce1),
    .q1(conv3_weights_q1),
    .address2(conv3_weights_address2),
    .ce2(conv3_weights_ce2),
    .q2(conv3_weights_q2),
    .address3(conv3_weights_address3),
    .ce3(conv3_weights_ce3),
    .q3(conv3_weights_q3),
    .address4(conv3_weights_address4),
    .ce4(conv3_weights_ce4),
    .q4(conv3_weights_q4)
);

vgg_accelerator_mux_325_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_325_8_1_1_U1080(
    .din0(window_V_2101_i_reload),
    .din1(window_V_9_2_i_reload),
    .din2(window_V_18_2_i_reload),
    .din3(window_V_27_2_i_reload),
    .din4(window_V_36_2_i_reload),
    .din5(window_V_45_2_i_reload),
    .din6(window_V_54_2_i_reload),
    .din7(window_V_63_2_i_reload),
    .din8(window_V_72_2_i_reload),
    .din9(window_V_81_2_i_reload),
    .din10(window_V_90_2_i_reload),
    .din11(window_V_99_2_i_reload),
    .din12(window_V_108_2_i_reload),
    .din13(window_V_117_2_i_reload),
    .din14(window_V_126_2_i_reload),
    .din15(window_V_135_2_i_reload),
    .din16(window_V_144_2_i_reload),
    .din17(window_V_153_2_i_reload),
    .din18(window_V_162_2_i_reload),
    .din19(window_V_171_2_i_reload),
    .din20(window_V_180_2_i_reload),
    .din21(window_V_189_2_i_reload),
    .din22(window_V_198_2_i_reload),
    .din23(window_V_207_2_i_reload),
    .din24(window_V_216_2_i_reload),
    .din25(window_V_225_2_i_reload),
    .din26(window_V_234_2_i_reload),
    .din27(window_V_243_2_i_reload),
    .din28(window_V_252_2_i_reload),
    .din29(window_V_261_2_i_reload),
    .din30(window_V_270_2_i_reload),
    .din31(window_V_279_2_i_reload),
    .din32(trunc_ln76_fu_2593_p1),
    .dout(px_V_fu_2640_p34)
);

vgg_accelerator_mux_325_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_325_8_1_1_U1081(
    .din0(window_V_1_2_i_reload),
    .din1(window_V_10_2_i_reload),
    .din2(window_V_19_2_i_reload),
    .din3(window_V_28_2_i_reload),
    .din4(window_V_37_2_i_reload),
    .din5(window_V_46_2_i_reload),
    .din6(window_V_55_2_i_reload),
    .din7(window_V_64_2_i_reload),
    .din8(window_V_73_2_i_reload),
    .din9(window_V_82_2_i_reload),
    .din10(window_V_91_2_i_reload),
    .din11(window_V_100_2_i_reload),
    .din12(window_V_109_2_i_reload),
    .din13(window_V_118_2_i_reload),
    .din14(window_V_127_2_i_reload),
    .din15(window_V_136_2_i_reload),
    .din16(window_V_145_2_i_reload),
    .din17(window_V_154_2_i_reload),
    .din18(window_V_163_2_i_reload),
    .din19(window_V_172_2_i_reload),
    .din20(window_V_181_2_i_reload),
    .din21(window_V_190_2_i_reload),
    .din22(window_V_199_2_i_reload),
    .din23(window_V_208_2_i_reload),
    .din24(window_V_217_2_i_reload),
    .din25(window_V_226_2_i_reload),
    .din26(window_V_235_2_i_reload),
    .din27(window_V_244_2_i_reload),
    .din28(window_V_253_2_i_reload),
    .din29(window_V_262_2_i_reload),
    .din30(window_V_271_2_i_reload),
    .din31(window_V_280_2_i_reload),
    .din32(trunc_ln76_fu_2593_p1),
    .dout(px_V_1_fu_2721_p34)
);

vgg_accelerator_mux_325_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_325_8_1_1_U1082(
    .din0(window_V_9_reload),
    .din1(window_V_16_reload),
    .din2(window_V_23_reload),
    .din3(window_V_30_reload),
    .din4(window_V_37_reload),
    .din5(window_V_44_reload),
    .din6(window_V_51_reload),
    .din7(window_V_58_reload),
    .din8(window_V_65_reload),
    .din9(window_V_72_reload),
    .din10(window_V_79_reload),
    .din11(window_V_86_reload),
    .din12(window_V_93_reload),
    .din13(window_V_100_reload),
    .din14(window_V_107_reload),
    .din15(window_V_114_reload),
    .din16(window_V_121_reload),
    .din17(window_V_128_reload),
    .din18(window_V_135_reload),
    .din19(window_V_142_reload),
    .din20(window_V_149_reload),
    .din21(window_V_156_reload),
    .din22(window_V_163_reload),
    .din23(window_V_170_reload),
    .din24(window_V_177_reload),
    .din25(window_V_184_reload),
    .din26(window_V_191_reload),
    .din27(window_V_198_reload),
    .din28(window_V_205_reload),
    .din29(window_V_212_reload),
    .din30(window_V_219_reload),
    .din31(window_V_1_reload),
    .din32(trunc_ln76_fu_2593_p1),
    .dout(px_V_2_fu_2802_p34)
);

vgg_accelerator_mux_325_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_325_8_1_1_U1083(
    .din0(window_V_3_2_i_reload),
    .din1(window_V_12_2_i_reload),
    .din2(window_V_21_2_i_reload),
    .din3(window_V_30_2_i_reload),
    .din4(window_V_39_2_i_reload),
    .din5(window_V_48_2_i_reload),
    .din6(window_V_57_2_i_reload),
    .din7(window_V_66_2_i_reload),
    .din8(window_V_75_2_i_reload),
    .din9(window_V_84_2_i_reload),
    .din10(window_V_93_2_i_reload),
    .din11(window_V_102_2_i_reload),
    .din12(window_V_111_2_i_reload),
    .din13(window_V_120_2_i_reload),
    .din14(window_V_129_2_i_reload),
    .din15(window_V_138_2_i_reload),
    .din16(window_V_147_2_i_reload),
    .din17(window_V_156_2_i_reload),
    .din18(window_V_165_2_i_reload),
    .din19(window_V_174_2_i_reload),
    .din20(window_V_183_2_i_reload),
    .din21(window_V_192_2_i_reload),
    .din22(window_V_201_2_i_reload),
    .din23(window_V_210_2_i_reload),
    .din24(window_V_219_2_i_reload),
    .din25(window_V_228_2_i_reload),
    .din26(window_V_237_2_i_reload),
    .din27(window_V_246_2_i_reload),
    .din28(window_V_255_2_i_reload),
    .din29(window_V_264_2_i_reload),
    .din30(window_V_273_2_i_reload),
    .din31(window_V_282_2_i_reload),
    .din32(trunc_ln76_fu_2593_p1),
    .dout(px_V_3_fu_2883_p34)
);

vgg_accelerator_mux_325_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_325_8_1_1_U1084(
    .din0(window_V_10_reload),
    .din1(window_V_17_reload),
    .din2(window_V_24_reload),
    .din3(window_V_31_reload),
    .din4(window_V_38_reload),
    .din5(window_V_45_reload),
    .din6(window_V_52_reload),
    .din7(window_V_59_reload),
    .din8(window_V_66_reload),
    .din9(window_V_73_reload),
    .din10(window_V_80_reload),
    .din11(window_V_87_reload),
    .din12(window_V_94_reload),
    .din13(window_V_101_reload),
    .din14(window_V_108_reload),
    .din15(window_V_115_reload),
    .din16(window_V_122_reload),
    .din17(window_V_129_reload),
    .din18(window_V_136_reload),
    .din19(window_V_143_reload),
    .din20(window_V_150_reload),
    .din21(window_V_157_reload),
    .din22(window_V_164_reload),
    .din23(window_V_171_reload),
    .din24(window_V_178_reload),
    .din25(window_V_185_reload),
    .din26(window_V_192_reload),
    .din27(window_V_199_reload),
    .din28(window_V_206_reload),
    .din29(window_V_213_reload),
    .din30(window_V_220_reload),
    .din31(window_V_2_reload),
    .din32(trunc_ln76_fu_2593_p1),
    .dout(px_V_4_fu_2964_p34)
);

vgg_accelerator_mux_325_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_325_8_1_1_U1085(
    .din0(window_V_11_reload),
    .din1(window_V_18_reload),
    .din2(window_V_25_reload),
    .din3(window_V_32_reload),
    .din4(window_V_39_reload),
    .din5(window_V_46_reload),
    .din6(window_V_53_reload),
    .din7(window_V_60_reload),
    .din8(window_V_67_reload),
    .din9(window_V_74_reload),
    .din10(window_V_81_reload),
    .din11(window_V_88_reload),
    .din12(window_V_95_reload),
    .din13(window_V_102_reload),
    .din14(window_V_109_reload),
    .din15(window_V_116_reload),
    .din16(window_V_123_reload),
    .din17(window_V_130_reload),
    .din18(window_V_137_reload),
    .din19(window_V_144_reload),
    .din20(window_V_151_reload),
    .din21(window_V_158_reload),
    .din22(window_V_165_reload),
    .din23(window_V_172_reload),
    .din24(window_V_179_reload),
    .din25(window_V_186_reload),
    .din26(window_V_193_reload),
    .din27(window_V_200_reload),
    .din28(window_V_207_reload),
    .din29(window_V_214_reload),
    .din30(window_V_221_reload),
    .din31(window_V_3_reload),
    .din32(trunc_ln76_fu_2593_p1),
    .dout(px_V_5_fu_3034_p34)
);

vgg_accelerator_mux_325_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_325_8_1_1_U1086(
    .din0(window_V_6_2_i_reload),
    .din1(window_V_15_2_i_reload),
    .din2(window_V_24_2_i_reload),
    .din3(window_V_33_2_i_reload),
    .din4(window_V_42_2_i_reload),
    .din5(window_V_51_2_i_reload),
    .din6(window_V_60_2_i_reload),
    .din7(window_V_69_2_i_reload),
    .din8(window_V_78_2_i_reload),
    .din9(window_V_87_2_i_reload),
    .din10(window_V_96_2_i_reload),
    .din11(window_V_105_2_i_reload),
    .din12(window_V_114_2_i_reload),
    .din13(window_V_123_2_i_reload),
    .din14(window_V_132_2_i_reload),
    .din15(window_V_141_2_i_reload),
    .din16(window_V_150_2_i_reload),
    .din17(window_V_159_2_i_reload),
    .din18(window_V_168_2_i_reload),
    .din19(window_V_177_2_i_reload),
    .din20(window_V_186_2_i_reload),
    .din21(window_V_195_2_i_reload),
    .din22(window_V_204_2_i_reload),
    .din23(window_V_213_2_i_reload),
    .din24(window_V_222_2_i_reload),
    .din25(window_V_231_2_i_reload),
    .din26(window_V_240_2_i_reload),
    .din27(window_V_249_2_i_reload),
    .din28(window_V_258_2_i_reload),
    .din29(window_V_267_2_i_reload),
    .din30(window_V_276_2_i_reload),
    .din31(window_V_285_2_i_reload),
    .din32(trunc_ln76_fu_2593_p1),
    .dout(px_V_6_fu_3104_p34)
);

vgg_accelerator_mux_325_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_325_8_1_1_U1087(
    .din0(window_V_12_reload),
    .din1(window_V_19_reload),
    .din2(window_V_26_reload),
    .din3(window_V_33_reload),
    .din4(window_V_40_reload),
    .din5(window_V_47_reload),
    .din6(window_V_54_reload),
    .din7(window_V_61_reload),
    .din8(window_V_68_reload),
    .din9(window_V_75_reload),
    .din10(window_V_82_reload),
    .din11(window_V_89_reload),
    .din12(window_V_96_reload),
    .din13(window_V_103_reload),
    .din14(window_V_110_reload),
    .din15(window_V_117_reload),
    .din16(window_V_124_reload),
    .din17(window_V_131_reload),
    .din18(window_V_138_reload),
    .din19(window_V_145_reload),
    .din20(window_V_152_reload),
    .din21(window_V_159_reload),
    .din22(window_V_166_reload),
    .din23(window_V_173_reload),
    .din24(window_V_180_reload),
    .din25(window_V_187_reload),
    .din26(window_V_194_reload),
    .din27(window_V_201_reload),
    .din28(window_V_208_reload),
    .din29(window_V_215_reload),
    .din30(window_V_222_reload),
    .din31(window_V_4_reload),
    .din32(trunc_ln76_fu_2593_p1),
    .dout(px_V_7_fu_3174_p34)
);

vgg_accelerator_mux_325_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_325_8_1_1_U1088(
    .din0(window_V_13_reload),
    .din1(window_V_20_reload),
    .din2(window_V_27_reload),
    .din3(window_V_34_reload),
    .din4(window_V_41_reload),
    .din5(window_V_48_reload),
    .din6(window_V_55_reload),
    .din7(window_V_62_reload),
    .din8(window_V_69_reload),
    .din9(window_V_76_reload),
    .din10(window_V_83_reload),
    .din11(window_V_90_reload),
    .din12(window_V_97_reload),
    .din13(window_V_104_reload),
    .din14(window_V_111_reload),
    .din15(window_V_118_reload),
    .din16(window_V_125_reload),
    .din17(window_V_132_reload),
    .din18(window_V_139_reload),
    .din19(window_V_146_reload),
    .din20(window_V_153_reload),
    .din21(window_V_160_reload),
    .din22(window_V_167_reload),
    .din23(window_V_174_reload),
    .din24(window_V_181_reload),
    .din25(window_V_188_reload),
    .din26(window_V_195_reload),
    .din27(window_V_202_reload),
    .din28(window_V_209_reload),
    .din29(window_V_216_reload),
    .din30(window_V_223_reload),
    .din31(window_V_5_reload),
    .din32(trunc_ln76_fu_2593_p1),
    .dout(px_V_8_fu_3244_p34)
);

vgg_accelerator_mul_8s_5s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8s_5s_12_1_1_U1089(
    .din0(px_V_reg_4386),
    .din1(conv3_weights_q4),
    .dout(mul_ln1347_fu_3332_p2)
);

vgg_accelerator_mul_8s_5s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8s_5s_12_1_1_U1090(
    .din0(px_V_1_reg_4396),
    .din1(conv3_weights_q3),
    .dout(mul_ln1347_1_fu_3345_p2)
);

vgg_accelerator_mul_8s_5s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8s_5s_12_1_1_U1091(
    .din0(px_V_2_reg_4406),
    .din1(conv3_weights_q2),
    .dout(mul_ln1347_2_fu_3358_p2)
);

vgg_accelerator_mul_8s_5s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8s_5s_12_1_1_U1092(
    .din0(px_V_3_reg_4416),
    .din1(conv3_weights_q1),
    .dout(mul_ln1347_3_fu_3371_p2)
);

vgg_accelerator_mul_8s_5s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8s_5s_12_1_1_U1093(
    .din0(px_V_4_reg_4426),
    .din1(conv3_weights_q0),
    .dout(mul_ln1347_4_fu_3384_p2)
);

vgg_accelerator_mul_8s_5s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8s_5s_12_1_1_U1094(
    .din0(px_V_5_reg_4431),
    .din1(conv3_weights_q3),
    .dout(mul_ln1347_5_fu_3811_p2)
);

vgg_accelerator_mul_8s_5s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8s_5s_12_1_1_U1095(
    .din0(px_V_6_reg_4436),
    .din1(conv3_weights_q2),
    .dout(mul_ln1347_6_fu_3824_p2)
);

vgg_accelerator_mul_8s_5s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8s_5s_12_1_1_U1096(
    .din0(px_V_7_reg_4441),
    .din1(conv3_weights_q1),
    .dout(mul_ln1347_7_fu_3837_p2)
);

vgg_accelerator_mul_8s_5s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mul_8s_5s_12_1_1_U1097(
    .din0(px_V_8_reg_4446),
    .din1(conv3_weights_q0),
    .dout(mul_ln1347_8_fu_3850_p2)
);

vgg_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln71_fu_2577_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ch_fu_702 <= add_ln71_fu_2583_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ch_fu_702 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lhs_fu_698 <= sext_ln66_cast_fu_2560_p1;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        lhs_fu_698 <= acc_V_fu_4201_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_10_reg_4506 <= acc_V_10_fu_3790_p2;
        icmp_ln71_1_reg_4451_pp0_iter1_reg <= icmp_ln71_1_reg_4451;
        icmp_ln71_reg_4369 <= icmp_ln71_fu_2577_p2;
        mul_ln1347_5_reg_4517 <= mul_ln1347_5_fu_3811_p2;
        mul_ln1347_6_reg_4522 <= mul_ln1347_6_fu_3824_p2;
        mul_ln1347_7_reg_4527 <= mul_ln1347_7_fu_3837_p2;
        mul_ln1347_8_reg_4532 <= mul_ln1347_8_fu_3850_p2;
        p_Result_8_reg_4500 <= ret_V_4_fu_3776_p2[32'd32];
        p_Result_9_reg_4511 <= acc_V_10_fu_3790_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        acc_V_reg_4537 <= acc_V_fu_4201_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln71_fu_2577_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln76_2_reg_4373 <= add_ln76_2_fu_2629_p2;
        icmp_ln71_1_reg_4451 <= icmp_ln71_1_fu_3314_p2;
        px_V_1_reg_4396 <= px_V_1_fu_2721_p34;
        px_V_2_reg_4406 <= px_V_2_fu_2802_p34;
        px_V_3_reg_4416 <= px_V_3_fu_2883_p34;
        px_V_4_reg_4426 <= px_V_4_fu_2964_p34;
        px_V_5_reg_4431 <= px_V_5_fu_3034_p34;
        px_V_6_reg_4436 <= px_V_6_fu_3104_p34;
        px_V_7_reg_4441 <= px_V_7_fu_3174_p34;
        px_V_8_reg_4446 <= px_V_8_fu_3244_p34;
        px_V_reg_4386 <= px_V_fu_2640_p34;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln71_reg_4369 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_ln1347_1_reg_4460 <= mul_ln1347_1_fu_3345_p2;
        mul_ln1347_2_reg_4465 <= mul_ln1347_2_fu_3358_p2;
        mul_ln1347_3_reg_4470 <= mul_ln1347_3_fu_3371_p2;
        mul_ln1347_4_reg_4475 <= mul_ln1347_4_fu_3384_p2;
        mul_ln1347_reg_4455 <= mul_ln1347_fu_3332_p2;
    end
end

always @ (*) begin
    if (((icmp_ln71_reg_4369 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln71_reg_4369 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ch_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_ch_1 = ch_fu_702;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            conv3_weights_address0 = zext_ln76_12_fu_3425_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            conv3_weights_address0 = zext_ln76_8_fu_2959_p1;
        end else begin
            conv3_weights_address0 = 'bx;
        end
    end else begin
        conv3_weights_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            conv3_weights_address1 = zext_ln76_11_fu_3415_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            conv3_weights_address1 = zext_ln76_7_fu_2878_p1;
        end else begin
            conv3_weights_address1 = 'bx;
        end
    end else begin
        conv3_weights_address1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            conv3_weights_address2 = zext_ln76_10_fu_3405_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            conv3_weights_address2 = zext_ln76_6_fu_2797_p1;
        end else begin
            conv3_weights_address2 = 'bx;
        end
    end else begin
        conv3_weights_address2 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            conv3_weights_address3 = zext_ln76_9_fu_3395_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            conv3_weights_address3 = zext_ln76_5_fu_2716_p1;
        end else begin
            conv3_weights_address3 = 'bx;
        end
    end else begin
        conv3_weights_address3 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        conv3_weights_ce0 = 1'b1;
    end else begin
        conv3_weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        conv3_weights_ce1 = 1'b1;
    end else begin
        conv3_weights_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        conv3_weights_ce2 = 1'b1;
    end else begin
        conv3_weights_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        conv3_weights_ce3 = 1'b1;
    end else begin
        conv3_weights_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv3_weights_ce4 = 1'b1;
    end else begin
        conv3_weights_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln71_1_reg_4451_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_conv3_blk_n = s_conv3_full_n;
    end else begin
        s_conv3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln71_1_reg_4451_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_conv3_write = 1'b1;
    end else begin
        s_conv3_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Range1_all_zeros_fu_4298_p2 = ((tmp_1_fu_4288_p4 == 11'd0) ? 1'b1 : 1'b0);

assign acc_V_10_fu_3790_p2 = ($signed(acc_V_9_fu_3749_p3) + $signed(sext_ln1347_9_fu_3772_p1));

assign acc_V_11_fu_3878_p3 = ((xor_ln302_4_fu_3866_p2[0:0] == 1'b1) ? select_ln346_4_fu_3870_p3 : acc_V_10_reg_4506);

assign acc_V_12_fu_3918_p2 = ($signed(acc_V_11_fu_3878_p3) + $signed(sext_ln1347_11_fu_3900_p1));

assign acc_V_13_fu_3958_p3 = ((xor_ln302_5_fu_3944_p2[0:0] == 1'b1) ? select_ln346_5_fu_3950_p3 : acc_V_12_fu_3918_p2);

assign acc_V_14_fu_3999_p2 = ($signed(acc_V_13_fu_3958_p3) + $signed(sext_ln1347_13_fu_3981_p1));

assign acc_V_15_fu_4039_p3 = ((xor_ln302_6_fu_4025_p2[0:0] == 1'b1) ? select_ln346_6_fu_4031_p3 : acc_V_14_fu_3999_p2);

assign acc_V_16_fu_4080_p2 = ($signed(acc_V_15_fu_4039_p3) + $signed(sext_ln1347_15_fu_4062_p1));

assign acc_V_17_fu_4120_p3 = ((xor_ln302_7_fu_4106_p2[0:0] == 1'b1) ? select_ln346_7_fu_4112_p3 : acc_V_16_fu_4080_p2);

assign acc_V_18_fu_4161_p2 = ($signed(acc_V_17_fu_4120_p3) + $signed(sext_ln1347_17_fu_4143_p1));

assign acc_V_19_fu_4224_p3 = ((tmp_fu_4217_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln71_fu_4214_p1);

assign acc_V_2_fu_3466_p0 = lhs_fu_698;

assign acc_V_2_fu_3466_p2 = ($signed(acc_V_2_fu_3466_p0) + $signed(sext_ln1347_1_fu_3448_p1));

assign acc_V_3_fu_3506_p3 = ((xor_ln302_fu_3492_p2[0:0] == 1'b1) ? select_ln346_fu_3498_p3 : acc_V_2_fu_3466_p2);

assign acc_V_4_fu_3547_p2 = ($signed(acc_V_3_fu_3506_p3) + $signed(sext_ln1347_3_fu_3529_p1));

assign acc_V_5_fu_3587_p3 = ((xor_ln302_1_fu_3573_p2[0:0] == 1'b1) ? select_ln346_1_fu_3579_p3 : acc_V_4_fu_3547_p2);

assign acc_V_6_fu_3628_p2 = ($signed(acc_V_5_fu_3587_p3) + $signed(sext_ln1347_5_fu_3610_p1));

assign acc_V_7_fu_3668_p3 = ((xor_ln302_2_fu_3654_p2[0:0] == 1'b1) ? select_ln346_2_fu_3660_p3 : acc_V_6_fu_3628_p2);

assign acc_V_8_fu_3709_p2 = ($signed(acc_V_7_fu_3668_p3) + $signed(sext_ln1347_7_fu_3691_p1));

assign acc_V_9_fu_3749_p3 = ((xor_ln302_3_fu_3735_p2[0:0] == 1'b1) ? select_ln346_3_fu_3741_p3 : acc_V_8_fu_3709_p2);

assign acc_V_fu_4201_p3 = ((xor_ln302_8_fu_4187_p2[0:0] == 1'b1) ? select_ln346_8_fu_4193_p3 : acc_V_18_fu_4161_p2);

assign add_ln71_fu_2583_p2 = (ap_sig_allocacmp_ch_1 + 6'd1);

assign add_ln76_10_fu_3420_p2 = (add_ln76_2_reg_4373 + 15'd8);

assign add_ln76_1_fu_2619_p2 = (zext_ln71_1_cast_fu_2556_p1 + zext_ln76_2_fu_2615_p1);

assign add_ln76_2_fu_2629_p2 = (zext_ln76_3_fu_2625_p1 + zext_ln76_cast_fu_2552_p1);

assign add_ln76_3_fu_2710_p2 = (add_ln76_2_fu_2629_p2 + 15'd1);

assign add_ln76_4_fu_2791_p2 = (add_ln76_2_fu_2629_p2 + 15'd2);

assign add_ln76_5_fu_2872_p2 = (add_ln76_2_fu_2629_p2 + 15'd3);

assign add_ln76_6_fu_2953_p2 = (add_ln76_2_fu_2629_p2 + 15'd4);

assign add_ln76_7_fu_3390_p2 = (add_ln76_2_reg_4373 + 15'd5);

assign add_ln76_8_fu_3400_p2 = (add_ln76_2_reg_4373 + 15'd6);

assign add_ln76_9_fu_3410_p2 = (add_ln76_2_reg_4373 + 15'd7);

assign add_ln76_fu_2609_p2 = (zext_ln76_1_fu_2605_p1 + zext_ln71_fu_2589_p1);

assign add_ln856_fu_4274_p2 = (trunc_ln377_1_fu_4254_p4 + zext_ln377_1_fu_4264_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((icmp_ln71_1_reg_4451_pp0_iter1_reg == 1'd1) & (s_conv3_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln71_1_reg_4451_pp0_iter1_reg == 1'd1) & (s_conv3_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln71_1_reg_4451_pp0_iter1_reg == 1'd1) & (s_conv3_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter2 = ((icmp_ln71_1_reg_4451_pp0_iter1_reg == 1'd1) & (s_conv3_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign conv3_weights_address4 = zext_ln76_4_fu_2635_p1;

assign deleted_zeros_fu_4324_p2 = (or_ln888_fu_4318_p2 & Range1_all_zeros_fu_4298_p2);

assign icmp_ln71_1_fu_3314_p2 = ((add_ln71_fu_2583_p2 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_2577_p2 = ((ap_sig_allocacmp_ch_1 == 6'd32) ? 1'b1 : 1'b0);

assign or_ln888_fu_4318_p2 = (xor_ln888_fu_4312_p2 | p_Result_18_fu_4280_p3);

assign overflow_1_fu_3486_p2 = (xor_ln895_1_fu_3480_p2 & p_Result_1_fu_3472_p3);

assign overflow_2_fu_3567_p2 = (xor_ln895_2_fu_3561_p2 & p_Result_3_fu_3553_p3);

assign overflow_3_fu_3648_p2 = (xor_ln895_3_fu_3642_p2 & p_Result_5_fu_3634_p3);

assign overflow_4_fu_3729_p2 = (xor_ln895_4_fu_3723_p2 & p_Result_7_fu_3715_p3);

assign overflow_5_fu_3861_p2 = (xor_ln895_5_fu_3856_p2 & p_Result_9_reg_4511);

assign overflow_6_fu_3938_p2 = (xor_ln895_6_fu_3932_p2 & p_Result_11_fu_3924_p3);

assign overflow_7_fu_4019_p2 = (xor_ln895_7_fu_4013_p2 & p_Result_13_fu_4005_p3);

assign overflow_8_fu_4100_p2 = (xor_ln895_8_fu_4094_p2 & p_Result_15_fu_4086_p3);

assign overflow_9_fu_4181_p2 = (xor_ln895_9_fu_4175_p2 & p_Result_17_fu_4167_p3);

assign overflow_fu_4336_p2 = (xor_ln895_fu_4330_p2 | p_Result_18_fu_4280_p3);

assign p_Result_10_fu_3910_p3 = ret_V_5_fu_3904_p2[32'd32];

assign p_Result_11_fu_3924_p3 = acc_V_12_fu_3918_p2[32'd31];

assign p_Result_12_fu_3991_p3 = ret_V_6_fu_3985_p2[32'd32];

assign p_Result_13_fu_4005_p3 = acc_V_14_fu_3999_p2[32'd31];

assign p_Result_14_fu_4072_p3 = ret_V_7_fu_4066_p2[32'd32];

assign p_Result_15_fu_4086_p3 = acc_V_16_fu_4080_p2[32'd31];

assign p_Result_16_fu_4153_p3 = ret_V_8_fu_4147_p2[32'd32];

assign p_Result_17_fu_4167_p3 = acc_V_18_fu_4161_p2[32'd31];

assign p_Result_18_fu_4280_p3 = p_Val2_20_fu_4268_p2[32'd7];

assign p_Result_1_fu_3472_p3 = acc_V_2_fu_3466_p2[32'd31];

assign p_Result_2_fu_3539_p3 = ret_V_1_fu_3533_p2[32'd32];

assign p_Result_3_fu_3553_p3 = acc_V_4_fu_3547_p2[32'd31];

assign p_Result_4_fu_3620_p3 = ret_V_2_fu_3614_p2[32'd32];

assign p_Result_5_fu_3634_p3 = acc_V_6_fu_3628_p2[32'd31];

assign p_Result_6_fu_3701_p3 = ret_V_3_fu_3695_p2[32'd32];

assign p_Result_7_fu_3715_p3 = acc_V_8_fu_3709_p2[32'd31];

assign p_Result_s_fu_3458_p3 = ret_V_fu_3452_p2[32'd32];

assign p_Val2_1_fu_4232_p4 = {{acc_V_19_fu_4224_p3[19:12]}};

assign p_Val2_20_fu_4268_p2 = (p_Val2_1_fu_4232_p4 + zext_ln377_fu_4250_p1);

assign ret_V_1_fu_3533_p2 = ($signed(sext_ln813_1_fu_3514_p1) + $signed(sext_ln1347_2_fu_3525_p1));

assign ret_V_2_fu_3614_p2 = ($signed(sext_ln813_2_fu_3595_p1) + $signed(sext_ln1347_4_fu_3606_p1));

assign ret_V_3_fu_3695_p2 = ($signed(sext_ln813_3_fu_3676_p1) + $signed(sext_ln1347_6_fu_3687_p1));

assign ret_V_4_fu_3776_p2 = ($signed(sext_ln813_4_fu_3757_p1) + $signed(sext_ln1347_8_fu_3768_p1));

assign ret_V_5_fu_3904_p2 = ($signed(sext_ln813_5_fu_3885_p1) + $signed(sext_ln1347_10_fu_3896_p1));

assign ret_V_6_fu_3985_p2 = ($signed(sext_ln813_6_fu_3966_p1) + $signed(sext_ln1347_12_fu_3977_p1));

assign ret_V_7_fu_4066_p2 = ($signed(sext_ln813_7_fu_4047_p1) + $signed(sext_ln1347_14_fu_4058_p1));

assign ret_V_8_fu_4147_p2 = ($signed(sext_ln813_8_fu_4128_p1) + $signed(sext_ln1347_16_fu_4139_p1));

assign ret_V_fu_3452_p2 = ($signed(sext_ln813_fu_3433_p1) + $signed(sext_ln1347_fu_3444_p1));

assign rhs_1_fu_3518_p3 = {{mul_ln1347_1_reg_4460}, {8'd0}};

assign rhs_2_fu_3599_p3 = {{mul_ln1347_2_reg_4465}, {8'd0}};

assign rhs_3_fu_3680_p3 = {{mul_ln1347_3_reg_4470}, {8'd0}};

assign rhs_4_fu_3761_p3 = {{mul_ln1347_4_reg_4475}, {8'd0}};

assign rhs_5_fu_3889_p3 = {{mul_ln1347_5_reg_4517}, {8'd0}};

assign rhs_6_fu_3970_p3 = {{mul_ln1347_6_reg_4522}, {8'd0}};

assign rhs_7_fu_4051_p3 = {{mul_ln1347_7_reg_4527}, {8'd0}};

assign rhs_8_fu_4132_p3 = {{mul_ln1347_8_reg_4532}, {8'd0}};

assign rhs_fu_3437_p3 = {{mul_ln1347_reg_4455}, {8'd0}};

assign s_conv3_din = select_ln302_fu_4342_p3;

assign select_ln302_fu_4342_p3 = ((overflow_fu_4336_p2[0:0] == 1'b1) ? 7'd127 : add_ln856_fu_4274_p2);

assign select_ln346_1_fu_3579_p3 = ((overflow_2_fu_3567_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln346_2_fu_3660_p3 = ((overflow_3_fu_3648_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln346_3_fu_3741_p3 = ((overflow_4_fu_3729_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln346_4_fu_3870_p3 = ((overflow_5_fu_3861_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln346_5_fu_3950_p3 = ((overflow_6_fu_3938_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln346_6_fu_4031_p3 = ((overflow_7_fu_4019_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln346_7_fu_4112_p3 = ((overflow_8_fu_4100_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln346_8_fu_4193_p3 = ((overflow_9_fu_4181_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln346_fu_3498_p3 = ((overflow_1_fu_3486_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign sext_ln1347_10_fu_3896_p1 = rhs_5_fu_3889_p3;

assign sext_ln1347_11_fu_3900_p1 = rhs_5_fu_3889_p3;

assign sext_ln1347_12_fu_3977_p1 = rhs_6_fu_3970_p3;

assign sext_ln1347_13_fu_3981_p1 = rhs_6_fu_3970_p3;

assign sext_ln1347_14_fu_4058_p1 = rhs_7_fu_4051_p3;

assign sext_ln1347_15_fu_4062_p1 = rhs_7_fu_4051_p3;

assign sext_ln1347_16_fu_4139_p1 = rhs_8_fu_4132_p3;

assign sext_ln1347_17_fu_4143_p1 = rhs_8_fu_4132_p3;

assign sext_ln1347_1_fu_3448_p1 = rhs_fu_3437_p3;

assign sext_ln1347_2_fu_3525_p1 = rhs_1_fu_3518_p3;

assign sext_ln1347_3_fu_3529_p1 = rhs_1_fu_3518_p3;

assign sext_ln1347_4_fu_3606_p1 = rhs_2_fu_3599_p3;

assign sext_ln1347_5_fu_3610_p1 = rhs_2_fu_3599_p3;

assign sext_ln1347_6_fu_3687_p1 = rhs_3_fu_3680_p3;

assign sext_ln1347_7_fu_3691_p1 = rhs_3_fu_3680_p3;

assign sext_ln1347_8_fu_3768_p1 = rhs_4_fu_3761_p3;

assign sext_ln1347_9_fu_3772_p1 = rhs_4_fu_3761_p3;

assign sext_ln1347_fu_3444_p1 = rhs_fu_3437_p3;

assign sext_ln66_cast_fu_2560_p1 = $signed(sext_ln66);

assign sext_ln813_1_fu_3514_p1 = acc_V_3_fu_3506_p3;

assign sext_ln813_2_fu_3595_p1 = acc_V_5_fu_3587_p3;

assign sext_ln813_3_fu_3676_p1 = acc_V_7_fu_3668_p3;

assign sext_ln813_4_fu_3757_p1 = acc_V_9_fu_3749_p3;

assign sext_ln813_5_fu_3885_p1 = acc_V_11_fu_3878_p3;

assign sext_ln813_6_fu_3966_p1 = acc_V_13_fu_3958_p3;

assign sext_ln813_7_fu_4047_p1 = acc_V_15_fu_4039_p3;

assign sext_ln813_8_fu_4128_p1 = acc_V_17_fu_4120_p3;

assign sext_ln813_fu_3433_p0 = lhs_fu_698;

assign sext_ln813_fu_3433_p1 = sext_ln813_fu_3433_p0;

assign shl_ln76_2_fu_2597_p3 = {{trunc_ln76_fu_2593_p1}, {3'd0}};

assign tmp_1_fu_4288_p4 = {{acc_V_19_fu_4224_p3[30:20]}};

assign tmp_2_fu_4242_p3 = acc_V_19_fu_4224_p3[32'd11];

assign tmp_4_fu_4304_p3 = acc_V_19_fu_4224_p3[32'd19];

assign tmp_fu_4217_p3 = acc_V_reg_4537[32'd31];

assign trunc_ln377_1_fu_4254_p4 = {{acc_V_19_fu_4224_p3[18:12]}};

assign trunc_ln71_fu_4214_p1 = acc_V_reg_4537[30:0];

assign trunc_ln76_fu_2593_p1 = ap_sig_allocacmp_ch_1[4:0];

assign xor_ln302_1_fu_3573_p2 = (p_Result_3_fu_3553_p3 ^ p_Result_2_fu_3539_p3);

assign xor_ln302_2_fu_3654_p2 = (p_Result_5_fu_3634_p3 ^ p_Result_4_fu_3620_p3);

assign xor_ln302_3_fu_3735_p2 = (p_Result_7_fu_3715_p3 ^ p_Result_6_fu_3701_p3);

assign xor_ln302_4_fu_3866_p2 = (p_Result_9_reg_4511 ^ p_Result_8_reg_4500);

assign xor_ln302_5_fu_3944_p2 = (p_Result_11_fu_3924_p3 ^ p_Result_10_fu_3910_p3);

assign xor_ln302_6_fu_4025_p2 = (p_Result_13_fu_4005_p3 ^ p_Result_12_fu_3991_p3);

assign xor_ln302_7_fu_4106_p2 = (p_Result_15_fu_4086_p3 ^ p_Result_14_fu_4072_p3);

assign xor_ln302_8_fu_4187_p2 = (p_Result_17_fu_4167_p3 ^ p_Result_16_fu_4153_p3);

assign xor_ln302_fu_3492_p2 = (p_Result_s_fu_3458_p3 ^ p_Result_1_fu_3472_p3);

assign xor_ln888_fu_4312_p2 = (tmp_4_fu_4304_p3 ^ 1'd1);

assign xor_ln895_1_fu_3480_p2 = (p_Result_s_fu_3458_p3 ^ 1'd1);

assign xor_ln895_2_fu_3561_p2 = (p_Result_2_fu_3539_p3 ^ 1'd1);

assign xor_ln895_3_fu_3642_p2 = (p_Result_4_fu_3620_p3 ^ 1'd1);

assign xor_ln895_4_fu_3723_p2 = (p_Result_6_fu_3701_p3 ^ 1'd1);

assign xor_ln895_5_fu_3856_p2 = (p_Result_8_reg_4500 ^ 1'd1);

assign xor_ln895_6_fu_3932_p2 = (p_Result_10_fu_3910_p3 ^ 1'd1);

assign xor_ln895_7_fu_4013_p2 = (p_Result_12_fu_3991_p3 ^ 1'd1);

assign xor_ln895_8_fu_4094_p2 = (p_Result_14_fu_4072_p3 ^ 1'd1);

assign xor_ln895_9_fu_4175_p2 = (p_Result_16_fu_4153_p3 ^ 1'd1);

assign xor_ln895_fu_4330_p2 = (deleted_zeros_fu_4324_p2 ^ 1'd1);

assign zext_ln377_1_fu_4264_p1 = tmp_2_fu_4242_p3;

assign zext_ln377_fu_4250_p1 = tmp_2_fu_4242_p3;

assign zext_ln71_1_cast_fu_2556_p1 = zext_ln71_1;

assign zext_ln71_fu_2589_p1 = ap_sig_allocacmp_ch_1;

assign zext_ln76_10_fu_3405_p1 = add_ln76_8_fu_3400_p2;

assign zext_ln76_11_fu_3415_p1 = add_ln76_9_fu_3410_p2;

assign zext_ln76_12_fu_3425_p1 = add_ln76_10_fu_3420_p2;

assign zext_ln76_1_fu_2605_p1 = shl_ln76_2_fu_2597_p3;

assign zext_ln76_2_fu_2615_p1 = add_ln76_fu_2609_p2;

assign zext_ln76_3_fu_2625_p1 = add_ln76_1_fu_2619_p2;

assign zext_ln76_4_fu_2635_p1 = add_ln76_2_fu_2629_p2;

assign zext_ln76_5_fu_2716_p1 = add_ln76_3_fu_2710_p2;

assign zext_ln76_6_fu_2797_p1 = add_ln76_4_fu_2791_p2;

assign zext_ln76_7_fu_2878_p1 = add_ln76_5_fu_2872_p2;

assign zext_ln76_8_fu_2959_p1 = add_ln76_6_fu_2953_p2;

assign zext_ln76_9_fu_3395_p1 = add_ln76_7_fu_3390_p2;

assign zext_ln76_cast_fu_2552_p1 = zext_ln76;

endmodule //vgg_accelerator_layer_block_32_64_8_Pipeline_VITIS_LOOP_71_8
