// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module vgg_accelerator_dense_layer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TLAST,
        s_pool3_dout,
        s_pool3_num_data_valid,
        s_pool3_fifo_cap,
        s_pool3_empty_n,
        s_pool3_read
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [31:0] OUTPUT_STREAM_TDATA;
output   OUTPUT_STREAM_TVALID;
input   OUTPUT_STREAM_TREADY;
output  [3:0] OUTPUT_STREAM_TKEEP;
output  [3:0] OUTPUT_STREAM_TSTRB;
output  [0:0] OUTPUT_STREAM_TLAST;
input  [7:0] s_pool3_dout;
input  [6:0] s_pool3_num_data_valid;
input  [6:0] s_pool3_fifo_cap;
input   s_pool3_empty_n;
output   s_pool3_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg s_pool3_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] dense_bias_address0;
reg    dense_bias_ce0;
wire   [1:0] dense_bias_q0;
reg   [1:0] c_1_reg_179;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln140_fu_123_p2;
wire   [13:0] acc_V_41_fu_145_p3;
reg   [13:0] acc_V_41_reg_193;
wire    ap_CS_fsm_state5;
wire   [10:0] shl_ln_fu_157_p3;
reg   [10:0] shl_ln_reg_198;
wire   [0:0] icmp_ln161_fu_166_p2;
reg   [0:0] icmp_ln161_reg_203;
reg   [9:0] flat_img_V_address0;
reg    flat_img_V_ce0;
reg    flat_img_V_we0;
wire   [7:0] flat_img_V_q0;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_done;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_idle;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_ready;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_s_pool3_read;
wire   [9:0] grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_address0;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_ce0;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_we0;
wire   [7:0] grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_d0;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_done;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_idle;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_ready;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TREADY;
wire   [9:0] grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_address0;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_ce0;
wire   [31:0] grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TDATA;
wire    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID;
wire   [3:0] grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TKEEP;
wire   [3:0] grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TSTRB;
wire   [0:0] grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TLAST;
reg    grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg;
reg    ap_block_state1_ignore_call9;
wire    ap_CS_fsm_state2;
reg    grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln140_fu_135_p1;
reg   [1:0] c_fu_68;
wire   [1:0] add_ln140_fu_129_p2;
reg    ap_block_state1;
wire   [0:0] trunc_ln152_fu_154_p1;
wire    ap_CS_fsm_state7;
wire    regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    OUTPUT_STREAM_TVALID_int_regslice;
wire    OUTPUT_STREAM_TREADY_int_regslice;
wire    regslice_both_OUTPUT_STREAM_V_data_V_U_vld_out;
wire    regslice_both_OUTPUT_STREAM_V_keep_V_U_apdone_blk;
wire    regslice_both_OUTPUT_STREAM_V_keep_V_U_ack_in_dummy;
wire    regslice_both_OUTPUT_STREAM_V_keep_V_U_vld_out;
wire    regslice_both_OUTPUT_STREAM_V_strb_V_U_apdone_blk;
wire    regslice_both_OUTPUT_STREAM_V_strb_V_U_ack_in_dummy;
wire    regslice_both_OUTPUT_STREAM_V_strb_V_U_vld_out;
wire    regslice_both_OUTPUT_STREAM_V_last_V_U_apdone_blk;
wire    regslice_both_OUTPUT_STREAM_V_last_V_U_ack_in_dummy;
wire    regslice_both_OUTPUT_STREAM_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg = 1'b0;
#0 grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg = 1'b0;
end

vgg_accelerator_dense_layer_dense_bias_ROM_AUTO_1R #(
    .DataWidth( 2 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
dense_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_bias_address0),
    .ce0(dense_bias_ce0),
    .q0(dense_bias_q0)
);

vgg_accelerator_dense_layer_flat_img_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
flat_img_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(flat_img_V_address0),
    .ce0(flat_img_V_ce0),
    .we0(flat_img_V_we0),
    .d0(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_d0),
    .q0(flat_img_V_q0)
);

vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_135_1 grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start),
    .ap_done(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_done),
    .ap_idle(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_idle),
    .ap_ready(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_ready),
    .s_pool3_dout(s_pool3_dout),
    .s_pool3_num_data_valid(7'd0),
    .s_pool3_fifo_cap(7'd0),
    .s_pool3_empty_n(s_pool3_empty_n),
    .s_pool3_read(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_s_pool3_read),
    .flat_img_V_address0(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_address0),
    .flat_img_V_ce0(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_ce0),
    .flat_img_V_we0(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_we0),
    .flat_img_V_d0(grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_d0)
);

vgg_accelerator_dense_layer_Pipeline_VITIS_LOOP_146_3 grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start),
    .ap_done(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_done),
    .ap_idle(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_idle),
    .ap_ready(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_ready),
    .OUTPUT_STREAM_TREADY(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TREADY),
    .sext_ln141(acc_V_41_reg_193),
    .shl_ln(shl_ln_reg_198),
    .flat_img_V_address0(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_address0),
    .flat_img_V_ce0(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_ce0),
    .flat_img_V_q0(flat_img_V_q0),
    .output_packet_last_V(icmp_ln161_reg_203),
    .OUTPUT_STREAM_TDATA(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TDATA),
    .OUTPUT_STREAM_TVALID(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID),
    .OUTPUT_STREAM_TKEEP(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TKEEP),
    .OUTPUT_STREAM_TSTRB(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TSTRB),
    .OUTPUT_STREAM_TLAST(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TLAST)
);

vgg_accelerator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_OUTPUT_STREAM_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TDATA),
    .vld_in(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID),
    .ack_in(OUTPUT_STREAM_TREADY_int_regslice),
    .data_out(OUTPUT_STREAM_TDATA),
    .vld_out(regslice_both_OUTPUT_STREAM_V_data_V_U_vld_out),
    .ack_out(OUTPUT_STREAM_TREADY),
    .apdone_blk(regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk)
);

vgg_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_OUTPUT_STREAM_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TKEEP),
    .vld_in(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID),
    .ack_in(regslice_both_OUTPUT_STREAM_V_keep_V_U_ack_in_dummy),
    .data_out(OUTPUT_STREAM_TKEEP),
    .vld_out(regslice_both_OUTPUT_STREAM_V_keep_V_U_vld_out),
    .ack_out(OUTPUT_STREAM_TREADY),
    .apdone_blk(regslice_both_OUTPUT_STREAM_V_keep_V_U_apdone_blk)
);

vgg_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_OUTPUT_STREAM_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TSTRB),
    .vld_in(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID),
    .ack_in(regslice_both_OUTPUT_STREAM_V_strb_V_U_ack_in_dummy),
    .data_out(OUTPUT_STREAM_TSTRB),
    .vld_out(regslice_both_OUTPUT_STREAM_V_strb_V_U_vld_out),
    .ack_out(OUTPUT_STREAM_TREADY),
    .apdone_blk(regslice_both_OUTPUT_STREAM_V_strb_V_U_apdone_blk)
);

vgg_accelerator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_OUTPUT_STREAM_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TLAST),
    .vld_in(grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID),
    .ack_in(regslice_both_OUTPUT_STREAM_V_last_V_U_ack_in_dummy),
    .data_out(OUTPUT_STREAM_TLAST),
    .vld_out(regslice_both_OUTPUT_STREAM_V_last_V_U_vld_out),
    .ack_out(OUTPUT_STREAM_TREADY),
    .apdone_blk(regslice_both_OUTPUT_STREAM_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg <= 1'b1;
        end else if ((grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_ready == 1'b1)) begin
            grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg <= 1'b1;
        end else if ((grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_ready == 1'b1)) begin
            grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        c_fu_68 <= 2'd0;
    end else if (((icmp_ln140_fu_123_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        c_fu_68 <= add_ln140_fu_129_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        acc_V_41_reg_193[13 : 12] <= acc_V_41_fu_145_p3[13 : 12];
        icmp_ln161_reg_203 <= icmp_ln161_fu_166_p2;
        shl_ln_reg_198[10] <= shl_ln_fu_157_p3[10];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_1_reg_179 <= c_fu_68;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_bias_ce0 = 1'b1;
    end else begin
        dense_bias_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        flat_img_V_address0 = grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        flat_img_V_address0 = grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_address0;
    end else begin
        flat_img_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        flat_img_V_ce0 = grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_flat_img_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        flat_img_V_ce0 = grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_ce0;
    end else begin
        flat_img_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        flat_img_V_we0 = grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_flat_img_V_we0;
    end else begin
        flat_img_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        s_pool3_read = grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_s_pool3_read;
    end else begin
        s_pool3_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln140_fu_123_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OUTPUT_STREAM_TVALID = regslice_both_OUTPUT_STREAM_V_data_V_U_vld_out;

assign OUTPUT_STREAM_TVALID_int_regslice = grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TVALID;

assign acc_V_41_fu_145_p3 = {{dense_bias_q0}, {12'd0}};

assign add_ln140_fu_129_p2 = (c_fu_68 + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call9 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign dense_bias_address0 = zext_ln140_fu_135_p1;

assign grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start = grp_dense_layer_Pipeline_VITIS_LOOP_135_1_fu_89_ap_start_reg;

assign grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_OUTPUT_STREAM_TREADY = (ap_CS_fsm_state6 & OUTPUT_STREAM_TREADY_int_regslice);

assign grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start = grp_dense_layer_Pipeline_VITIS_LOOP_146_3_fu_97_ap_start_reg;

assign icmp_ln140_fu_123_p2 = ((c_fu_68 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln161_fu_166_p2 = ((c_1_reg_179 == 2'd1) ? 1'b1 : 1'b0);

assign shl_ln_fu_157_p3 = {{trunc_ln152_fu_154_p1}, {10'd0}};

assign trunc_ln152_fu_154_p1 = c_1_reg_179[0:0];

assign zext_ln140_fu_135_p1 = c_fu_68;

always @ (posedge ap_clk) begin
    acc_V_41_reg_193[11:0] <= 12'b000000000000;
    shl_ln_reg_198[9:0] <= 10'b0000000000;
end

endmodule //vgg_accelerator_dense_layer
